dangdangwalk/dangdang-walk

.github/labeler.yml, .github/workflows/pr_labeler_validator.yaml
새로운 PR이 열릴 때마다 다음 순서로 labeling 작업과 branch 이름 및 PR 제목 검사를 수행합니다.
- branch명의 prefix(frontend/backend)로 labeling
- labeling 실패 시 branch naming convention을 따르는지 검사
- PR title convention을 따르는지 검사
- branch naming convention을 따르지 않을 경우 convention을 따르도록 수정해달라는 comment 생성
- PR title convention을 따르지 않을 경우 convention을 따르도록 수정해달라는 comment 생성
https://www.notion.so/do0ori/PR-Labeler-Validator-deaa00f1c076473ba466a894a860dac3
제 개인 repo에서 작성한 GitHub Actions가 잘 돌아가는지 미리 테스트를 진행했고 문제 없이 돌아가는 것을 확인했습니다.
- 예시
- 예시
=> backend/DANG-100: PR labeling과 branch 이름 및 PR 제목 validation을 위한 GitHub Actions 추가

frontend/package-lock.json, frontend/package.json, frontend/src/app/api-test/page.tsx
클라이언트와 서버의 통신 확인을 위해 테스트용 페이지(/api-test)와 버튼을 구현
https://www.notion.so/do0ori/d4d6951161da42e59d1fef7faea101d7?pvs=4
- 예시
- 예시
=> frontend/DANG-88: 통신 확인용 페이지와 버튼을 구현

.github/labeler.yml, .github/workflows/pr_labeler_validator.yaml
- **규칙을 따르지 않으면 GitHub Actions가 실패하도록 업데이트**
- trigger 조건 추가
- 불필요한 권한 삭제
- 변수를 GITHUB_OUTPUT이 아닌 GITHUB_ENV에 저장해 사용
- step의 순서를 바꿔 필요한 step만 실행되도록 refactoring
https://www.notion.so/do0ori/GitHub-Actions-branch-PR-0b6bb5f7f4114100b0e9892f2cbb4c46
- 예시
- 예시
=> backend/DANG-124: GitHub Actions branch 이름 및 PR 제목 규칙 강제하도록 업데이트

.github/workflows/pr_labeler_validator.yaml
기존에는 모든 edit event 발생 시 job이 실행되기 때문에 PR body만 수정된 경우에도 job이 실행되어 comment가 여러 번 생성되는 상황이 발생했었다.
이를 방지하기 위해 edit event가 trigger되더라도 PR title이 수정되었을 때에만 job이 실행되도록 조건을 추가했다.
https://www.notion.so/do0ori/GitHub-Actions-pr_labeler_validator-edit-trigger-e252d47af50748ffa1b7330aa25814f3
- 예시
- 예시
=> infra/DANG-143: edit trigger 시 title 수정 때에만 job이 실행되도록  조건 추가

backend/src/app.module.ts, backend/src/auth/auth.controller.ts, backend/src/auth/auth.module.ts, backend/src/auth/auth.service.ts, backend/src/auth/google/google.controller.ts, backend/src/auth/google/google.service.ts, backend/src/auth/kakao/kakao.controller.ts, backend/src/auth/kakao/kakao.service.ts, backend/src/auth/naver/naver.controller.ts, backend/src/auth/naver/naver.service.ts
- DB 없이 일단 기본 로그인 로직 구현했습니다.
1. `auth/:provider`
2. `auth/:provider/callback`
- oauth_id가 users table에 존재하는지 확인
- 존재할 경우 (로그인): oauth_access_token과 oauth_refresh_token 저장..해야되나? 필요하지 않을 것 같기도..
- 존재하지 않는 경우 (회원가입): 새로운 user 생성 (nickname은 hash로)
- jwt payload
- user_id
- provider (kakao, naver, google)
```
{
user_id
provider
}
```
- controller와 service 모두 abstract class를 만들고 이를 extends하여 각 provider 별로 구현하는 식으로 작성했습니다.
https://www.notion.so/do0ori/DB-X-8b4d4d649d1b4601bd676e3fe8985ce7
- 현재 `auth.service.ts`에 jwt 발행 및 복호화하는 service를 작성했는데 token.service.ts로 따로 뺀다면 어느 위치에 만들면 좋을까요?
- 다음에 할 일
- DB 로직 추가
- `auth.guard.ts` 추가
- `user.decorator.ts` 추가
- 예시
- 예시
- if-else는 컴파일 시 처리가 되어 재컴파일 없이 …
=> backend/DANG-142: 로그인까지 구현 (DB X)

frontend/src/components/OAuthButton.tsx, frontend/src/pages/Login.tsx
로그인 후 로그인전 path로 redirect
산책(홈)페이지, 내정보페이지에 로그인버튼 만들때 아래의 코드 추가해야됨
```
const handleLogin = () => {
const currentURL = window.location.pathname;
navigate('/login', { state: { currentURL } });
};
```
- 예시
- 예시
=> frontend/DANG-202: 로그인 후 로그인전 path로 redirect

backend/src/users/userDogs.entity.ts, backend/src/users/users.module.ts, backend/src/users/users.service.ts
- 실제 DB에서는 SELECT가 되는데 코드상으로 빈배열이 리턴되는 에러때문에 임시로 하드코딩해둠
- 재경님이 Users를 써야해서 임시로 해둔것
- usersDogs 엔티티 파일 users 하위로 이동
- 예시
- 예시
=> backend/DANG-201: Users에 사용자의 강아지 목록 리턴하는 함수 임시로 하드코딩

backend/src/fixture/users.fixture.ts, backend/src/users/users.entity.ts, backend/src/users/users.service.spec.ts, backend/src/users/users.service.ts, backend/src/users/users.spec.ts
주요 변경 사항
- Users 엔티티에 새로운 create 메서드를 추가했습니다.
- 이 메서드는 사용자 정보를 입력받아 새로운 Users 인스턴스를 생성합니다.
- Users 엔티티에 대한 유닛 테스트 코드를 추가했습니다.
- 테스트 코드는 create 메서드가 올바르게 작동하는지 확인합니다.
- 예시
- 예시
=> backend/DANG-208: Users 엔티티에 create 메서드 추가 및 테스트 코드 작성

backend/src/auth/oauth/google.service.ts, backend/src/auth/oauth/kakao.service.ts
요청한 정보를 받을 redirect url을 지정했더니 oauth에서 client로 요청이 가서 cors 에러가 발생했다. authorize code는 이제 client에서 처리하므로 redirect url이 필요 없다. 따라서 oauth service에서 요청을 보낼 때 redirect url을 사용하지 않도록 수정했다.
https://www.notion.so/do0ori/redirect-url-6fa465a9c89448f2a2024fdb6f41e804
- 예시
- 예시
=> backend/DANG-213: oauth service에서 redirect url 삭제

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/auth/token/token.service.ts
refresh token만 존재하기 때문에 새로 발급할 access token에 넣을 provider를 알 수 없다.
그래서 그냥 refresh token의 payload에 provider도 추가했다.
db에서 user를 가져와서 userId를 얻고 그걸로 access token을 재발급한다. refresh token은 현재 값으로 재발급한다.
재발급한 access token은 body에, refresh token은 cookie에 담아 응답한다. 일단 oauth token을 재발급하는 과정은 뺐다.
필요할 지는 추후 생각해 볼 예정.
https://www.notion.so/do0ori/api-3e558a444d754123b34c394d802aa1d7
- 예시
- 예시
=> backend/DANG-214: 토큰 재발급 api 추가

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/auth/guards/auth.guard.ts, backend/src/auth/guards/refreshToken.guard.ts
- access token에 들어 있는 userId에 해당하는 사용자가 실제로 존재하는지 검증하는 로직을 추가했다.
- 대응하는 method를 auth service에 구현했다.
- refresh token guard에 빠진 await을 추가했다.
- 회원 탈퇴 api는 일단은 간단히 사용자를 직접 삭제하고 cookie를 clear하도록 했다. oauth 탈퇴 처리는 나중에.
https://www.notion.so/do0ori/api-b2132bd43d3642f8ab39a790569a958c
- 예시
- 예시
=> backend/DANG-196: auth guard에 사용자 존재 여부 확인 로직 추가 & 회원 탈퇴 api 추가

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/auth/oauth/google.service.ts, backend/src/auth/oauth/kakao.service.ts, backend/src/auth/oauth/oauth.service.interface.ts
- request body에 redirectURI field가 추가되었다.
- oauth server로 요청 시 전달받은 redirectURI를 사용하도록 추가했다.
https://www.notion.so/do0ori/login-redirect-uri-755f488aab7e4fe9b2fc551251cc6da4
- 예시
- 예시
=> backend/DANG-224: login 로직에 redirect uri 추가

docker-compose-dev.yml, frontend/Dockerfile
주요 변경사항
- 프론트엔드 상태 확인을 위해 HEALTHCHECK CMD를 추가합니다.
- 상태 확인은 http://localhost:3000/health 를 컬링하고 실패하면 1로 종료한다.
- 이전에는 target: dev로 인해 프론트엔드가 제대로 빌드되지 않는 문제가 있었습니다.
- frontend 서비스에서 target: dev를 제거했습니다.
- https://www.notion.so/do0ori/DockerFile-health-Check-b59b652cb3434c5795efb628fe171707?pvs=4
- 예시
- 예시
=> Infra/DANG 227: DockerFile health Check를 추가하기

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/auth/oauth/kakao.service.ts, backend/src/auth/oauth/naver.service.ts, backend/src/auth/oauth/oauth.service.interface.ts, backend/src/users/users.service.ts
- oauth service에서도 따로 logout을 해주어야 한다.
- 계정의 세션을 만료시키는 것은 아니다.
- "카카오계정과 함께 로그아웃"으로 계정의 세션까지 만료시킬 수 있으나 Logout Redirect URI도 따로 등록해야 한다.
- 그런데 카카오 계정은 보통 사람마다 하나이고 본인 계정을 사용할 것이기 때문에 카카오계정 세션까지 만료시킬 필요는 없다고 판단해서 단순히 token을 만료시키는 logout api를 사용했다.
- kakao, naver는 token을 만료시키는 방법을 사용한다.
- google은 따로 logout api가 없는 것 같다. (생각해보면 자동으로 로그인되지 않고 매 로그인마다 계정을 선택해서 로그인해야 하기 때문에 굳이 필요가 없다.)
- google을 제외한 provider에서 logout 요청 발생 시 oauth api를 통해 oauth token을 만료시켜 로그아웃 처리를 한다.
- 로그아웃 후 바로 로그인 페이지나 홈 페이지로 이동하므로 db에 저장해둔 oauth access/refresh token은 굳이 삭제할 필요는 없을 것 같다.
- 자연스럽게 다음 로그인 때 oauth access/refresh token이 갱신된다.
https://www.notion.so/do0ori/oauth-logut-3d761d19cad24a8baf0759a6bbdb6951
postmane을 활용해 테스트 완료
- 예시
- 예시
- 함수는 한 가지 일을 해야 …
=> backend/DANG-226: oauth logut 추가

backend/src/auth/auth.service.ts, backend/src/auth/oauth/google.service.ts, backend/src/auth/oauth/kakao.service.ts, backend/src/auth/oauth/naver.service.ts, backend/src/auth/oauth/oauth.service.interface.ts
없는 줄 알았는데 token 삭제하는 api가 있어서 추가했다.
또 해당 service의 이름을 더 명확하게 변경했다. (requestLogout -> requestTokenExpiration)
https://www.notion.so/do0ori/oauth-logout-google-3cee27423fa54bd28f2088d20fcdc1e7
- 예시
- 예시
=> backend/DANG-239: google에 대한 oauth logout 추가

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/auth/oauth/kakao.service.ts, backend/src/auth/oauth/naver.service.ts
네이버와 구글은 로그아웃 로직 동일하게, 카카오는 연결 끊기 api를 활용해 oauth 탈퇴를 구현했다.
일단은 여전히 사용자를 table에서 실제로 삭제한다.
https://www.notion.so/do0ori/oauth-deactivate-d478a4c2e99c4fc4be61fec9269885f4
- 예시
- 예시
=> backend/DANG-231: oauth deactivate 추가

backend/src/auth/auth.controller.ts
redirectURI가 full path인 줄 알고 그대로 넘겼는데 상대경로로 전달되는 관계로 redirectURI를 request body에서 꺼내서 앞에 cors origin을 붙여주는 코드를 추가했다.
https://www.notion.so/do0ori/redirect-uri-2c3f6f069b6b48a1bdb6bd7e25c628ba
- 예시
- 예시
=> backend/DANG-243: 상대 경로인 redirectURI를 full path로 가공하는 코드 추가

backend/src/common/health/health.controller.ts
AuthGuard를 global로 사용하면서 health check에도 적용이 되었다.
health check는 guard가 필요없기 때문에 decorator로 skip해주었다.
https://www.notion.so/do0ori/health-check-guard-skip-36863d67215d4f41972d2eb9a5d84e49
- 예시
- 예시
=> backend/DANG-246: health check api에 SkipAuthGuard 추가

backend/src/auth/auth.service.ts, backend/src/auth/oauth/google.service.ts, backend/src/auth/oauth/kakao.service.ts, backend/src/auth/oauth/naver.service.ts, backend/src/auth/oauth/oauth.service.interface.ts
- 각 oauth service에 토큰 재발급 요청을 보내 새로운 access/refresh token을 받는 `requestTokenRefresh`라는 method를 추가했다.
- 모두 기본적으로 새로운 access token을 발급해준다.
- refresh token은 provider마다 다르다.
- kakao의 경우 refresh token의 만료 기간이 1개월 이내 일 경우에만 새로운 refresh token이 발급된다고 한다.
- naver의 경우는 refresh token의 만료 기간을 늘려줄 뿐 새로운 refresh token을 발급해주지는 않는다. 처음에 발급받은 refresh token을 그대로 사용하면 된다.
- google은 사용자가 access를 취소할 때까지 처음에 발급 받은 refresh token을 계속 사용할 수 있기 때문에 마찬가지로 따로 refresh token을 새로 발급해주지 않는다.
https://www.notion.so/do0ori/oauth-token-d1d639d2eb5040c1b638d5649ccb5cb6
전반적으로 refactoring을 할 예정
- 예시
- 예시
=> backend/DANG-244: oauth token 갱신 추가

backend/src/users/users.entity.ts
로그인 요청이 2번 왔을 때 row가 2개 와서 문제 원인 파악을 하다가 발견했다.
근본적인 원인은 react의 `index.ts` 파일에서 [`<StrictMode>`](https://ko.react.dev/reference/react/StrictMode)를 사용으로 인해 요청이 2번 보내지는 것이었다.
로그인 테스트 때에는 해당 부분을 주석 처리하고 진행했다.
https://www.notion.so/do0ori/users-entity-oauthId-field-unique-4aca90171a3d45be963f8d0f592fdfd4
- 예시
- [] 커밋 본문을 작성하셨나요?
- 예시
=> backend/DANG-257: Users entity에서 oauthId field에 누락된 unique 조건 추가

backend/src/auth/oauth/google.service.ts, backend/src/auth/oauth/kakao.service.ts, backend/src/auth/oauth/naver.service.ts, backend/src/auth/oauth/oauth.service.interface.ts
- url query string을 axios config의 params property를 이용해 가독성을 높였다.
- naver의 경우 모든 값들을 url query로 넣어서 요청을 보내야 한다.😒
- google의 경우 일부 api만 url query를 사용한다.
- kakao는 깔끔하게 url query를 사용하지 않는다.
- hard coding되어 있던 oauth api url을 환경변수에서 관리하도록 변경했다.
- 타입 정의를 해둔 interface 파일도 수정했다.
https://www.notion.so/do0ori/oauth-service-refactoring-5274d41cd73d4771bbc687854dfb55e6
- 예시
- 예시
=> backend/DANG-249: oauth service refactoring

backend/src/app.module.ts
모든 요청의 UnauthorizedException 에러 발생으로 Auth 모듈을 제거했습니다.
- https://www.notion.so/do0ori/Auth-22597e846bda4c9aac64d68541342059?pvs=4
- 예시
- 예시
=> backend/DANG-268: 전역에서 Auth 모듈 사용을 제거하기

backend/src/app.module.ts, backend/src/auth/guards/auth.guard.ts
주요 변경사항
- AuthModule를 전역으로 사용하고 metrics 정보만 허용 하도록 수정했습니다.
- 예시
- 예시
=> backend/DANG-269: Auth을 전역으로 사용하고 metrics url만 허용하기

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts
우리 서비스에 가입된 사용자가 아니라면 동의화면을 보여줘야 하므로 이를 확인하는 api가 필요하다. 인가 코드는 일회용이기 때문에 사용자 인지 확인한 후 로그인 때 재사용할 수가 없으므로 frontend에서 oauth access/refresh token까지 발급받기로 logic를 수정했다.
[회원 API 문서 참고](https://www.notion.so/do0ori/ac3c2402d85c4ac6a8160a232e825071?v=7a0568c6172c446cb41ea419db93e3c3)
https://www.notion.so/do0ori/is-member-api-login-logic-0655a8398c5e4006936d5b0d0fca6f64
- 예시
- 예시
=> backend/DANG-270: 우리 서비스에 가입된 사용자인지 확인하는 api 추가 및 login logic 수정

backend/src/auth/token/token.service.ts
- OAuth에서 발급해주는 access token의 수명을 조사해 본 결과 다음과 같다.
- Google: 1시간
- Kakao: 6시간
- Naver: 1시간
- OAuth access token도 만료되기 전에 갱신을 해주는 것이 좋기 때문에 우리 token을 갱신할 때 OAuth token도 갱신할 수 있도록 수명을 OAuth token의 최소 수명에 맞추기로 한다.
https://www.notion.so/do0ori/access-token-1-495b8ff4ab324b23bd96ec33800b8d86
- 예시
- 예시
=> backend/DANG-289: access token 수명을 12h에서 1h로 변경

.github/workflows/pr_labeler_validator.yaml
현재는 branch 이름 검사와 PR title 형식 검사가 PR이 열렸을 때 그리고 title이 수정되었을 때에만 trigger된다.
PR 본문을 수정했을 때 불필요한 검사가 실행되는 것을 방지할 수는 있지만 형식을 지키지 않았을 때에도 skip되는 문제가 있다.
이를 방지하기 위해 message를 보낼 때에만 조건을 넣어서 해결했다.
https://www.notion.so/do0ori/GitHub-Actions-labeler-and-validator-020875f9da2044bab42658612a885613
- 예시
- 예시
=> backend/DANG-245: test skip되는 문제 해결

.github/workflows/backend_deploy.yaml, .github/workflows/frontend_deploy.yaml
컨테이너 정리 명령 수정
- 이전에는 docker container prune -f 명령을 사용하여 실행 중이지 않는 컨테이너를 제거했습니다.
- 이번 커밋에서는 명령을 docker rm -fv 로 변경하여 정지된 컨테이너뿐만 아니라 볼륨 정보까지 제거하도록 했습니다. ECR 빌드/배포 스테이지 명칭 변경
- 이전 스테이지 명칭은 단순히 build 또는 deploy였습니다.
- 이번 커밋에서는 명확성을 위해 각 스테이지 이름을 ECR Build와 ECR Deploy로 변경했습니다.
- https://www.notion.so/do0ori/GitAction-Docker-Build-name-4454514143ad43158168920155d5e1ab?pvs=4
- 예시
- 예시
=> infra/DANG-292: 컨테이너 정리 명령 수정 및 ECR 빌드/배포 스테이지 명칭 변경

backend/src/auth/token/token.service.ts, backend/src/utils/ms.utils.spec.ts, backend/src/utils/ms.utils.ts
token 수명을 환경변수에 추가했다.
수명을 miliseconds로 변환하기 위해 utils에 vercel/ms 오픈소스에서 필요한 parse 함수만 가져와 수정해 추가했다.
https://www.notion.so/do0ori/token-944841d12a5c42ecbffd983d33ddbf25
- 예시
- 예시
=> backend/DANG-301: token 수명 하드 코딩 제거

.github/workflows/backend_deploy.yaml
컨테이너 포트 수정 이전에는 두 번째 백엔드 컨테이너의 포트가 3032였으나, 3031로 수정되었습니다.
두 컨테이너는 동일한 서비스를 제공하므로 동일한 포트를 사용해야 합니다.
- 예시
- 예시
=> infra/DANG-323: 백엔드 배포 워크플로우 서버 포트 동일하게 하게 하기

frontend/src/App.tsx, frontend/src/components/LoginAlertModal.tsx, frontend/src/components/LoginBottomSheet.tsx, frontend/src/components/LoginModal.tsx, frontend/src/components/Navbar.tsx, frontend/src/components/OAuthButton.tsx, frontend/src/index.tsx, frontend/src/pages/Home.tsx, frontend/src/pages/Join.tsx, frontend/src/pages/Profile.tsx, frontend/src/store/modalStateStore.ts
`LoginAlertModal`이 띄어 졌는지 , 회원가입중인지 상태를 알기 위해 zustands로 store 생성
1. `LoginAlertModal`의 회원가입/로그인 버튼 클릭시에 `setLoginBottomSheetState(true)`가 되어 `setLoginBottomSheetState`은 true가 되고,
`setLoginBottomSheetState == true?  `
1)`LoginBottomSheetState`가 화면 아래에서 위로 올라옴
2) `LoginAlertModal` 배경 어둡게, `LoginAlertModal` 페이지 section 없어짐
3) 뒷배경을 클릭하면 `isLoginBottomSheet` === false, 다시 LoginBottomSheet 내려감
2. oauth로그인 버튼 클릭후 '`/join`'페이지로 이동시 `navbar`와 `LoginBottomSheet`가 같이 보이는 일이 발생했기때문에
회원가입중인 상태(`isJoinning`)에 따라 navbar와 LoginBottomSheet 없앰
- 예시
- 예시
=> frontend/DANG-322: LoginBottomSheet 관련 로직 수정

.github/workflows/link_pr_to_ticket.yaml
PR 추가 시 notion api를 사용해 현재 branch에 적힌 Task ID에 해당하는 ticket에 PR url을 추가한다.
https://www.notion.so/do0ori/notion-api-PR-ticket-8cc696183111486ea4bd2765b487956b
개인 repo에서 테스트 완료
- 예시
- 예시
=> backend/DANG-230: GitHub Actions PR 생성 시 ticket에 PR url 추가 자동화

backend/src/common/interceptor/logging.interceptor.ts, backend/src/common/logger/winstonLogger.service.ts, backend/src/main.ts
- WinstonLoggerService에서 NODE_ENV를 productio으로 잘못 가져오고 있어 prod로 변경
- main.ts에서 콘솔 로그 찍던 거 winston 로거로 변경
- WinstonLoggerService 내부에서 찍던 로그는 제거해버림, 매번 내장 로거를 의존성으로 주입받는게 너무 불편함
- 예시
- 예시
=> backend/DANG-337: WinstonLoggerService에서 환경 변수 가져올때 production→prod로 변경

.github/workflows/change_ticket_status_done.yaml
PR merge 시 notion ticket의 status를 Done으로 업데이트한다.
https://www.notion.so/do0ori/PR-Notion-Status-Done-53fb296815d44f048d7634a028452381
- 예시
- 예시
=> infra/DANG-326: PR merge 시 Status를 Done으로 업데이트하도록 하는 GitHub Actions 추가

frontend/package-lock.json, frontend/package.json, frontend/src/components/common/Divider.tsx, frontend/src/components/common/Separator.tsx
구분선(Divider) 컴포넌트 구현
https://www.notion.so/do0ori/f730c7b9009b4275b9dcb5f0ad6d968f?pvs=4
- 예시
- 예시
=> frontend/DANG-333: 공통 컴포넌트에 구분선 추가

.github/workflows/backend_deploy.yaml, .github/workflows/frontend_deploy.yaml, backend/src/breed/breed.spec.ts, frontend/src/vitest.test.ts
주요 변경 사항
- 백엔드 배포 워크플로우에서 ENV_FILE_BACKEND 시크릿을 사용하여 .env.prod 파일을 생성하는 단계를 추가했습니다.
- 예시
- 예시
=> infra/DANG-348: 프론트엔드 및 백엔드 env.prod 분리하기

backend/src/dogs/dogs.service.ts
- 필요 산책량을 가져올 때 breedId가 아닌 dogId로 조회해 잘못된 값을 가져오는 버그가 있었습니다. breedId를 사용하도록 해 해결했습니다.
- 예시
- 예시
=> backend/DANG-347:  필요 산책량 잘못 가져오는 버그 수정

frontend/src/components/common/Button.tsx, frontend/src/components/common/Divider.tsx
공통 컴포넌트에서 import 방식 변경
https://www.notion.so/do0ori/import-7827c4854f3c405b9f87a0a8efbccfe4?pvs=4
- 예시
- 예시
=> frontend/DANG-349: 공통 컴포넌트에서 import 방식 변경

frontend/src/App.tsx, frontend/src/pages/Join.tsx
currentPage ‘/join’일때 Navbar, LoginBottomSheet 없애기
App.tsx에서 현재페이지 path를 감지해서 '/join'일때 fixed 상태인 Navbar와 LoginBottomSheet를 조건부로 렌더링하지 않게 만들었습니다.
추후 산책중 관련 페이지일때도 추가해야됩니다.
- 예시
- 예시
=> frontend/DANG-354: currentPage ‘/join’일때 Navbar, LoginBottomSheet 없애기

backend/src/common/database/abstract.repository.ts, backend/src/dogs/dogs.controller.ts, backend/src/dogs/dogs.service.ts, backend/src/users/users.service.ts
- 요청한 유저가 강아지의 소유자가 맞는지 확인합니다
- 맞다면, 요청한 강아지에 대한 프로필을 리턴합니다
- 강아지 프로필 만드는 로직에서, dogId가 배열일 경우와 아닐 경우를 합쳐서 한 메소드에서 구현하려고 했었는데, 그렇게 하면 statistics
API에서 dogId가 하나일 때도 빈 배열로 반환하는 경우를 포함하지 못해서, 배열일 경우와 아닐 경우를 따로 메소드로 분리했습니다
- 예시
- 예시
=> backend/DANG-351: 강아지 프로필 조회 API 구현

backend/src/common/database/database.module.ts
synchronize option은 매번 application을 실행할 때마다 database schema가 새롭게 생성되기 때문에 잘못하면 data가 사라질 수 있다. production에서는 이 option을 사용하지 말라고 option 설명에 나와있다.
```
(property) synchronize?: boolean | undefined
Indicates if database schema should be auto created on every application launch. Be careful with this option and don't use this in production - otherwise you can lose production data. This option is useful during debug and development. Alternative to it, you can use CLI and run schema:sync command.
Note that for MongoDB database it does not create schema, because MongoDB is schemaless. Instead, it syncs just by creating indices.
```
https://www.notion.so/do0ori/DB-module-synchronize-option-prod-false-68b7b02ddfe54a0ea738e24ff77f6fb5
- 예시
- 불필요한 메서드를 …
=> backend/DANG-335: DB module의 synchronize option을 prod일 때는 false가 되도록 수정

backend/src/auth/auth.controller.ts
`NODE_ENV`가 `'production'`인지 확인했었는데 `package.json` script를 보면 `'prod'`로 사용 중이어서 수정했다.
또한 `Boolean`을 직접 사용해 boolean 값을 return하기 보다는 가독성을 높이기 위해 삼항연산자를 사용했다.
https://www.notion.so/do0ori/NODE_ENV-production-prod-21c0b9be9a064c43a8f992ab489bbf1e
- 예시
- 예시
=> backend/DANG-360: NODE_ENV production에서 prod로 수정

frontend/package.json
- 프로덕션 빌드 시 FAST_REFRESH=false 대신 NODE_ENV=production을 사용하도록 수정함
- NODE_ENV=production 설정을 통해 React의 프로덕션 모드를 활성화하고, 개발 환경에서만 사용되는 개발 관련 코드와 기능을 제거할 수 있음
- 이를 통해 프로덕션 빌드 시 불필요한 코드가 포함되지 않아 번들 크기 감소와 성능 최적화가 가능해짐
- 예시
- 예시
=> infra/DANG-370: use NODE_ENV=production for production build

backend/src/auth/auth.service.ts, backend/src/common/database/abstract.repository.ts, backend/src/dogs/dogs.module.ts, backend/src/fixture/users.fixture.ts, backend/src/users-dogs/users-dogs.entity.ts, backend/src/users-dogs/users-dogs.module.ts, backend/src/users-dogs/users-dogs.repository.ts, backend/src/users-dogs/users-dogs.service.ts, backend/src/users/types/user-types.ts, backend/src/users/users.entity.ts, backend/src/users/users.module.ts, backend/src/users/users.repository.ts, backend/src/users/users.service.spec.ts, backend/src/users/users.service.ts
- abstract repository class 오타 수정 (fidnOne -> findOne)
- users service에서 repository를 직접 주입해 사용했던 user-dogs를 분리했다.
- users module이 abstract repository를 사용하도록 수정: abstract repository를 extends해 UsersRepository를 정의하고, UsersService에서 UsersRepository와 UsersDogsService를 의존성 주입해 class를 업데이트했다.
- 변경된 users 구조에 맞게 fixture와 test 코드(`users.service.spec.ts`) 수정
- 변경된 users service에 맞게 auth service 수정
- DogsModule에 추가된 불필요한 providers, exports 제거
https://www.notion.so/do0ori/Users-Repository-f10163438bed4fc9b289266d4d231bd6
`npm test`, `npm start` 성공
- 예시
- 예시
=> backend/DANG-356: Users module이 abstract Repository 사용하도록 변경

backend/src/main.ts, frontend/src/api/http.ts, frontend/src/utils/oauth.ts
백엔드 CORS 설정 확장
- backend/src/main.ts 파일에서 CORS 설정을 업데이트하여 프론트엔드 배포 도메인과 포트 (http://dangdang-walk.prgms-fullcycle.com:3000) 도 요청 허용하도록 변경했습니다.
프론트엔드 환경 변수 사용:
- 프론트엔드 코드에서 백엔드 API 베이스 URL (REACT_APP_NEST_BASE_URL)과 OAuth 클라이언트 ID (REACT_APP_GOOGLE_CLIENT_ID, REACT_APP_KAKAO_CLIENT_ID, REACT_APP_NAVER_CLIENT_ID) 를 가져오는 방식을 수정했습니다.
- 이전에는 process.env 객체를 직접 사용했습니다.
- 이번 커밋을 통해 앞서 설정된 window._ENV 객체를 사용하도록 변경되었습니다.
- 예시
- 예시
=> infra/DANG-401: 프론트엔드 백엔드 Auth 리다이렉트 CORS 허용

frontend/src/components/common/Checkbox2.tsx
공통 컴포넌트 Checkbox2에서 asChild 프롭 제거
https://www.notion.so/do0ori/Checkbox2-ee24ccd920884a639798d34269449a52?pvs=4
- 예시
- 예시
=> frontend/DANG-407: 공통 컴포넌트 Checkbox2 수정

backend/src/breed/breed.service.ts, backend/src/daily-walk-time/daily-walk-time.entity.ts, backend/src/daily-walk-time/daily-walk-time.service.ts, backend/src/dog-walk-day/dog-walk-day.service.ts, backend/src/dogs/dogs.controller.ts, backend/src/dogs/dogs.entity.ts, backend/src/dogs/dogs.module.ts, backend/src/dogs/dogs.service.ts, backend/src/dogs/dto/dog.dto.ts, backend/src/excrements/excrements.entity.ts, backend/src/journals/journals-dogs.entity.ts
- `Dogs` entity
- walkDay 및 dailyWalkTime field에 cascade 및 onDelete 설정 추가
- isWalking field에 default 값 false 추가
- `DailyWalkTime` entity
- duration field에 default 값 0 추가
- `JournalsDogs`와 `Excrements`에서 dog가 삭제되면 해당 dogId를 가진 row는 모두 삭제되어야 하므로 `onDelete: 'CASCADE'` option 추가
- `onDelete: 'CASCADE'` option이 적용된 row는 부모 table에서 참조하는 row가 삭제되면 해당 row도 삭제된다.
- UsersDogs table에는 onDelete option이 없기 때문에 직접 삭제해주었고,
`DogWalkDay`와 `DailyWalkTime`에 있는 row를 삭제해주면 Dogs에 있는 강아지 정보는 onDelete option에 의해 자동 삭제된다.
- Dogs에 있는 강아지 정보가 삭제되었으므로 dogId를 외래키로 가지고 있으면서 onDelete option을 설정해두었던 `Excrements`와 `JournalsDogs`에 있는 row 또한 자동 삭제된다.
https://www.notion.so/do0ori/api-2b8963c1773d4cbb8ac4e926f82437f6
DB로 manual하게 동작 테스트 완료. 추후 테스트 코드 작성이 필요해 보임.
- 예시
- 불필요한 …
=> backend/DANG-355: 강아지 등록, 삭제, 정보 수정 api 추가

backend/src/dogs/dogs.controller.ts, backend/src/dogs/guards/authDog.guard.ts
authorize dog guard를 만들어 중복 코드를 줄였다.
https://www.notion.so/do0ori/authorizeDog-guard-4a1438de32ea48a0b22f5361ad72d5e9
- 예시
- 예시
=> backend/DANG-415: 사용자가 주인이 아닌 강아지에 대한 요청을 거르는 guard 추가

backend/src/dogs/dogs.controller.ts, backend/src/dogs/dogs.service.ts, backend/src/users-dogs/users-dogs.entity.ts
Dogs의 row가 삭제될 때 UsersDogs의 row도 자동으로 삭제되도록 option을 추가
https://www.notion.so/do0ori/UsersDogs-dogId-onDelete-f88f9c7f47054cc090d12a1a834486b9
- 예시
- 예시
=> backend/DANG-433: UsersDogs dogId에 onDelete 추가

backend/src/dogs/dogs.entity.ts, backend/src/dogs/dto/dog.dto.ts
강아지 등록 시 강아지의 생일을 모를 수도 있기 때문에 null 값을 허용했다.
default는 null이다.
https://www.notion.so/do0ori/Dogs-birth-nullable-default-null-130947f10c754caca56834bdce862446
- 예시
- 예시
=> backend/DANG-436: Dogs birth field에 null option 추가

backend/src/dogs/dogs.entity.ts, backend/src/dogs/dto/dog.dto.ts
`@Column()` decorator에 type option(`type: 'timestamp'`)을 추가했다. ([참고자료](https://stackoverflow.com/a/74956084))
이제 date type의 birth column에 null을 넣을 수 있다.
https://www.notion.so/do0ori/Dogs-birth-error-cb0d0a6b56a24d269b0148b4c6bf5c90
- 예시
- 예시
=> backend/DANG-441: Dogs birth column error 해결

backend/src/dogs/dogs.controller.ts
GET 요청에 대한 handler 순서의 문제였다.
getOneProfile handler는 `'/:id'` 형태로 endpoint를 받고 AuthDogGuard를 사용하는데 getAvailableDogs와 getDogsStatistics handler가 그 뒤에 위치하게 되면서 routing 시 `'/:id'`에 먼저 match가 되어 버린다.
즉 id 값이 statistics와 walk-available로 간주되는 것이다.
따라서 간단히 getOneProfile handler의 위치를 마지막으로 옮겨 해결했다.
https://www.notion.so/do0ori/dogs-controller-AuthDogGuard-endpoint-AuthDogGuard-ed4d23ba430544da98ce1974c86b83b1
https://www.notion.so/do0ori/Guard-endpoint-bc3e7599e6314d5292a31d06622db833
- 예시
- 예시
=> backend/DANG-452: dogs controller에서 AuthDogGuard를 적용하지 않은 endpoint에도 AuthDogGuard가 적용되는 문제 해결하기

frontend/src/components/walk/Map.tsx, frontend/src/typed/window.d.ts
- 카카오맵 스크립트 로드 방식을 변경하였습니다. 이전에는 window.kakao 객체를 글로벌로 사용하였지만, 이번 변경으로 스크립트 로드 후 이벤트 리스너를 통해 지도를 초기화하도록 변경되었습니다.
- 환경 변수 REACT_APP_KAKAO_MAP_ID를 window._ENV 객체에서 가져오도록 변경하였습니다. 기존에는 process.env에서 직접 가져왔습니다.
- window.kakao 타입을 window.d.ts 파일에 정의하였습니다. 이전에는 Map.tsx 파일 내부에 선언되어 있었습니다.
- 예시
- 예시
=> frontend/DANG-456: kakao Map 로드 방식 변경 및 타입 정의

frontend/src/api/auth.ts, frontend/src/components/OAuthButton.tsx, frontend/src/constants/keys.ts, frontend/src/hooks/useAuth.ts, frontend/src/index.tsx, frontend/src/models/dog.model.ts, frontend/src/pages/Home.tsx, frontend/src/pages/Join.tsx, frontend/src/pages/JoinStep/DogRegister2.tsx, frontend/src/pages/OauthCallback.tsx, frontend/src/pages/Profile.tsx, frontend/src/store/authStore.ts, frontend/src/types/common.ts, frontend/src/utils/cookie.ts, frontend/src/utils/oauth.ts
기존 로그인 상태를 관리를 getAccessToken api의 성공여부로 관리를 했지만,
chrome caching(back/forward) 관련 이슈때문에 cookie 상태로 로그인 상태를 관리하는 것으로 리펙토링
참고 https://blog.hoseung.me/2020-10-31-chrome-back-forward-cache
- 예시
- 예시
=> frontend/DANG-469: 로그인 상태 관리 관련 로직 리펙토링

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.spec.ts, backend/src/auth/auth.service.ts
OAuth App마다 등록 가능한 redirectURI 개수에 제한이 있는터라 그냥 origin + /callback으로 redirectURI를 고정하기로 했다.
https://www.notion.so/do0ori/redirectUri-origin-callback-1b3a59e2cd0b4f72986c79fdd8ea6d64
- 예시
- 예시
=> backend/DANG-470: 회원가입, 로그인 API의 Body 값에서 redirectURI를 삭제하고 origin + /callback 고정값 사용

backend/src/app.module.ts, backend/src/journals-dogs/journals-dogs.entity.ts, backend/src/journals-dogs/journals-dogs.module.ts, backend/src/journals-dogs/journals-dogs.repository.ts, backend/src/journals-dogs/journals-dogs.service.ts, backend/src/journals/dto/journals-detail.dto.ts, backend/src/journals/journals.controller.ts, backend/src/journals/journals.module.ts, backend/src/journals/journals.repository.ts, backend/src/journals/journals.service.ts, backend/src/utils/manipulate.util.ts, backend/src/walk-log-photos/walk-log-photos.module.ts, backend/src/walk-log-photos/walk-log-photos.service.ts
- 산책일지 상세 API를 구현했습니다 
- util 함수인 makeSubObjectsArray와 makeSubObject 함수와 DTO의 getKey() 함수를 조합해 각 테이블에서 필요한 컬럼을 손으로 하드코딩 하지 않고 DTO에 정의해둔 대로 가져올 수 있도록 구조를 만들었습니다
추가 작업이 필요한 부분
- 컬럼명 변경. Dog엔티티까지 수정해야 할 부분이 있어서 여기서 안하고 따로 티켓 만들어서 같이 할 예정
- DTO의 getKey 함수는 하드코딩 되어있기에 이를 reflect-metadata 와 같은 라이브러리를 사용해서 하드코딩된 부분 없앨 수 있는지 찾아보기
- checkDogExistsInJournal의 예외가 제대로 처리되지 않고 있음 (예외를 throw했을 때 컨트롤러 -> 프론트로 전달되는 게 아니라 콘솔에 찍히고 프로그램이 종료되어버림), nest의 예외에 대해 찾아보고 고쳐야 할 것 같음
- 예시
- 예시
=> backend/DANG-357: 산책일지 상세 API 구현

backend/src/auth/auth.controller.ts, backend/src/auth/interceptors/cookie.interceptor.ts
- accessToken 만료 시간을 seconds에서 miliseconds 단위로 변경했다. (Tanstack query(React query)에서 miliseconds 단위를 사용한다고 한다.)
- 크롬 브라우저에서 cache를 복구하는 기능 때문에 isLoggedIn 정보가 제대로 동작하지 않는 경우가 있어, server에서 cookie로 세션을 관리하기로 했다. client는 cookie에서 isLoggedIn을 꺼내 전역에서 로그인 상태를 관리한다.
- 중복되는 set/clear cookie 응답을 custom cookie interceptor를 만들어 처리했다.
https://www.notion.so/do0ori/cookie-isLoggedIn-true-expiresIn-number-ms-5428fa48f5bd4bbb83ac4c088ff23d85
`CookieInterceptor` 이름 추천 받습니다.🤗
- 예시
- 예시
=> backend/DANG-471: session 관리를 위해 cookie에 isLoggedIn, expiresIn field 추가

backend/src/auth/auth.service.ts
네이버 로그아웃 후 재로그인 시 동의화면이 뜨는 현상이 발생한다.
네이버는 따로 로그아웃이나 회원탈퇴(연동해제)를 지원하는 API가 존재하지 않는다.
그래서 token 만료 요청을 사용했었는데 매 로그인마다 동의화면이 뜨는 관계로 로그아웃 시에는 요청을 보내지 않고 회원탈퇴 때에만 요청을 보내는 것으로 수정하였다.
로그아웃에 대해 정확히 찾아보니 다음과 같다.
- [Naver](https://developers.naver.com/docs/login/api/api.md#3-2--%EC%A0%91%EA%B7%BC-%ED%86%A0%ED%81%B0-%EB%B0%9C%EA%B8%89%EA%B0%B1%EC%8B%A0%EC%82%AD%EC%A0%9C-%EC%9A%94%EC%B2%AD)는 따로 로그아웃 api가 없다. 다음과 같은 방법이 존재한다.
1. [http://nid.naver.com/nidlogin.logout으로](http://nid.naver.com/nidlogin.logout%EC%9C%BC%EB%A1%9C) 보내기
2. [재인증 API](https://developers.naver.com/docs/login/devguide/devguide.md#5-2-%EC%9E%AC%EC%9D%B8%EC%A6%9D)(기존 로그인 요청 URL에 `auth_type=reauthenticate` query 추가): 간편 로그인 사용 불가능
3. 토큰 만료 (회원탈퇴/연동해제 요청과 동일하게 처리): 이 경우 재로그인 시 동의화면이 뜸
여기서 우리는 원래 3번 방법을 사용했으나 1번이나 2번을 사용해야 하지 않을까 싶다. …
=> backend/DANG-479: naver 로그아웃 시 token 만료 요청 사용하지 않기

frontend/src/components/icon/Feces.tsx, frontend/src/components/icon/Urine.tsx
대소변 컴포넌트의 color 프롭을 선택 사항으로 변경
https://www.notion.so/do0ori/color-a27cd52a071645c99451fec64c2c581c?pvs=4
- 예시
- 예시
=> frontend/DANG-476: 대소변 컴포넌트의 color 프롭을 선택 사항으로 변경

backend/src/auth/auth.service.ts
naver와 마찬가지로 로그아웃 후 재로그인 시 동의화면이 뜨는 현상이 발생한다.
google도 따로 로그아웃 API가 없어서 token 만료 요청을 사용했는데 매 로그인마다 동의화면이 뜨는 관계로 로그아웃 시에는 요청을 보내지 않는 것으로 수정한다.
https://www.notion.so/do0ori/4de1d75169024bcaa6cd3989cd466e93
- [x ] PR 올리기 전 **rebase** 동기화를 하셨나요?
- 예시
- 예시
=> backend/DANG-485: google 로그아웃 시 token 만료 요청 사용하지 않기

backend/src/excrements/excrements.entity.ts, backend/src/excrements/excrements.service.ts, backend/src/journal-photos/journal-photos.service.ts, backend/src/journals-dogs/journals-dogs.entity.ts, backend/src/journals-dogs/journals-dogs.service.ts, backend/src/journals/dto/journals-create.dto.ts, backend/src/journals/journals.controller.ts, backend/src/journals/journals.entity.ts, backend/src/journals/journals.service.ts, backend/src/journals/types/journal-types.ts
산책일지 생성 API를 구현했습니다.
구현 과정에서 excrements의 type도 컴포지트 키에 포함하도록 변경했습니다.
이전에는 journalId, dogId만 pk로 되어있어, 같은 journalId와 dogId를 가지고 있으면 type이 달라도 중복 검사에 걸렸습니다. 
- 예시
- 예시
=> backend/DANG-486: 산책일지 생성 API 구현

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.spec.ts, backend/src/auth/auth.service.ts, backend/src/auth/decorators/oauthData.decorator.ts, backend/src/auth/guards/oauthData.guard.ts, backend/src/auth/interceptors/cookie.interceptor.ts
- 로그인 시 회원이 아닌 경우 oauth 관련 cookie를 생성하고, 회원가입 시 cookie에 담긴 oauth 정보를 사용한 후 해당 cookie는 삭제한다.
- oauth 관련 cookie가 존재하는지 검증하고 `request.oauthData` property에 cookie 정보들을 객체로 담는 `OauthDataGuard `추가
- 회원가입 api에서 `request.oauthData` 객체를 쉽게 가져오기 위해 `OauthCookies` decorator 추가
- 바뀐 로그인/회원가입 flow에 맞게 auth controller, service 및 test code 업데이트
https://www.notion.so/do0ori/oauth-cookie-api-cookie-oauth-cookie-api-2dcf262f5fe24046815e5069ebce8993
- 예시
- 예시
=> backend/DANG-488: 변경된 로그인/회원가입 flow에 맞게 auth 코드 수정

backend/src/dogs/dogs.controller.ts, backend/src/dogs/dogs.service.ts
usersService logic을 dogsService로 옮겼다.
dogsService의 makeProfileList method에 안나(@opehn)님이 만든 util 함수를 적용했다.
https://www.notion.so/do0ori/dogs-controller-usersService-DI-5924c8b0004849b181528bf8458d6d3f
- 예시
- 예시
=> backend/DANG-501: dogs controller에서 usersService DI 제거

backend/src/auth/interceptors/cookie.interceptor.ts
client에서 접근 가능하도록 httpOnly 속성을 제거했다.
https://www.notion.so/do0ori/isLoggedIn-expiresIn-cookie-httpOnly-683166012042468494864763a7ec9bdc
- 예시
- 예시
=> backend/DANG-532: isLoggedIn 및 expiresIn cookie에서 httpOnly 속성 제거

backend/src/excrements/excrements.entity.ts, backend/src/journal-photos/journal-photos.entity.ts, backend/src/journals-dogs/journals-dogs.entity.ts, backend/src/journals/dto/journal-update.dto.ts, backend/src/journals/journals.controller.ts, backend/src/journals/journals.service.ts
산책일지 수정, 삭제 API를 구현했습니다.
삭제시 CASCADE 옵션을 추가해 자동으로 삭제되도록 구현했습니다.
추가적으로 필요한 작업
update 시 트랜잭션 처리가 필요한 것 같습니다.
create의 경우에도 마찬가지라 트랜잭션에 대해 조사 후 일괄적으로 적용이 필요해보임
- 예시
- 예시
=> backend/DANG-511: 산책일지 수정, 삭제 API 구현

backend/src/auth/interceptors/cookie.interceptor.ts
cookie interceptor에서 `Cannot use 'in' operator to search for 'accessToken' in undefined` 에러가 발생했다.
data가 먼저 존재하는지 확인하도록 수정하고 early return을 사용해 해결했다.
https://www.notion.so/do0ori/Cannot-use-in-operator-to-search-for-accessToken-in-undefined-02822655de5f4ff69ba41e8aaf575d14
- 예시
- 예시
=> backend/DANG-536: 로그아웃 에러 해결하기

backend/src/common/interceptors/logging.interceptor.ts, backend/src/common/logger/winstonLogger.service.ts, backend/src/utils/ansi.utils.ts
- log message format 변경
- ansi code를 이용해 log message에 색상 적용
- userId와 oauthId 앞에 prefix를 붙여 구분
https://www.notion.so/do0ori/Log-format-1c3530dcee944d9ab5929e41981675d8
- 예시
- 예시
=> backend/DANG-434: Log format 가독성 높이기

backend/src/auth/interceptors/cookie.interceptor.ts
client hosting을 vercel로 변경하면서 client와 server의 origin이 달라져 발생한 문제였다.
local 환경
- `sameSite: 'lax'`
- `secure: false`
prod 환경
- `sameSite: 'none'`
- `secure: true`
https://www.notion.so/do0ori/cookie-37f22e8ef5634b7586a3298f52f8ad5a
- 예시
- 예시
=> backend/DANG-551: 배포 환경(cross-site)에 맞게 cookie option 설정

backend/src/dogs/dogs.controller.ts, backend/src/journals/journals.controller.ts
id params가 숫자만 받을수 있도록 정규식으로 제한을 걸었습니다. 
https://velog.io/@unogle/URL-%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0-GET-POST 참고
- 예시
- 예시
=> backend/DANG-556: id 파라미터가 숫자만 받을 수 있도록 제한

backend/src/auth/guards/oauthData.guard.ts, backend/src/auth/guards/refreshToken.guard.ts, backend/src/auth/interceptors/cookie.interceptor.ts, backend/src/daily-walk-time/daily-walk-time.module.ts, backend/src/daily-walk-time/daily-walk-time.service.ts, backend/src/dogs/dogs.service.ts, backend/src/dogs/guards/authDog.guard.ts, backend/src/journals/journals.controller.ts, backend/src/journals/journals.service.ts
에러 로그 추가
한글이 한글자당 바이트가 더 많이 들어갔던 것 같아서 영어로 바꿨습니다
필요한 추가 작업 
1.
abstract repository에서 던지는 에러 로그를 메소드별로 구분하기 위해
error의 stack에서 메소드 명을 추출해서 repository에 인자로 넣어줘야 할 것 같은데
Nest의 디폴트 에러에는 에러 스택이 없다고 함
Custom 에러를 정의하고 error 스택을 가져오게 한 뒤에, 메소드를 추출해서 repository에 인자로 넘겨주어 
해당 에러가 어떤 메소드에서 난 에러인지 구분하는 작업이 필요해보임
- 예시
- 예시
=> backend/DANG-557: 에러 로깅 전체적으로 추가

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/auth/guards/auth.guard.ts, backend/src/auth/guards/oauthData.guard.ts, backend/src/auth/guards/refreshToken.guard.ts, backend/src/auth/interceptors/cookie.interceptor.ts, backend/src/common/database/abstract.repository.ts, backend/src/daily-walk-time/daily-walk-time.service.ts, backend/src/dogs/dogs.controller.ts, backend/src/dogs/dogs.service.ts, backend/src/dogs/dogs.spec.ts, backend/src/dogs/guards/authDog.guard.ts, backend/src/journals/dto/journals-create.dto.ts, backend/src/journals/dto/journals-detail.dto.ts, backend/src/journals/journals.spec.ts
- error 메시지를 구체적으로 작성
- 변수명은 `e`가 아니라 `error`로 명확히 작성
- 일반 log나 debug message 형식 통일
- `OauthDataGuard`에서 어떤 cookie 값이 빠졌는지 구체적인 message 생성
- `AuthGuard` 및 `RefreshTokenGuard`에서 TokenExpiredError, JsonWebTokenError 처리 코드 추가
https://www.notion.so/do0ori/error-format-log-cec47774c4fe41d1a65f8b0a6425f207
global한 error 처리, custom error class 필요
- 예시
- 예시
=> backend/DANG-560: error 메시지 구체화, format 통일, 불필요한 log 제거

backend/src/auth/interceptors/cookie.interceptor.ts
cookie의 domain 설정은 보안상의 이유로 host url로만 설정 가능하다. 때문에 우리는 배포환경이 cross-site인데 이 경우 domain을 client url로 설정이 불가능해 일단 삭제했다. client에서 test를 위해 body에 isLoggedIn과 expiresIn을 추가했다.
- 예시
- 예시
=> backend/DANG-574: cookie domain 속성 삭제, body에 isLoggedIn, expiresIn 추가

frontend/src/pages/Journals/CreateForm.tsx
산책기록 저장 페이지의 저장 취소 로직 구현
https://www.notion.so/do0ori/59c75e69c2e944a28349d0d3a0eb3e44?pvs=4
- 예시
- 예시
=> frontend/DANG-565: 산책기록 저장 페이지의 저장 취소 로직 구현

backend/src/auth/interceptors/cookie.interceptor.ts, backend/src/main.ts
- cors options들 중 `string` 형식을 `string[]` 형식으로 변경
- client에서 뒤로가기할 경우 bfcache가 로딩되어 로그인 상태 관리에 어려움이 있었는데 해당 event가 발생할 때 브라우저를 새로고침함으로써 이 문제를 해결해서 더 이상 server에서 `isLoggedIn`을 보내줄 필요가 없어졌다. `expiresIn` 또한 어차피 고정이기 때문에 보내주지 않는다.
- 예시
- 예시
=> backend/DANG-584: isLoggedIn, expiresIn 삭제

backend/src/auth/oauth/google.service.ts, backend/src/auth/oauth/kakao.service.ts, backend/src/auth/oauth/naver.service.ts
axios error의 `response.data`도 출력하도록 했다.
- 예시
- 예시
=> backend/DANG-589: oauth service에서 axios error 처리 개선

backend/src/breed/breed.controller.ts, backend/src/dogs/dogs.controller.ts, backend/src/dogs/dogs.entity.ts, backend/src/dogs/dogs.service.ts, backend/src/dogs/pipes/dateValidation.pipe.ts
- data query string을 위한 validation pipe 추가
- `YYYY-MM-DD` 형식인지
- month와 day의 숫자가 유효한지
- 현재 또는 과거의 날짜인지
- dogs controller에 `param.id`에는 `ParseIntPipe`를, `query.date`에는 앞서 정의한 custom `DateValidationPipe`를 사용한다.
- delete api refactoring
- dogs entity에서 breed의 option을 `eager: true`로 설정하여 dog data를 가져올 때 breedId에 해당하는 Breed 정보도 가져오도록 했다.
https://www.notion.so/do0ori/API-1-c921013ff2a94552b932d3b41d144bd8
- 예시
- 예시
=> backend/DANG-601: 월별 강아지 산책 조회 API 1차

.github/workflows/link_pr_to_ticket.yaml
`check_error`라는 함수에서 "error"라는 단어가 응답에 존재하면 exit 1을 하게 되는데 찾은 페이지에서 "error"라는 단어를 제목이나 본문에서 사용하고 있으면 이 조건을 충족해 exit 1이 되어버려 script가 중단되는 것이었다. error message에 대해 처리를 하려고 만든 함수였지만 의도치 않은 현상이 생겨 삭제했다.
https://www.notion.so/do0ori/link-pr-to-notion-script-page-patch-api-0cee86ee743a4074bc2440bf6a18dbeb
- 예시
- 예시
=> infra/DANG-611: "error"라는 단어가 포함된 페이지에서 script가 중단되는 현상 해결

backend/src/dogs/dogs.entity.ts
aws s3에 업로드한 이미지 url이 varchar의 최대 범위인 65,532 byte를 넘어가는 관계로 text type으로 변경한다.
https://www.notion.so/do0ori/Dogs-profilePhotoUrl-type-varchar-text-07b585762b0540ccb025c7f3cf294968
- 예시
- 예시
=> backend/DANG-645: Dogs.profilePhotoUrl의 type을 varchar에서 text로 수정

backend/src/breed/breed.service.ts, backend/src/common/database/abstract.repository.ts, backend/src/daily-walk-time/daily-walk-time.service.ts, backend/src/dog-walk-day/dog-walk-day.service.ts, backend/src/dogs/dogs.service.ts, backend/src/excrements/excrements.service.ts, backend/src/journal-photos/journal-photos.service.ts, backend/src/journals-dogs/journals-dogs.service.ts, backend/src/journals/journals.service.ts, backend/src/users-dogs/users-dogs.service.ts, backend/src/users/users.service.ts
- 추상 리포지토리 find 함수를 typeorm의 find 함수 쓰도록 변경
- 인자 타입을 findMayOptions 로 변경해 더 많은 옵션을 넣을 수 있도록 변경
- 예시
- 예시
=> backend/DANG-652:  추상 리포지토리 find 함수를 typeorm의 find 함수 쓰도록 변경, 인자 타입 findManyOptions로 변경

frontend/src/components/journals/DogImages.tsx, frontend/src/pages/Journals/CreateForm.tsx
산책일지 저장 페이지에서 상태에 저장된 경로를 이용해 이미지를 표시
https://www.notion.so/do0ori/2ed3234462f2443f92e700145a4f88ce?pvs=4
- 예시
- 예시
=> frontend/DANG-651: 산책일지 저장 페이지에서 상태에 저장된 경로를 이용해 이미지를 표시

frontend/src/pages/Journals/CreateForm.tsx
산책일지 저장 페이지에서 저장 로직 구현
https://www.notion.so/do0ori/7d93b9d30d574ed18ce59b341b2d7217?pvs=4
- 예시
- 예시
=> frontend/DANG-659: 산책일지 저장 페이지에서 저장 로직 구현

frontend/src/components/journals/Heading.tsx, frontend/src/pages/Journals/CreateForm.tsx
산책일지 저장 페이지를 위한 Heading 컴포넌트
https://www.notion.so/do0ori/Heading-f38735f6ea6f42d08b9f968cc4892503?pvs=4
- 예시
- 예시
=> frontend/DANG-667: 산책일지 저장 페이지를 위한 Heading 컴포넌트

backend/src/journals-dogs/journals-dogs.service.ts
- 최근 산책일지를 찾는 로직에서, 산책일지가 없을 때를 !result로 체크했는데, 산책일지가 없어도 빈 배열을 리턴해서 체크를 통과해버려서 빈 배열 안에 있는 joruanlId에 접근해서 생긴 문제.
- 체크 로직을 !result.length로 변경해서 해결했다
- 예시
- 예시
=> backend/DANG-677: journalId를 찾을 수 없다는 버그 수정

backend/src/dogs/dogs.entity.ts, backend/src/journals/dto/journal-update.dto.ts, backend/src/journals/dto/journals-create.dto.ts, backend/src/journals/dto/journals-detail.dto.ts, backend/src/journals/journals.entity.ts
1. journals에서 title 삭제
- 사용자가 제목 입력하는 기능이 없다고 해서 삭제했습니다
2. dogs에서 profile_photo_url 컬럼 타입을 text->varchar로 복귀
- presigned URL을 저장하는걸로 잘못 해석해서 길이가 초과됐었는데, presigned URL이 아니라 저장된 파일의 경로를 저장하는거라 varchar로도 충분합니다
- 예시
- 예시
=> backend/DANG-678: journals에서 title 삭제, dogs의 profile_photo_url 타입 text->varchar로 복귀

backend/src/dogs/dogs.service.ts
현재 `Dogs.breed` column에 option으로 `eager: true`가 설정되어 있기 때문에 Dogs entity를 가져올 때 breedId에 해당하는 Breed entity도 함께 가져오게 된다. 그래서 따로 breedId에 해당하는 Breed 객체를 찾지 않아도 된다.
https://www.notion.so/do0ori/getProfile-method-eager-option-f629ea7d253e4fbea0b093b8b35eaf43
- 예시
- 예시
=> backend/DANG-699: getProfile method에서 breed field의 koreanName을 사용하도록 수정

backend/src/dogs/dogs.controller.ts, backend/src/dogs/dogs.service.ts
`UserDogs`에서 사용자가 소유한 모든 강아지의 id를 가져오고 순회하며 profile을 작성할 수도 있지만 비효율적인 것 같아 `QueryBuilder`로 해결했다. 보내줄 field는 확정은 아니라서 일단 강아지 프로필 조회 API와 동일하게 보낸다.
생일 timezone도 아직 처리가 안되어 있다.
https://www.notion.so/do0ori/API-c5160d28653449cf8e2b363e2de2390a
- 예시
- 예시
=> backend/DANG-688: 사용자가 소유한 모든 강아지의 profile을 가져오는 API 추가

frontend/src/components/journals/DogImages.tsx, frontend/src/utils/url.ts
산책일지 저장 페이지에서 잘못된 사진 Url
https://www.notion.so/do0ori/Url-69f696f21dc94d5695088a555a1e603f?pvs=4
- 예시
- 예시
=> frontend/DANG-703: 산책일지 저장 페이지에서 잘못된 사진 Url

backend/src/auth/auth.controller.ts, backend/src/auth/auth.module.ts, backend/src/auth/auth.service.spec.ts, backend/src/auth/auth.service.ts, backend/src/journals/journals.entity.ts, backend/src/users-dogs/users-dogs.entity.ts
- `UsersDogs` 및 `Journals`의 userId FK에 `onDelete: 'CASCADE'` 추가
- Table들의 연관관계가 업데이트되면서 단순히 userId에 해당하는 user를 삭제할 수 없게 되었다. (FK Constraints Error 발생)
연관된 row들까지 삭제하는 순서는 다음과 같다.
1. UsersDogs에서 사용자가 소유하고 있는 강아지의 id를 모두 찾아 해당 강아지들을 삭제
2. Users에서 사용자 삭제
`onDelete: 'CASCADE'` option에 의해 연관된 나머지 row들은 자동으로 삭제된다.
https://www.notion.so/do0ori/row-c7fd34272af549cb93a015cfa9dd016f
- 예시
- 예시
=> backend/DANG-695: 회원탈퇴(삭제)시 연관된 row들까지 삭제하도록 업데이트

frontend/src/components/journals/DogImages.tsx
산책일지 저장 페이지에서 잘못된 산책 사진 CSS
https://www.notion.so/do0ori/CSS-d13ed84eba8e4d6393aecf66efccd323?pvs=4
- 예시
- 예시
=> frontend/DANG-706: 산책일지 저장 페이지에서 잘못된 산책 사진 CSS

frontend/src/components/common/Checkbox2.tsx
Checkbox2 컴포넌트에서 함수의 이름 변경
https://www.notion.so/do0ori/84da6a9ecbc1491a908a59854e486631?pvs=4
- 예시
- 예시
=> frontend/DANG-458: Checkbox2 컴포넌트에서 함수의 이름 변경

backend/src/auth/token/token.service.ts
oauthId는 string이라 number로 type casting을 해줄 필요가 없는데 실수로 추가했다.
따라서 다시 삭제.
- 예시
- 예시
=> backend/DANG-715: oauthId를 number로 type casting하는 code 삭제

frontend/src/pages/Journals/CreateForm.tsx, frontend/src/utils/url.ts
산책일지 저장 페이지가 받는 history.state에 대한 데이터 가공
https://www.notion.so/do0ori/history-state-f035ecbb81584665b88c1fab5d828018?pvs=4
- 예시
- 예시
=> frontend/DANG-717: 산책일지 저장 페이지가 받는 history.state에 대한 데이터 가공

backend/src/common/database/database.module.ts, backend/src/common/database/seeds/breed.seeder.ts
- `DatabaseModule`에는 `WinstonLoggerService` 주입
- `BreedSeeder`는 주입이 안되는 관계로 직접 instance를 생성해 사용
https://www.notion.so/do0ori/seeding-console-log-winstonLogger-841f565105af45cbb3255f5e1aac1b09
- 예시
- 예시
=> backend/DANG-693: seeding 시 console.log를 winstonLogger로 대체하기

backend/src/journals/journals.service.ts
월 길이 만큼 보내야 하는데 잘못 추가했다.
https://www.notion.so/do0ori/API-6095a036d21240a1a916e04dfe344f8d
- 예시
- 예시
=> backend/DANG-723: journals가 빈 배열일 때 journalCntAMonth 빈 배열 보내는 코드 삭제

backend/src/common/database/abstract.repository.ts, backend/src/dogs/dogs.service.ts, backend/src/journals-dogs/journals-dogs.service.ts, backend/src/journals/dto/journal-list.dto.ts, backend/src/journals/journals.controller.ts, backend/src/journals/journals.service.ts, backend/src/utils/manipulate.util.ts
산책 목록 API를 구현했습니다.
- makeSubObjectArray 함수의 Attributes 인자를 targetAttributes, srcAttributes로 분리했습니다.
만들 대상이 되는 배열과, 재료(?)배열의 속성명이 다를 수 있어 바꾸었습니다.
- 예시
- 예시
=> backend/DANG-722: 산책 목록 API 구현

backend/src/journals/dto/journals-create.dto.ts, backend/src/journals/journals.entity.ts, backend/src/journals/journals.service.ts, backend/src/journals/types/journal-types.ts
- Journals 엔티티  routeImageUrl -> routes로 변경했습니다
- 산책일지 생성시 이미지 url 대신 routes 경로 데이터를 저장하도록 변경했습니다
- 예시
- 예시
=> backend/DANG-733: Journals 엔티티에 routeImageUrl -> routes로 변경, 산책일지 생성시 routes 경로 저장

backend/src/auth/auth.service.spec.ts, backend/src/auth/auth.service.ts, backend/src/auth/guards/oauthData.guard.ts, backend/src/auth/interceptors/cookie.interceptor.ts, backend/src/auth/oauth/google.service.ts, backend/src/auth/oauth/kakao.service.ts, backend/src/auth/oauth/naver.service.ts, backend/src/auth/oauth/oauth.service.interface.ts, backend/src/users/dto/createUser.dto.ts, backend/src/users/users.controller.ts, backend/src/users/users.entity.ts, backend/src/users/users.module.ts, backend/src/users/users.service.ts, frontend/src/utils/oauth.ts
- Users table에 email, profileImage column 추가
- 회원가입 시 다시 oauthAccesToken으로 userInfo를 요청하기 때문에 oauthId를 cookie에 저장할 필요가 없어서 삭제
- google 인가 코드 요청 url에 userinfo.profile scope 추가
https://www.notion.so/do0ori/API-d824f5bb23b14f0e94d6a8417fd02efe
- 예시
- 예시
=> backend/DANG-728: 회원 정보 조회 API 구현

backend/src/dogs/dogs.module.ts, backend/src/dogs/dogs.service.ts, backend/src/users/dto/updateUser.dto.ts, backend/src/users/users.controller.ts, backend/src/users/users.module.ts, backend/src/users/users.service.spec.ts, backend/src/users/users.service.ts
- 회원 정보 수정 API는 nickname과 profileImage를 받음 (nickname은 # 앞부분에 해당하는 문자열)
- profileImage update 시 기존 profileImage는 S3에서 삭제
https://www.notion.so/do0ori/API-6861b6db6be94df091a9f178818c2cf0
- 예시
- 예시
=> backend/DANG-744: 회원 정보 수정 API 구현

backend/src/users/users.service.ts
OAuth Server로부터 받은 profileImage의 경우 OAuth Server의 CDN에 저장되어 있는 이미지 파일로 완전한 url 형태이기 때문에 우리 S3에 저장하지 않았다. 따라서 S3에 존재하는 이미지일 경우에만 삭제 처리를 하도록 추가했다.
https://www.notion.so/do0ori/S3-4921a1929555455ca7324eb06150de0b
- 예시
- 예시
=> backend/DANG-747: S3 이미지일 경우에만 삭제처리하도록 업데이트

backend/src/auth/auth.service.spec.ts, backend/src/auth/auth.service.ts, backend/src/s3/s3.service.ts
회원탈퇴 시 S3에서 회원의 폴더를 삭제하도록 추가
https://www.notion.so/do0ori/S3-6b447b03ca9540c69ba1216aa0ad6094
- 예시
- 예시
=> backend/DANG-719: 회원탈퇴시 S3에서 해당 유저의 데이터(폴더) 삭제

backend/src/excrements/excrements.entity.ts
excrement는 한 산책일지, 같은 강아지, 같은 타입 내에서도 중복될 수 있어
컴포지트 키를 삭제하고 pk를 추가했습니다.
- 예시
- 예시
=> backend/DANG-759: excrements 엔티티 primary 컬럼 추가하고 컴포지트 키 삭제

frontend/src/pages/Journals/CreateForm.tsx
산책일지 저장 페이지에서 테스트용 콘솔 출력 제거
https://www.notion.so/do0ori/4cfa74fbe2424f1c84beaef4c5d2b8cc?pvs=4
- 예시
- 예시
=> frontend/DANG-763: 산책일지 저장 페이지에서 테스트용 콘솔 출력 제거

backend/src/common/database/database.module.ts, backend/src/dogs/dogs.service.ts
- DataSource with name 'default' has already added 에러 방지 코드 추가
- DatabaseModule에서 이름이 'default'인 DataSource를 가져오거나 없으면 새로 생성하도록 함
https://www.notion.so/do0ori/DataSource-with-name-default-has-already-added-d395e4d352c74dd1b6785bbed17d16dc
- 예시
- 예시
=> backend/DANG-765: 간헐적인 DataSource with name 'default' has already added. 에러 해결하기

frontend/src/components/journals/DogImages.tsx, frontend/src/components/journals/Photos.tsx, frontend/src/pages/Journals/CreateForm.tsx
산책일지 저장 페이지에서 타입과 변수 이름 변경
- 타입: `ImageUrl` → `ImageFileName`
- 상태: `images` → `imageFileNames`
- 변수: `photoUrls` → `photoFileNames`
- 프롭: `imageUrls` → `imageFileNames`
https://www.notion.so/do0ori/4bde9c26354740b3aed0a3a6474b6e05?pvs=4
- 예시
- 예시
=> frontend/DANG-764: 산책일지 저장 페이지에서 타입과 변수 이름 변경

backend/src/excrements/excrements.entity.ts, backend/src/excrements/excrements.service.ts, backend/src/journals-dogs/journals-dogs.service.ts, backend/src/journals/dto/journals-detail.dto.ts, backend/src/journals/journals.service.ts
산책일지 상세 API를 변경했습니다.
- excrements 관계형 컬럼과 이름이 같은 일반 컬럼을 추가했습니다. typeorm에서 find시 이렇게 해야 결과가 조회됩니다. 
- 예시
- 예시
=> backend/DANG-729: 산책일지 상세 API 변경

frontend/src/components/journals/Memo.tsx
Memo 컴포넌트에 readonly 기능 구현
https://www.notion.so/do0ori/Memo-readonly-5a05006061ca47f7bc710a2a8905b5aa?pvs=4
- 예시
- 예시
=> frontend/DANG-769: Memo 컴포넌트에 readonly 기능 구현

frontend/src/api/upload.ts, frontend/src/components/journals/DogImages.tsx, frontend/src/components/journals/Photos.tsx, frontend/src/pages/Journals/CreateForm.tsx
산책일지 저장 페이지에서 사진 삭제 기능 구현
https://www.notion.so/do0ori/0aedcf4d45d34bae89cf7c9762ebbd30?pvs=4
- 예시
- 예시
=> frontend/DANG-770: 산책일지 저장 페이지에서 사진 삭제 기능 구현

backend/src/journals/journals.service.ts, backend/src/statistics/statistics.controller.ts, backend/src/statistics/statistics.service.ts, backend/src/utils/date.utils.ts
- 한달 전 날짜를 구하는 util 함수 추가
- 한달의 기준은 단순히 (월 - 1)
ex. 2024-05-21 → 2024-04-21
- [강아지의 최근 한달 간 산책 통계 API ](https://www.notion.so/do0ori/71574bd772e64614923ba0a2087f24b4)구현
https://www.notion.so/do0ori/API-330def6b74d346519fd27961047eb41c
- 예시
- 예시
=> backend/DANG-773: 강아지의 최근 한달 간 산책 통계 API 구현

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.spec.ts, backend/src/auth/auth.service.ts, backend/src/auth/decorators/oauth-data.decorator.ts, backend/src/auth/dtos/oauth.dto.ts, backend/src/auth/interceptors/cookie.interceptor.ts, backend/src/auth/token/token.service.ts, backend/src/auth/types/auth.type.ts, backend/src/users/users.service.ts
`ValidationPipe`에 `validateCustomDecorators` option을 사용해 OauthCookies custom decorator에서 반환하는 값에도 class validation을 적용했다.
DTO는 client와 server 간에 주고 받는 데이터 전송 객체이기 때문에 validation에만 사용하고 그 외에는 type에서 정의한 객체를 사용해 역할을 분리했다.
https://www.notion.so/do0ori/Auth-Validation-7409ea05c3e14297933092ccd21f2f93
- 예시
- 예시
=> backend/DANG-781: Auth에 Validation 추가

frontend/src/api/journals.ts, frontend/src/components/common/Avatar.tsx, frontend/src/components/journals/CompanionDogSection2.tsx, frontend/src/components/journals/JournalCard.tsx, frontend/src/index.tsx, frontend/src/pages/Journals/Detail.tsx
산책기록 상세 페이지에서 데이터 바인딩과 수정 구현
https://www.notion.so/do0ori/511bb4b4e67f479992008442b6526b4e?pvs=4
- 예시
- 예시
=> frontend/DANG-779: 산책기록 상세 페이지에서 데이터 바인딩과 수정 구현

backend/src/dog-walk-day/dog-walk-day.service.ts, backend/src/today-walk-time/today-walk-time.service.ts, backend/src/utils/date.util.ts
홈 화면 조회시 today_walk_time 마지막 업데이트일이 오늘 이전인지 확인해서 리셋하는 로직을 추가했습니다.
- 예시
- 예시
=> backend/DANG-791: 홈 화면 조회시 today_walk_time 마지막 업데이트일이 오늘 이전인지 확인해서 리셋

backend/src/journals/journals.service.ts
산책일지 생성시,photoURL을 보내지 않은 경우에도 journal-photos에 새 행을 만들도록 변경했습니다.
이에 따라 산책일시 상세 조회시 photoUrl에 있는 빈 문자열이 그대로 보내지는 문제가 있어서,
photoUrl의 값이 하나이고, 빈 문자열이면 빈 배열을 리턴하도록 변경했습니다.
- 예시
- 예시
=> backend/DANG-805: photoUrl 없을 시 빈배열 리턴

backend/src/journal-photos/journal-photos.service.ts, backend/src/journals/journals.service.ts
- 산책일지 사진 삭제 시, 레코드를 먼저 찾고 없을 때만 삭제하도록 변경
- 산책일지 생성시 빈 문자열로 journals-photos에 레코드 생성하는 로직 삭제
- 빈 문자열 -> 빈 배열로 변경하는 로직도 삭제
- 예시
- 예시
=> backend/DANG-812: 산책일지 수정 API 버그 수정

frontend/src/components/common/Avatar.tsx, frontend/src/utils/url.test.ts, frontend/src/utils/url.ts
Avatar 컴포넌트의 이미지 경로 문제
https://www.notion.so/do0ori/Avatar-db658f1ecf6540688feac4ca6ef3a7f8?pvs=4
- 예시
- 예시
=> frontend/DANG-799: Avatar 컴포넌트의 이미지 경로 문제

frontend/src/assets/icons/ic-meatball.svg, frontend/src/components/journals/Heading.tsx, frontend/src/pages/Journals/Detail.tsx
산책일지 상세 페이지에서 상단 바의 외관 구현
https://www.notion.so/do0ori/ea5abe1ba6d84409a379338fd8f62e87?pvs=4
- 예시
- 예시
=> frontend/DANG-815: 산책일지 상세 페이지에서 상단 바의 외관 구현

backend/src/dogs/dogs.service.ts, backend/src/utils/manipulate.util.ts
- targetAttributes를 옵셔널로 받도록 변경
- 인자가 문자열로 들어와도 배열로 바꾸어 동일한 로직 사용하도록 변경
- 예시
- 예시
=> backend/DANG-849: makeSubobjectsArray 함수 개선

backend/src/statistics/pipes/date-validation.pipe.ts, backend/src/statistics/pipes/period-validation.pipe.ts
따로 DTO를 이용한 validation 대신 각 parameter마다 custom pipe를 적용하고 있기 때문에 value가 없는 경우에 대해서도 처리해주었다.
https://www.notion.so/do0ori/Statistics-pipe-validation-b49aabc54cf24412b0aa284d324aba81
- 예시
- 예시
=> backend/DANG-887: custom pipe에서 value가 없을 경우 error 발생시키도록 코드 추가

backend/src/auth/auth.service.ts, backend/src/auth/guards/auth.guard.ts, backend/src/auth/guards/refresh-token.guard.ts, backend/src/auth/oauth/google.service.ts, backend/src/auth/oauth/kakao.service.ts, backend/src/auth/oauth/naver.service.ts, backend/src/common/interceptors/logging.interceptor.ts, backend/src/common/logger/winstonLogger.service.ts
- log format을 text에서 json으로 변환하여 Loki에서 log data를 json 형태로 다룰 수 있도록 했다.
- 각 level method에 `meta` parameter를 추가하여 원하는 field를 동적으로 log에 포함시킬 수 있도록 했다.
- console에서 meta parameter가 보기 좋게 출력되도록 consoleLogFormat 함수를 개선했다.
- 바뀐 log method에 맞게 존재하는 모든 log 업데이트
```log
2024. 5. 31. 오후 9:46:17 | INFO   | AppController {/}:
2024. 5. 31. 오후 9:46:17 | INFO   | Mapped {/, GET} route
2024. 5. 31. 오후 9:46:17 | INFO   | HealthController {/health}:
2024. 5. 31. 오후 9:46:17 | INFO   | Mapped {/health, GET} route
```
```log
{"level":"info","message":"AppController {/}:","timestamp":"2024-05-31T12:32:00.956Z"}
{"level":"info","message":"Mapped {/, GET} route","timestamp":"2024-05-31T12:32:00.957Z"}
{"level":"info","message":"HealthController {/health}:","timestamp":"2024-05-31T12:32:00.957Z"} …
```
=> backend/DANG-863: WinstonLogger의 log를 json 형식으로 변환 & log 형식 개선

backend/src/excrements/excrements.service.ts, backend/src/journals/dtos/create-journal.dto.ts, backend/src/journals/dtos/update-journal.dto.ts, backend/src/journals/journals.controller.ts, backend/src/journals/journals.service.ts, backend/src/journals/types/create-journal-data.type.ts, backend/src/journals/validator/WGS84.validator.ts
- journals에 validation pipe 적용, 부족한 데코레이터 보완
- WGS84 좌표계 확인하는 custom validator 추가
- class-validator에도 위도, 경도를 확인하는 @IsLatitude, @IsLatitude()  데코레이터가 있지만 
GPS에서 사용하는 WGS84 좌표계가 아닌 DM, DMS 형식을 기반으로 해서 맞지 않음
간단하게 앞에마이너스 부호와, 중간에 소숫점을 허용하도록 하는 정규표현식을 사용해 구현함
- 일지 생성시 excrements가 없는 경우에 대한 분기 처리가 안되어있어 추가
- 예시
- 예시
=> backend/DANG-868: journlas validation 추가

frontend/src/api/auth.ts, frontend/src/hooks/useAuth.ts, frontend/src/store/authStore.ts
비로그인상태에서 getRefreshToken api 호출되는 문제 
로그인 상태로 조건부로 api 호출하기
- 예시
- 예시
=> frontend/DANG-904: 비로그인상태에서 getRefreshToken api 호출하지 않기

frontend/src/hooks/useDogsStatistic.ts, frontend/src/pages/Home.tsx
accesstoken 비동기 이슈로 인해 useDogsStatistic에 enabled 옵션으로 getRefreshToken와의 의존성 삭제
- 예시
- 예시
=> frontend/DANG-905: useDogsStatistic: getRefreshToken 의존성 (enabled) 삭제

backend/src/auth/interceptors/cookie.interceptor.ts, backend/src/auth/token/token.service.ts
- tokenService에서 process.env로 token 만료 기간을 가져오지 못하는 문제가 발생했다.
- TokenService class 내에서 configService를 사용해 TOKEN_LIFETIME_MAP을 static member로 설정해주었다.
- TokenService.TOKEN_LIFETIME_MAP으로 가져와 사용 가능하다.
https://www.notion.so/do0ori/token-process-env-d55896b31b544ea3bc5d64c7b252ac96
- 예시
- 예시
=> backend/DANG-910: token process.env 문제 해결하기

backend/src/utils/manipulate.util.ts
makeSubObjectsArray 함수에서 할당시 src와 target의 위치가 바뀌어 생긴 문제
변수명이 헷갈리는것같아 원래 객체의 속성 : srcAttributes, 새로 만들 객체의 속성 : newAttributes로 수정함
- 예시
- 예시
=> backend/DANG-915: 산책일지 목록에서 journalId를 리턴하지 않는 버그 수정

backend/src/app.controller.spec.ts, backend/src/auth/auth.service.ts, backend/src/auth/guards/auth.guard.ts, backend/src/auth/guards/oauth-data.guard.ts, backend/src/auth/guards/refresh-token.guard.ts, backend/src/auth/oauth/google.service.ts, backend/src/auth/oauth/kakao.service.ts, backend/src/auth/oauth/naver.service.ts, backend/src/common/logger/winstonLogger.service.ts, backend/src/dogs/dogs.service.ts, backend/src/dogs/guards/auth-dog.guard.ts, backend/src/journals/guards/auth-journal.guard.ts, backend/src/statistics/statistics.service.ts, backend/src/today-walk-time/today-walk-time.service.ts
- meta parameter가 string일 때 `…meta`를 하게 되면 (index: 문자) 형태로 spread되어 버리는 것이 원인이었다.
- trace까지 포함해서 meta parameter로 받도록 한다.
- `this.logger.error('error message', { trace: 'trace' })`와 같이 사용하면 된다.
https://www.notion.so/do0ori/ERROR-79a0a23df9814ba28e5627b6cfecf659
- 예시
- 예시
=> backend/DANG-913: ERROR 로그에서 원치 않는 메타 데이터 찍히는 버그 해결하기

frontend/src/App.tsx, frontend/src/api/auth.ts, frontend/src/api/breed.ts, frontend/src/api/dogs.ts, frontend/src/api/http.ts, frontend/src/hooks/useAuth.ts, frontend/src/hooks/useBreed.ts, frontend/src/store/authStore.ts
httpClient interceptor request에서 accessToken을 몇 가지 제외사항 나머지 우리 서버 관련 api request header에 넣어주고
비동기 이슈로 header에 token이 들어가지 않았을때 response에서 401에러가 났을때 캐싱된 accessToken을 fetch하여 header에 설정해주고 원래 호출하려던 api를 재호출 하는 방식으로 비동기 이슈 해결
- 예시
- 예시
=> frontend/DANG-903: accessToken 설정을 custom axios interceptor에서 관리하기

backend/src/common/database/database.module.ts, backend/test/app.e2e-spec.ts
database module에서 data source option 중 entities에 경로를 명시하고 있지만 e2e test 시 seeding 작업에서 사용하는 Breed를 찾지 못하고 있어 해당 entity class를 직접 추가해주어 해결했다.
https://www.notion.so/do0ori/e2e-test-EntityMetadataNotFoundError-No-metadata-for-Breed-was-found-c311e486a503409db89e37b64c29d164
- 예시
- 예시
=> backend/DANG-925: e2e test 실행 시 발생하는 EntityMetadataNotFoundError 해결하기

backend/src/common/interceptors/logging.interceptor.ts
응답이 object가 아닌 경우 ...res를 하게 되면 splat되어 버리기 때문에 object일 때만 ...res를 하도록 수정했다.
(#613 참고)
https://www.notion.so/do0ori/logger-response-446c64ea54e34880b79bfa4082d056f5
- 예시
- 예시
=> backend/DANG-926: object일 때만 spread 연산자를 사용해 출력하도록 수정

backend/src/auth/auth.service.spec.ts, backend/src/auth/auth.service.ts, backend/src/auth/guards/auth.guard.ts, backend/src/auth/guards/refresh-token.guard.ts, backend/src/common/logger/winstonLogger.service.ts, backend/src/fixtures/users.fixture.ts, backend/src/users/users.spec.ts, backend/test/app.e2e-spec.ts, backend/test/auth.e2e-spec.ts, backend/test/jest-e2e.json, backend/test/test-utils.ts
```bash
$ npm run test:e2e
> cross-env NODE_ENV=test jest --config ./test/jest-e2e.json --maxWorkers=1
PASS  test/auth.e2e-spec.ts (7.925 s)
AuthController (e2e)
/auth/login (POST)
비회원이 로그인 요청을 보내면
√ 404 상태 코드와 Oauth data cookie를 반환해야 한다. (54 ms)
회원이 로그인 요청을 보내면
√ 200 상태 코드와 body에는 access token, cookie에는 refresh token을 반환해야 한다. (48 ms)
요청 body에 authorizeCode field가 빠진 경우
√ 400 상태 코드를 반환해야 한다. (8 ms)
요청 body에 provider field가 빠진 경우
√ 400 상태 코드를 반환해야 한다. (10 ms)
요청 body의 provider field 값이 google, kakao, naver 중 하나가 아닌 경우                                                                                                                                                          
√ 400 상태 코드를 반환해야 한다. (6 ms) …
```
=> backend/DANG-859: auth e2e test 코드 작성

backend/src/auth/auth.service.spec.ts, backend/src/breed/breed.spec.ts, backend/src/dog-walk-day/dog-walk-day.spec.ts, backend/src/dogs/dogs.controller.ts, backend/src/dogs/dogs.service.ts, backend/src/dogs/dogs.spec.ts, backend/src/fixtures/dogs.fixture.ts, backend/src/fixtures/users.fixture.ts, backend/src/journals/journals.spec.ts, backend/src/users/users.service.spec.ts, backend/src/users/users.spec.ts, backend/test/auth.e2e-spec.ts, backend/test/constants.ts, backend/test/dogs.e2e-spec.ts, backend/test/test-utils.ts, docs/api/upload.yaml, docs/dogs/id-statistics.yaml, docs/journals/id.yaml, docs/openapi.yaml
```bash
$ npm run test:e2e -- --testPathPattern=test/dogs.e2e-spec.ts
> cross-env NODE_ENV=test jest --config ./test/jest-e2e.json --maxWorkers=1 --testPathPattern=test/dogs.e2e-spec.ts
PASS  test/dogs.e2e-spec.ts (7.199 s)
DogsController (e2e)
/dogs (GET)
사용자가 소유한 강아지가 없을 때 소유한 강아지 목록 요청을 보내면
√ 200 상태 코드와 빈 배열을 반환해야 한다. (31 ms)
사용자가 소유한 강아지가 존재할 때 소유한 강아지 목록 요청을 보내면
√ 200 상태 코드와 강아지 프로필 목록을 반환해야 한다. (50 ms)
/dogs (POST)
사용자가 강아지 등록 요청을 보내면
√ 201 상태 코드를 반환해야 한다. (59 ms)
사용자가 존재하지 않는 견종으로 강아지 등록 요청을 보내면
√ 404 상태 코드를 반환해야 한다. (73 ms)
/dogs/:id (GET)
사용자가 자신이 소유한 강아지의 프로필 조회 요청을 보내면
√ 200 상태 코드와 강아지 프로필을 반환해야 한다. (106 ms)
사용자가 자신이 소유하지 않은 강아지의 프로필 조회 요청을 보내면
√ 403 상태 코드를 반환해야 한다. (52 ms)
/dogs/:id (PATCH)
사용자가 자신이 소유한 강아지의 정보 수정 요청을 보내면
√ 204 상태 코드를 반환해야 한다. …
```
=> backend/DANG-938: DogsController e2e test 코드 작성

backend/src/auth/auth.controller.ts, backend/src/dogs/dogs.controller.ts, backend/src/fixtures/users.fixture.ts, backend/src/journals/journals.controller.ts, backend/src/users/users.controller.ts, backend/src/walk/walk.controller.ts, backend/test/users.e2e-spec.ts
```bash
$ npm run test:e2e -- --testPathPattern=test/users.e2e-spec.ts
> cross-env NODE_ENV=test jest --config ./test/jest-e2e.json --maxWorkers=1 --testPathPattern=test/users.e2e-spec.ts
PASS  test/users.e2e-spec.ts (8.779 s)
UsersController (e2e)
/users/me (GET)
사용자가 회원 정보 조회 요청을 보내면
√ 200 상태 코드와 사용자 정보를 반환해야 한다. (50 ms)
/users/me (PATCH)
사용자가 회원 정보 수정 요청을 보내면
√ 204 상태 코드를 반환해야 한다. (37 ms)
Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        8.888 s, estimated 49 s
Ran all test suites matching /test\\users.e2e-spec.ts/i.
```
https://www.notion.so/do0ori/UsersController-e2e-test-7ab118e87ecb466ab92031a772b62223
- 예시
- 예시
- 함수는 한 가지 일을 해야 한다는 원칙에 …
=> backend/DANG-944: UsersController e2e test 코드 작성

backend/src/breed/breed.service.spec.ts, backend/src/fixtures/breed.fixture.ts
- BreedService의 findOne 메서드가 특정 ID의 견종 정보를 성공적으로 조회하는지 테스트
- 견종 정보 조회 성공 시, 올바른 견종 데이터를 반환하는지 검증
- Fixture 데이터를 활용하여 테스트 환경 구성
- 예시
- 예시
=> backend/DANG-949: BreedService의 findOne 메서드 테스트 케이스 추가

backend/package.json, backend/test/auth.e2e-spec.ts, backend/test/constants.ts, backend/test/dogs.e2e-spec.ts, backend/test/statistics.e2e-spec.ts, backend/test/test-utils.ts, backend/test/users.e2e-spec.ts
```bash
$ npm run test:e2e
> cross-env NODE_ENV=test jest --config ./test/jest-e2e.json --maxWorkers=1
PASS  test/dogs.e2e-spec.ts (9.747 s)
DogsController (e2e)
/dogs (GET)
사용자가 소유한 강아지가 없을 때 소유한 강아지 목록 요청을 보내면
√ 200 상태 코드와 빈 배열을 반환해야 한다. (39 ms)
사용자가 소유한 강아지가 존재할 때 소유한 강아지 목록 요청을 보내면
√ 200 상태 코드와 강아지 프로필 목록을 반환해야 한다. (58 ms)
Authorization header 없이 강아지 목록 요청을 보내면
√ 401 상태 코드를 반환해야 한다. (12 ms)
구조가 잘못된 access token을 Authorization header에 담아 강아지 목록 요청을 보내면
√ 401 상태 코드를 반환해야 한다. (7 ms)
만료된 access token을 Authorization header에 담아 강아지 목록 요청을 보내면
√ 401 상태 코드를 반환해야 한다. (6 ms)
존재하지 않는 userId를 가진 access token을 Authorization header에 담아 강아지 목록 요청을 보내면  
√ 401 상태 코드를 반환해야 한다. (9 ms)
/dogs (POST)
사용자가 강아지 등록 요청을 보내면
√ 201 상태 코드를 반환해야 한다. (62 ms)
사용자가 존재하지 않는 견종으로 강아지 …
```
=> backend/DANG-969: e2e test Authorization header 인가 test 공통 함수로 분리하여 적용하기

backend/src/auth/auth.service.ts, backend/src/s3/__mocks__/s3.service.ts, backend/src/s3/s3.controller.ts, backend/test/s3.e2e-spec.ts
```bash
$ npm run test:e2e -- --testPathPattern=test/s3.e2e-spec.ts
> cross-env NODE_ENV=test jest --config ./test/jest-e2e.json --maxWorkers=1 --testPathPattern=test/s3.e2e-spec.ts
PASS  test/s3.e2e-spec.ts (11.833 s)
S3Controller (e2e)
/api/upload (POST)                                                                                                                                                                                             
사용자가 이미지 업로드를 위한 presignedUrl 요청을 보내면                                                                                                                                                     
√ 200 상태 코드와 presignedUrl을 반환해야 한다. (49 ms) …
```
=> backend/DANG-942: S3Controller e2e test 코드 작성

frontend/src/hooks/useAuth.ts
as-is : 
1. 회원탈퇴 후 useNavigate 사용해서 '/' 루트로 리다이렉트했더니 re-render 에러 발생
2. 로그아웃 후 홈으로 갔다가 마이페이지로 이동하면 isSignedIn 스토리지가 bfcache되는 문제 발생
to-be: 
1. window.location.href = '/'으로 리다이렉트로 해결
2.window.location.href = '/'으로 리다이렉트해서 새로고침됨으로써 bfcache 캐싱 해결 
- 예시
- 예시
=> frontend/DANG-975: 로그아웃, 회원탈퇴  후 isSignedIn bfcache 문제 해결

backend/src/statistics/statistics.service.ts
- getDogWalkCnt 함수 내에서 startDate와 endDate 변수 선언을 한 줄로 합쳐져 있던 것을 각각 분리하여 가독성을 향상시켰습니다.
- 변수 타입은 명시적으로 Date로 지정했습니다.
- 예시
- 예시
=> infra/DANG-994: startDate와 endDate 변수 선언 분리

backend/src/dogs/dogs.service.ts, backend/src/journals/guards/auth-journal.guard.ts, backend/src/journals/journals.service.ts, backend/src/users/users.service.ts, backend/src/utils/manipulate.util.ts, backend/src/walk/dtos/walk-command.dto.ts, backend/src/walk/guards/auth-dogs.guard.ts, backend/src/walk/walk.controller.ts, backend/test/walk.e2e-spec.ts
```bash
$ npm run test:e2e -- --testPathPattern=test/walk.e2e-spec.ts
> cross-env NODE_ENV=test jest --config ./test/jest-e2e.json --maxWorkers=1 --testPathPattern=test/walk.e2e-spec.ts
PASS  test/walk.e2e-spec.ts (8.986 s)
WalkController (e2e)
/dogs/walks/start (POST)                                                                                                                                                   
사용자가 소유한 강아지 목록으로 산책 시작 요청을 보내면                                                                                                                  
√ 200 상태 코드와 강아지 목록을 반환해야 한다. (107 ms)                                                                                                                
사용자가 소유하지 않은 강아지가 포함된 목록으로 산책 시작 요청을 보내면 …
```
=> backend/DANG-945: WalkController e2e test 코드 작성

backend/src/auth/interceptors/cookie.interceptor.ts
배포환경에서 client는 `'https://dangdang-walk.xyz'`, server는 `'https://api.dangdang-walk.xyz'`를 사용하게 되면서 same-site 환경이 되었다. 따라서 sameSite option은 default 값인 `'lax'`를 그대로 사용한다.
domain option은 따로 설정하지 않으면 자동으로 `api.dangdang-walk.xyz`가 되는데 어차피 모든 요청을 여기서 처리할 것이기 때문에 따로 설정하지 않았다.
https://www.notion.so/do0ori/Set-Cookie-option-01a11cf397c5415d91a69b83ee280aff
- 예시
- 예시
=> backend/DANG-1000: 서버 이전에 따른 Set-Cookie option 수정

backend/src/auth/auth.service.ts
url -> path로 통일하기 위해 
기존에 사용하던 oauth에서 가져온 프로필 이미지 url을 사용하지 않고,
s3에 올라가 있는 디폴트 프로필 이미지를 사용하도록 변경하였습니다.
- 예시
- 예시
=> backend/DANG-1016: 회원가입시 디폴트 프로필 이미지 사용하도록 변경

backend/src/common/database/abstract.repository.ts, backend/src/common/database/database.module.ts, backend/src/journals/journals.service.ts
- query logging 추가 - 가장 가까운 package.json 파일이 존재하는 root 폴더에 ormlogs.log 파일에 생성되며 여기에 log가 저장된다.
- `entityManager.save`로 entity를 insert하면 새로운 entityManager가 생성되어 @Transactional 적용 시 문제가 발생하기 때문에 수정했다.
- 추상 리포지토리에서 entityManager를 사용하는 method는 없지만 추상 리포지토리를 상속받는 리포지토리에서 entityManager를 사용하고 있으므로 주입해둔다.
- JournalsService에 transaction 적용
https://www.notion.so/do0ori/updateJournal-Transactional-hang-4c094889200e4d03a5d0bbe5eb85a3bc
https://www.notion.so/do0ori/Transactional-Lock-wait-timeout-exceeded-634ef101b1624bf7879875a36edbb800
- 예시
- 예시
=> backend/DANG-1018: updateJournal에 @Transactional 적용 시 요청이 hang되는 오류 해결하기

backend/src/auth/auth.service.spec.ts, backend/src/auth/auth.service.ts, backend/src/auth/guards/auth.guard.ts, backend/src/auth/guards/oauth-data.guard.ts, backend/src/auth/guards/refresh-token.guard.ts, backend/src/dogs/guards/auth-dog.guard.ts, backend/src/journals/guards/auth-journal.guard.ts, backend/src/walk/guards/auth-dogs.guard.ts
- guard 가독성 향상 및 validation 추가 
- logic을 method로 분리하여 canActivate의 가독성을 향상시켰다.
- AuthDogGuard의 경우 dogId의 값을 query나 params에서 가져올 때 validation 추가했다. dogId의 값을 params에서 가져올 때에는 controller의 url에서 regex로 검증되지만 query에서 가져올 때에는 따로 validation이 필요하기 때문이다.
- AuthService의 validateAccessToken과 validateRefreshToken에서 token verify까지 진행하도록 수정했다.
- 바뀐 method logic에 맞게 test code 수정
- Guard를 수정하면서 AuthService의 validateAccess/RefreshToken method가 변경되어 이에 맞게 test code를 수정했다.
https://www.notion.so/do0ori/Guard-refactoring-9d155038ed1745b38af6e368ee0b45bb
- 예시
- 예시
=> backend/DANG-1021: Guard refactoring

frontend/src/api/http.ts, frontend/src/pages/Join/index.tsx
storage에 isSignedIn이 true인 상태에서 refreshToken이 cookie에 없는경우 로그인 상태로 있을때 
interceptor에서 비로그인화 상태로 만들기 
- 예시
- 예시
=> frontend/DANG-1025: cookie에 refreshtoken 없을때 로그아웃 되지 않는 문제 해결

frontend/src/components/NavbarProvider.tsx, frontend/src/hooks/useAuth.ts
LoginAlertModal에서 localStorage에 isSignedIn 상태를 확인해서 렌더링 했었는데,
refreshTokenQuery.isSuccess 유무로 판단하는 걸로 수정
새로고침했을때 modal 잠깐 렌더링 되는 것도 !refreshTokenQuery.isLoading 조건을 주어서 렌더링 안되게 수정
- 예시
- 예시
=> frontend/DANG-1033: LoginAlertModal 로그인 상태관련 로직 수정

backend/test/journals.e2e-spec.ts, backend/test/test-utils.ts
- 산책 일지 생성 테스트의 오타를 수정했다.
- 산책 일지 생성 및 삭제 시 DogWalkDay가 업데이트되므로 검증 코드를 추가했다.
- 이에 맞게 test-utils에서 mockJournal 생성 및 삭제 함수에서도 DogWalkDay를 추가했다.
https://www.notion.so/do0ori/JournalsController-e2e-test-DogWalkDay-bba23daa3f7847b1a6261df46599882b
- 예시
- 예시
=> backend/DANG-1038: 산책 일지 생성 및 삭제 시 DogWalkDay까지 확인하도록 e2e test 수정

backend/test/journals.e2e-spec.ts
https://www.notion.so/do0ori/e2e-test-case-fe947917c946454fa4e2f1d15c9fcd87
- 예시
- 예시
=> backend/DANG-1057: FakeDate을 설정해 산책 일지 삭제 요청 시 walkDay 검증이 실패하는 오류 수정

README.md, backend/src/auth/auth.service.ts, backend/src/auth/token/token.service.ts
- 추후 병렬 처리를 하기 위해 TokenService method를 비동기 함수로 변경
- 불필요한 전역 변수 제거
- TokenService method들을 병렬 처리를 위해 비동기 함수로 변경했으므로 await 추가
- TODO 추가
- batch query
- `Promise.all`로 병렬 처리
https://www.notion.so/do0ori/AuthService-TODO-236be76c60534b16b3a6b987c17b1893
왜인지 오늘 같이 추가한 auth TODO가 누락되어서 따로 확인해서 추가함
- 예시
- 예시
=> backend/DANG-1063: TokenService method를 비동기 함수로 수정 및 AuthService TODO 추가

frontend/src/hooks/useDog.ts, frontend/src/hooks/useDogsStatistic.ts, frontend/src/pages/Join/index.tsx
최초가입후 강아지 등록 후 callback 페이지로 리다이렉트 되는 문제 해결
- 예시
- 예시
=> frontend/DANG-1068: 최초가입후 강아지 등록 후 callback 페이지로 리다이렉트 되는 문제 해결

frontend/src/components/journals/MemoSection.tsx, frontend/src/pages/Journals/Detail.tsx
일지 상세 페이지에서 읽기 모드일 때 메모 포커스 없애기
https://www.notion.so/do0ori/fd93343842a44f05ba88efb419705342?pvs=4
- 예시
- 예시
=> frontend/DANG-1069: 일지 상세 페이지에서 읽기 모드일 때 메모 포커스 없애기

docs/auth/users.yaml, docs/images/delete.yaml, docs/journals/id.yaml
삭제, 수정 성공시 리턴할 데이터가 없어도 true를 반환했었는데
그럴 필요가 없다고 판단되어 reponse 데이터를 없애고,
status 코드를 200 -> 204(성공했음 & 반환 데이터 없음)로 변경하였고
이를 swagger에도 반영하였습니다.
- 예시
- 예시
=> backend/DANG-1083: status code 200->204로 변경된 api swagger에 반영

backend/src/fixtures/users.fixture.ts, backend/src/users/users.spec.ts, backend/test/auth.e2e-spec.ts, backend/test/constants.ts, backend/test/statistics.e2e-spec.ts
- 하나의 파일에서 상수들을 관리하기 위해 `users.fixture.ts`에 정의된 상수를 `constants.ts`로 옮겼다.
- fixture 파일에 의존하지 않기 위해 객체를 하드코딩하여 명시 
- database로 정확히 동작을 검증
https://www.notion.so/do0ori/auth-statistics-e2e-test-f23467a7febc4500b1be844bfe72acdb
- 예시
- 예시
=> backend/DANG-1093: auth, statistics e2e test 하드코딩

backend/test/dogs.e2e-spec.ts, backend/test/users.e2e-spec.ts
테스트 간 독립성을 유지하고, 사용되는 mock을 한눈에 볼 수 있게 하기 위해 fixture를 각 테스트에서 정의해 사용하는 방식으로 변경하였습니다.
- 예시
- 예시
=> backend/DANG-1095: dogs, s3, users e2e 테스트에서 fixture를 각 테스트에서 정의하도록 변경

backend/test/auth.e2e-spec.ts, backend/test/dogs.e2e-spec.ts, backend/test/journals.e2e-spec.ts, backend/test/s3.e2e-spec.ts, backend/test/statistics.e2e-spec.ts, backend/test/test-utils.ts, backend/test/users.e2e-spec.ts, backend/test/walk.e2e-spec.ts
- 고정된 mock data를 삽입하는 대신 parameter를 만들어 원하는 data를 삽입할 수 있도록 수정
- e2e test 코드에서 직접 값을 parameter로 넘겨주므로 가독성 향상 가능
https://www.notion.so/do0ori/test-utils-insert-method-2ad7b523a5b04d248dea872b8074ed4c
- 예시
- 예시
=> backend/DANG-1096: test-utils insert method 형식 변경

backend/test/auth.e2e-spec.ts, backend/test/dogs.e2e-spec.ts, backend/test/journals.e2e-spec.ts, backend/test/s3.e2e-spec.ts, backend/test/statistics.e2e-spec.ts, backend/test/test-utils.ts, backend/test/users.e2e-spec.ts, backend/test/walk.e2e-spec.ts
https://www.notion.so/do0ori/test-utils-insert-method-e2e-test-17455e70f50843b38627d8b27de0e4e7
- 예시
- 예시
=> backend/DANG-1100: 변경된 test-utils insert method 형식에 따라 e2e test 수정

backend/src/breed/breed.service.spec.ts, backend/src/breed/breed.service.ts
- breedIds 배열을 입력받아 각 견종의 권장 산책량을 조회하는 getRecommendedWalkAmountList 메서드 구현
- 견종 ID가 존재하지 않거나 빈 배열일 경우 예외 처리 (NotFoundException)
- 조회된 견종 정보를 맵으로 변환하여 권장 산책량 추출 및 반환
- 해당 메서드의 동작을 검증하는 테스트 케이스 작성
- 예시
- 예시
=> backend/DANG-1101: BreedService 테스트 케이스 추가

backend/src/auth/auth.service.ts, backend/src/auth/guards/auth.guard.ts, backend/src/auth/guards/oauth-data.guard.ts, backend/src/auth/guards/refresh-token.guard.ts, backend/src/auth/interceptors/cookie.interceptor.ts, backend/src/auth/oauth/google.service.ts, backend/src/auth/oauth/kakao.service.ts, backend/src/auth/oauth/naver.service.ts, backend/src/common/database/database.module.ts, backend/src/dog-walk-day/dog-walk-day.service.spec.ts, backend/src/dog-walk-day/dog-walk-day.service.ts, backend/src/dogs/dogs.service.ts, backend/src/dogs/guards/auth-dog.guard.ts, backend/src/journals/guards/auth-journal.guard.ts, backend/src/s3/s3.service.ts, backend/src/statistics/statistics.service.ts, backend/src/today-walk-time/today-walk-time.service.ts, backend/src/utils/manipulate.util.ts, backend/src/utils/ms.util.ts, backend/src/walk/guards/auth-dogs.guard.ts, backend/test/dogs.e2e-spec.ts, backend/test/journals.e2e-spec.ts, backend/test/users.e2e-spec.ts
가독성, 작업의 편의성을 높이기 위해 
에러 메세지를 영어에서 한글로 변경하였습니다.
공통적으로 적용된 규칙들
- 문장 끝의 온점은 필요하지 않은 것 같아 찍지 않았습니다.
- id가 n인 주체를 표현할 때, 주체 + n으로 표기하였습니다.
ex) id가 1인 유저 : 유저 1
뒤에 관사가 올 때, 숫자에 따라 '은' 또는 '는'이 올 수 있어 은/는으로 표기하였습니다.
- DB의 한 행 : 레코드로 표현하였습니다.
- validation에 통과하지 못했을 때 : [validation 대상]이 [적합한 타입]이 아닙니다. 로 표기하였습니다.
ex) dogId가 정수가 아닙니다
- 권한이 없을 때 : a는 b에 대한 접근 권한이 없습니다.
- 예시
- 예시
=> backend/DANG-1102: 에러 메세지 영어 -> 한글로 변경

backend/package.json, backend/src/auth/guards/oauth-data.guard.ts, backend/src/common/database/database.module.ts, backend/test/performance/__mocks__/oauth.service.ts, backend/test/performance/__mocks__/s3.service.ts, backend/test/performance/response-time.ts
=> backend/DANG-1103: API response time script 작성

backend/src/dog-walk-day/dog-walk-day.service.spec.ts, backend/src/dog-walk-day/dog-walk-day.service.ts
getWalkDayList 함수에 walkDayIds 인자가 빈 배열일 경우에 대한  예외처리 추가하고
이에 대한 테스트 케이스를 추가했습니다.
- 예시
- 예시
=> backend/DANG-1104: getWalkDayList 함수에 walkDayIds 인자가 빈 배열일 경우에 대한  예외처리 추가

backend/src/today-walk-time/today-walk-time.service.spec.ts, backend/src/today-walk-time/today-walk-time.service.ts
- updateDurations 메서드에서 todayWalkTimes 조회 결과가 비어있는 경우에만 예외 발생하도록 수정
- 예외 메시지에 누락된 walkTimeIds 정보 추가
- 테스트 케이스의 입력값 수정 (빈 배열 -> 존재하지 않는 walkTimeIds)
- 테스트 케이스의 예상 예외 메시지 수정
- 예시
- 예시
=> backend/DANG-1122: updateDurations 메서드 예외 처리 오류 수정

backend/src/today-walk-time/today-walk-time.service.spec.ts
- 기존 getWalkDurations 테스트 케이스에 누락되었던 todayWalkTimeRepository.update 메서드 모킹 추가
- 추후 getWalkDurations 테스트 케이스에 업데이트 로직이 추가될 경우를 대비하여 사전에 모킹 설정
- 예시
- 예시
=> backend/DANG-1125: getWalkDurations 테스트 케이스에 대한 repository.update 모킹 추가

backend/src/auth/auth.service.ts, backend/src/breed/breed.service.spec.ts, backend/src/breed/breed.service.ts, backend/src/common/database/abstract.repository.ts, backend/src/dog-walk-day/dog-walk-day.service.ts, backend/src/dogs/dogs.service.ts, backend/src/journals/journals.service.ts, backend/src/users-dogs/users-dogs.service.ts, backend/src/users/users.service.spec.ts, backend/src/users/users.service.ts, backend/src/walk/walk.service.ts
- findOne에 select 옵션을 사용하기 위해, where 뿐만 아니라  여러 옵션을 포괄하는 findOneOptions 타입으로 인자의 타입을 변경하였습니다.
- 예시
- 예시
=> backend/DANG-1127: findOne 인자 타입 findOneOptions로 변경

backend/test/performance/response-time.ts, backend/test/performance/utils/createMockEntity.util.ts, backend/test/performance/utils/random.util.ts
- utils에 random한 값을 반환하는 함수들과 mock entity들을 생성하는 함수들을 정의하였다.
- n명의 사용자에게 0~5마리의 강아지를 random하게 생성한다.
- postman을 사용하지 않고 data만 넣어본 예시! 잘 된다. 😄
```
$ npm run test:response-time
> nest-js-example@0.0.1 test:response-time
> cross-env NODE_ENV=test ts-node ./test/performance/response-time.ts
Test server running at http://localhost:3333
Successfully inserted test data:
┌─────────┬────────────┬───────┐
│ (index) │   Entity   │ Count │
├─────────┼────────────┼───────┤
│    0    │  'Users'   │  10   │
│    1    │   'Dogs'   │  25   │
│    2    │ 'UserDogs' │  25   │
└─────────┴────────────┴───────┘
Cleared all test data
```
https://www.notion.so/do0ori/API-response-time-script-insertTestData-a62c7f9285984b8893c6656fe0d4ca53
data 삽입/삭제만 따로 사용할 수 있게 분리하는 것도 좋을 것 같다.
- 예시
- …
=> backend/DANG-1105: n명의 사용자에게 0~5마리의 강아지를 random하게 생성하는 로직 추가

backend/src/breed/breed.service.ts
- breed service에서 select로 필요한 column만 반환하도록 추가
- breed table의 koreanName에 index를 추가할까 했지만 실제로 해본 결과 217개 밖에 안되는 너무 작은 table이라 개선 정도가 너무 미미해서 추가하지 않았다.
select를 추가한 것만으로는 개선 정도가 미미했지만 성능 측정에 익숙해져 보고자 연습 겸 해보았다.
https://www.notion.so/do0ori/select-182d25d12f67425d8f4bcf70e29ce25c
제대로 측정을 한 것인지 한번 읽어보시고 피드백 주시면 감사하겠습니다. 😄
- 예시
- 예시
=> backend/DANG-1134: Breed TODO select 추가 & 성능 개선 및 측정

backend/src/statistics/pipes/period-validation.pipe.ts, backend/src/statistics/statistics.controller.ts, backend/test/statistics.e2e-spec.ts
- 현재 최근 한달 간 산책 통계 API만 존재하기 때문에  `PeriodValidationPipe`에서 동적으로 period 값을 받도록 수정했다.
- statistics e2e test에 period query가 week인 test case 추가 (`period=week`)
https://www.notion.so/do0ori/API-period-query-validation-caca888003fc413fab1cd827e82b86ef
https://github.com/dangdangwalk/dangdang-walk/pull/790#discussion_r1653181712
- 예시
- 예시
=> backend/DANG-1139: 최근 한달 간 산책 통계 API period query validation 수정

backend/src/common/database/database.module.ts, backend/src/common/interceptors/profilingInterceptor.ts
- 기존 typeorm의 query log는 환경 변수 `ENABLE_QUERY_LOGGER` 값이 true인 경우에만 사용하도록 했다.
- ProfilingInterceptor에서 Query Id와 detail 정보를 삭제하고 timestamp와 실행한 총 query 개수, query 별 실행 시간을 기록하도록 수정했다. log도 환경 별로 찍힌다.
- 기존 orm log는 모든 query가 기록되는 반면 profiling log는 요청마다 실행된 query만 기록된다. 필요한 정보에 맞게 선택적으로 사용하면 된다.
https://www.notion.so/do0ori/query-logger-809e98fdbd0249bda3d9c71eed6cb52c
- 예시
- 예시
=> backend/DANG-1141: query logger 개선

backend/test/performance/response-time.ts, backend/test/performance/utils/createMockEntity.util.ts, backend/test/performance/utils/random.util.ts, backend/test/test-utils.ts
- n명의 사용자는 random한 강아지들과 함께 0~50개의 산책 일지를 random하게 생성한다.
- 산책 일지는 통계 API를 고려하여 30일 전 ~ 오늘 사이의 날짜로 random하게 설정했다.
- 사용자 100명 data 삽입 테스트를 해본 결과 성능 개선이 잘 된 것을 확인할 수 있다. (순서대로 적용)
이전 작업 대비 개선된 정도를 확인해보면 `save`에서 `insert`로 바꿨을 때 불필요한 query들이 제거되고 bulk insert가 의도한대로 이루어지면서 큰 성능 개선이 일어난 것을 확인할 수 있다. 실제로 `ENABLE_QUERY_LOGGER=true`로 query log를 보며 확인했다.
|작업| 100명의 사용자를 생성했을 때 data 당 평균 삽입 시간|
|--|:--:|
|독립적인 삽입 method를 병렬로 처리|0.8~1ms|
|데이터 삽입 시 `save` 대신 `insert` 사용|0.05ms|
|method 내부 query들을 병렬 처리|0.02~0.03ms|
- 사용자 100명 data 삽입 예시 (삽입에 걸린 시간과 전체 data size를 출력하도록 업데이트함)
```bash
$ MYSQL_DATABASE=performance DATA_SIZE=100 npm run test:response-time
> nest-js-example@0.0.1 test:response-time
> cross-env NODE_ENV=test ts-node ./test/performance/response-time.ts
Test server running at …
```
=> backend/DANG-1143: API response time script의 insertTestData 함수에 일지 추가

backend/package.json, backend/test/performance/clear-database.ts, backend/test/performance/insert-test-data.ts, backend/test/performance/response-time.ts, backend/test/performance/utils/createMockEntity.util.ts, backend/test/performance/utils/testApp.util.ts
- TestApp 시작, 종료, TestData 삽입, 삭제 기능을 class로 분리하여 정의했다.
- 원하는 크기의 test data를 DB에 손쉽게 삽입, 삭제할 수 있는 script 파일을 작성했다.
- package.json 파일의 scripts에 명령어를 추가해 쉽게 사용할 수 있다. 다음은 사용 예시이다.
```bash
$ MYSQL_DATABASE=performance DATA_SIZE=100 npm run test:insert
> nest-js-example@0.0.1 test:insert
> cross-env NODE_ENV=test ts-node ./test/performance/insert-test-data.ts
Test server running at http://localhost:3333
Connected database: performance
Cleared all test data
Successfully inserted test data (+379ms):
┌─────────┬─────────────────┬───────┐
│ (index) │     Entity      │ Count │
├─────────┼─────────────────┼───────┤
│    0    │     'Users'     │  100  │
│    1    │     'Dogs'      │  227  │
│    2    │   'UserDogs'    │  227  │
│    3    │   'Journals'    │ 2089  │
│    4    │ 'JournalsDogs'  │ 4023 …
```
=> backend/DANG-1144: response-time script에서 각 기능을 독립적으로 사용할 수 있도록 분리

frontend/src/hooks/useJournal.ts, frontend/src/index.tsx, frontend/src/pages/Journals/Detail.tsx
https://www.notion.so/do0ori/loader-hook-5c1f6a1099d043d8a247a523ffacb0c7?pvs=4
- 예시
- 예시
=> frontend/DANG-1154: 산책일지 상세 페이지에서 loader를 커스텀 hook으로 대체

backend/src/s3/pipes/file-type-validation.pipe.ts, backend/src/s3/s3.controller.ts, backend/src/s3/s3.service.ts, backend/src/statistics/pipes/period-validation.pipe.ts, backend/test/s3.e2e-spec.ts
- `<input type="file" accept="image/*" />`를 사용할 때 허용되는 이미지 파일 확장자 목록을 참고해 이미지 파일 확장자만 받도록 custom validation pipe를 추가했다.
- s3 e2e test 파일에 `FileTypeValidationPipe` 관련 test case 추가
https://www.notion.so/do0ori/custom-validation-pipe-43a5d9ccd8f74e7e823c8cfb2b87c2f7
- 예시
- 예시
=> backend/DANG-1049: 이미지 파일 확장자만 받도록 custom validation pipe 추가

backend/src/dogs/dogs.service.ts, docs/dogs/id.yaml
산책 중인 강아지는 삭제하지 못하도록 예외처리를 추가했습니다. 
서버 리소스의 상태와 일치하지 않는 요청이 온 경우인 409 conflict 에러를 던지도록 처리했습니다. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409
- 예시
- 예시
=> backend/DANG-1152: 산책 중인 강아지의 경우 삭제하지 못하도록 예외처리 추가

backend/src/journals/journals.service.ts, backend/src/journals/types/create-journal-data.type.ts, backend/src/journals/types/journal-detail.type.ts, backend/src/journals/types/journal-info.type.ts, backend/src/walk/test.walk.service.ts
필요한 열만 가져오도록 select 옵션을 추가해 쿼리 성능을 향상하였습니다.
https://www.notion.so/do0ori/5a63faefd23b4bfb8dbd4f06338bcded?p=49ffaf998cb54f578a58487431a1c3a0&pm=s
https://www.notion.so/do0ori/5a63faefd23b4bfb8dbd4f06338bcded?p=968adc4fa24e4a60aa53d4698daa4171&pm=s
journals_dogs 테이블에서 journal_id만 select하도록 옵션을 주었지만 실제 실행된 쿼리는 여전히 journal_id, dog_id를 모두 가져오는 문제가 있었습니다.
직접 journal_id만 가져오도록 쿼리를 바꿔서 `EXPLAIN ANALYZE` 해봤더니 cost에 변화는 없었습니다.
이대로 써도 성능에 큰 영향은 없을 것 같지만 찝찝해서 해결책을 찾는 중입니다.
https://www.notion.so/do0ori/946c5f068b79446b85ba2ab5a040822a?v=7bd0ed1cabc7490f83c6c0c4e563bb83&p=83167d9cbd4f4425985a49e0695a7390&pm=s
- 예시
- 예시
이에 따라 코드가 실행되는 순간에 실행이 결정되는 if …
=> backend/DANG-1059: journals 쿼리에 select 옵션 추가

backend/src/dogs/dogs.spec.ts, backend/src/fixtures/dogs.fixture.ts, backend/src/s3/__mocks__/s3.service.ts, backend/src/s3/s3.service.ts, backend/test/auth.e2e-spec.ts, backend/test/performance/__mocks__/s3.service.ts
- 회원탈퇴 시 사용자가 소유한 강아지도 올바르게 삭제되는지 확인하도록 test case 수정
- S3에서 default 폴더의 파일은 삭제되지 않도록 처리
https://www.notion.so/do0ori/S3Service-default-c3f131071933419a84d9163d94482d2e
- 예시
- 예시
=> backend/DANG-1156: S3Service에서 default 폴더에 존재하는 파일은 삭제되지 않도록 처리

backend/src/auth/auth.service.ts, backend/src/dogs/dogs.service.ts, backend/src/users/users.service.ts
- 병렬 처리
- AuthService의 토큰 재발급 과정에서 Promise.all을 사용하여 병렬적으로 비동기 작업을 처리함.
- deleteUserData 메서드에서 사용자의 모든 개를 병렬적으로 삭제하도록 수정하고, 사용자 데이터 삭제와 S3 폴더 삭제를 병렬적으로 처리하도록 개선함.
- DogsService의 deleteDogFromUser 메서드에서 개와 관련된 데이터를 병렬적으로 삭제하도록 수정함.
- bulk delete 처리
- 사용자가 소유한 강아지를 loop를 돌며 하나씩 삭제하기보다는 deleteOwnDogs라는 method를 추가해 bulk delete하도록 변경
- usersService.delete가 사용자 삭제 및 사용자의 S3 폴더 삭제까지 병렬로 처리하도록 변경
https://www.notion.so/do0ori/AuthService-TODO-f58fd84a72a24c5cb2f4cba608838b92
https://www.notion.so/do0ori/9d751850cd8e412f907bcc35f8a57c80
사용자가 소유한 강아지 수: $n$
개선 비율: 0 ~ 57%
|  | Query 개수 | $n = 5$일 때<br>API 실행 시간 |
| -- | -- |-- |
|기존 API | $4n + 5$ | 37ms |
|개선된 API | 8 | 16ms |
</body>
</html>
- 예시
- 예시
- 함수는 한 가지 일을 해야 한다는 원칙에 따라 …
=> backend/DANG-1155: AuthService의 비동기 처리 성능 개선

backend/src/journals/journals.service.ts, backend/src/journals/types/journal-detail.type.ts, backend/test/journals.e2e-spec.ts, docs/journals/id.yaml
산책일지 상세 조회시
해당하는 산책일지 & 강아지의 배변 기록이 없으면 아예 필드를 보내지 않았는데
0을 넣어 보내도록 변경했습니다.
- 예시
- 예시
=> backend/DANG-1050: excrements가 없어도 0을 보내도록 변경

backend/test/performance/response-time.ts
test data 삽입, 삭제 script를 분리하면서 API 응답 속도 측정 script에서 DATA_SIZE 변수를 사용할 필요가 없어졌다.
https://www.notion.so/do0ori/API-script-DATA_SIZE-4c84c8b91351421b8a727c2bb42d9ffb
- 예시
- 예시
=> backend/DANG-1161: 더 이상 사용하지 않는 DATA_SIZE 변수 제거

backend/src/dog-walk-day/dog-walk-day.service.spec.ts, backend/src/dog-walk-day/dog-walk-day.service.ts, backend/src/dogs/dogs.service.ts, backend/src/fixtures/journals.fixture.ts, backend/src/statistics/statistics.service.ts, backend/src/today-walk-time/today-walk-time.service.spec.ts, backend/src/today-walk-time/today-walk-time.service.ts, backend/src/users/users.service.ts, backend/src/utils/date.util.spec.ts, backend/src/utils/date.util.ts
- select option을 추가해 가져올 열 명시
- 수정된 excrements 동작에 맞게 journals fixture 변경 (`urineCnt: 0`,)
- 날짜 범위를 가져오는 함수의 반환 타입을 `{ startDate, endDate }`으로 통일 및 period 예외 처리
- `dogsService`에서 `makeSubObject`를 활용해 `makeProfile` method 간소화, `find` method 추가
- 강아지 통계 method 개선 
- 기존에는 필요한 data를 모두 개별적인 query를 실행해 비효율적으로 가져왔었다.
- 단일 query를 사용해 필요한 정보를 모두 가져온 후 가공한다.
- 하루 산책 시간과 일주일 산책 횟수의 경우 조회 시 오래된 data인 경우 초기화를 하는 logic이 필요하므로 따로 method를 만들어 사용했다.
https://www.notion.so/do0ori/DogsService-StatisticsService-UsersService-TODO-ffe0ded760c846c69821e5dbbc134ec7
https://www.notion.so/do0ori/Join-select-data-9e701eda49b5446f9e8129247dabe7ba
- 예시
- 예시
이에 따라 …
=> backend/DANG-1159: DogsService, StatisticsService, UsersService TODO

backend/src/common/database/abstract.repository.ts, backend/src/excrements/excrements.service.spec.ts, backend/src/excrements/excrements.service.ts, backend/src/excrements/fake-excrements.service.ts, backend/src/journal-photos/journal-photos.service.ts, backend/src/journals/journals.service.ts, backend/src/journals/types/journal-detail.type.ts
산책일지 상세 성능 개선
- 참여한 강아지들의 정보를 가져올 때 `where : IN` 을 사용해 한 번의 쿼리로
조회할 수 있도록 변경
- dog_id, type별로 배변량의 count를 계산하는 쿼리를 사용해 한 번의
쿼리로 조회할 수 있도록 변경
- `Promise.all`로 순서가 중요하지 않은 쿼리는 병렬 처리
- journal_photos 테이블 조회시 `select` 옵션으로 열 명시
기타
- abstract repository의 find 메소드에 404 예외처리 추가
https://www.notion.so/do0ori/ef1d009e3eaa4f619dbc9050197e8b41?pvs=4
- 예시
- 예시
=> backend/DANG-1158: 산책일지 상세 API 성능 개선

backend/src/common/database/abstract.repository.ts
- 기존 영어 예외 메세지는 'Entity not found'라고 되어있었는데, 
Entity라는 표현이 적합하지 않은 것 같아 레코드로 단어를 바꾸었습니다.
- 예시
- 예시
=> backend/DANG-1166: AbstractRepository 예외 메세지 영어 -> 한글로 수정

backend/src/auth/auth.service.ts, backend/src/users/users.entity.ts, backend/test/performance/__mocks__/auth.service.ts, backend/test/performance/utils/testApp.util.ts
- index 사용 전/후 성능 비교
- token 재발급 API 응답 시간 테스트를 위해 auth service mock 추가
https://www.notion.so/do0ori/Token-API-select-option-oauthId-Index-5a2bae7e99a549a3a82156de78ad217a
https://www.notion.so/do0ori/Index-e33b1e9fbde242128aa21ea81259fa78
- 예시
- 예시
=> backend/DANG-898: Token 재발급 API에서 select option 사용 및 oauthId Index 추가

backend/src/dogs/dogs.service.ts, backend/src/users/users.service.ts
- 트랜잭션 안에서는 Promise.all을 사용해도 병렬 처리가 안되어 삭제했습니다.
https://jojoldu.tistory.com/639
- 예시
- 예시
=> backend/DANG-1175: 트랜잭션에 적용된 Promise.all 삭제

backend/src/journals/journals.service.ts, backend/src/journals/types/journal-info.type.ts
몇번째 산책일지인지 계산하기 위해 
journals_dogs에서 해당 강아지의 산책일지를 모두 가져온 뒤 
조건에 맞는 산책일지의 위치를 findIndex로 찾아오던 로직을,
getJournalIdsByDogIdAndDate 함수의 서브쿼리로 처리해 
하나의 쿼리에서 해결할 수 있도록 변경했습니다.
- 예시
- 예시
=> backend/DANG-1185:  산책일지 목록 쿼리 리팩토링

backend/rest-api/journals/journals.http, backend/src/excrements/excrements.service.ts, backend/src/excrements/fake-excrements.service.ts, backend/src/journals/dtos/create-journal.dto.ts, backend/src/journals/journals.service.ts, backend/src/journals/types/create-journal-data.type.ts, backend/src/journals/validators/WGS84.validator.ts
산책 경로(routes) , 배변량(excrements)에 사용되는 좌표 타입의 크기를 줄이기 위해
{lat: number/string, lng: number/string}[]에서
[number, number][]로 변경하였습니다
- 예시
- 예시
=> backend/DANG-1187: 좌표 타입 number 배열로 수정

backend/src/journals/journals.entity.ts, backend/src/journals/journals.service.ts, backend/src/journals/types/journal-info.type.ts, backend/test/journals.e2e-spec.ts
- `STRAIGNT_JOIN` 구문으로 더 적은 row를 반환하는 journals 테이블을 먼저 조인하도록 조인 순서를 강제하였습니다. 이를 통해 조인시 loop 수가 줄어드게 됩니다.
- user_id와 started_at을 함께 인덱싱하는 복합 인덱스를 추가하였습니다. 인덱스 스캔으로만 조건을 검사할 수 있어 속도가 빨라집니다.
이를 통해 cost를 457 -> 85.4로 약 81% 개선했습니다.
성능 개선 문서 : https://www.notion.so/do0ori/3b142e13e4e9402ea138ce2a34db4f19
블로그 링크 1: https://velog.io/@anna951/MySQL-TypeORM-%EC%BF%BC%EB%A6%AC-%ED%8A%9C%EB%8B%9D-1-%EC%A1%B0%EC%9D%B8-%EC%88%9C%EC%84%9C-%EB%B3%80%EA%B2%BD%ED%95%98%EA%B8%B0
블로그 링크 2: https://velog.io/@anna951/MySQL-TypeORM-%EC%BF%BC%EB%A6%AC-%ED%8A%9C%EB%8B%9D-2-%EB%B3%B5%ED%95%A9-%EC%9D%B8%EB%8D%B1%EC%8A%A4-%EC%B6%94%EA%B0%80%ED%95%98%EA%B8%B0
- 예시
- 예시
- if-else는 컴파일 시 처리가 되어 재컴파일 없이 수정 할 수 …
=> backend/DANG-1184: findUserDogJournalsByDate 쿼리 성능 개선

frontend/src/pages/Journals/CreateForm.tsx
- 사용자가 업로드한 이미지 파일의 확장자를 가져올 때 file 객체의 type필드를 파싱하지 않아  image/[파일타입]의 형식으로 저장되어
presignedUrl 발급요청에 실패하는 버그가 있어
/를 기준으로 split 해서 확장자만 가져올 수 있게 수정했습니다
혹시 type에서 가져오지 못하는 경우 파일 이름에서 가져올 수 있도록 예외처리 하였습니다
- 예시
- 예시
=> frontend/DANG-1198: 이미지 파일 확장자를 image/[파일타입]으로 가져오는 문제 수정

frontend/src/api/journal.ts, frontend/src/constants/keys.ts, frontend/src/hooks/useJournal.ts, frontend/src/pages/Journals/CreateForm.tsx, frontend/src/pages/Journals/Detail.tsx, frontend/src/pages/Walk.tsx, frontend/src/store/index.ts, frontend/src/store/walkStore.ts
- 산책일지 생성 수정 상세정보 api 컬럼명 수정에 따른 frontend 변수명 수정
- useJournal react-query로 리팩토링
- 상세정보 수정시 image 타입 수정 추가
- 상세정보 수정 후 해당 상세정보 queryKey 무효화하여 새로운 data fetching
- 예시
- 예시
=> frontend/DANG-1200: 일지 생성,수정,상세정보 api 컬럼명 변경에 따른 리팩토링

frontend/src/hooks/useGeolocation.ts, frontend/src/pages/Walk.tsx, frontend/src/store/walkStore.ts
- setRoutes가 콜백 함수를 사용하도록 변경
- setRoutes가 프로미스를 반환하고, stopWalk에서 이를 await로 받도록 변경
- 예시
- 예시
=> frontend/DANG-1206: 비동기 문제로 알고리즘이 적용된 경로가 저장되지 않는 문제 수정

frontend/src/hooks/useGeolocation.ts, frontend/src/pages/Walk.tsx
> ## 작업 내용 (Content)
- stopGeo 함수와 requestWalkStop 함수를 Promise.allSettled로 병렬 실행
- stopGeo 함수가 실패하더라도, 산책 중지 요청은 보내야 하기에 allSettled를 사용했음
- stopGeo에서 applyRDP 함수 실패시 이전 경로를 저장하도록 변경
- 예시
- 예시
=> frontend/DANG-1208: 산책 중지 시 연관 없는 비동기 작업 Promise.allSettled로 병렬 처리

backend/src/journals/journals.service.ts
- 테스트 환경에서 routes가 지워지고, 백업 데이터와 최신 데이터 사이 갭이 생겨 그 사이에 있던 산책일지 조회시 JSON.parse의 인자로 빈 데이터가 들어가서 발생한 에러였다.
- 데이터 유무를 확인하는 예외처리 로직을 추가했다.
- 사실 산책일지 생성시 데이터가 없어도 "", [] 등 디폴트로 비어있는 값이 할당되어 실제로는 이러한 상황은 발생하면 안된다. 하지만 테스트 환경에서는 빈번하게 발생할 수 있을 것 같고, 실제 환경에서도 혹시 모를 경우가 있으니 추가했다.
- 예시
- 예시
=> backend/DANG-1213: unexpected end of JSON에러 fix

backend/src/journals/journals.controller.ts, backend/src/journals/journals.service.ts
- 기존 쿼리에 해당 조건이 누락되어 있어 추가했습니다.
- 추후 강아지 공유 기능이 생긴다면, user_id 조건을 빼고 dog_id로만 조회하고, 산책일지 조회 페이지에 산책자가 누구인지 넣는 게 좀 더 사용자 입장에서 편할 것 같다는 생각도 들었습니다. 
- 예시
- 예시
=> backend/DANG-1211: 산책일지 목록 조회 쿼리에 현재 유저의 user_id인지 확인하는 Where 조건 추가

backend/server/Dockerfile
- 앞선 티켓에서 husky를 dev dependency로 변경했었음
- ci 단계에서 자동으로 npm prepare 명령어가 돌아가서 빌드 오류 발생
- npm ci의 옵션으로 --ignore-scripts를 주어 에러 방지
- 예시
- 예시
=> backend/DANG-1216:  prod 빌드 시 prepare 명령어 동작하지 않게 변경

backend/.husky/pre-push
- 원격에 푸시되지 않은 브랜치에 대한 분기 처리가 안되어있어 새 브랜치를 푸시할 때 오류 발생
- 원격에 없는 경우에 대한 분기 처리
- 예시
- 예시
=> backend/DANG-1217: git hook 원격에 없는 브랜치일 경우 분기 처리

backend/weather-api-module/package-lock.json, backend/weather-api-module/package.json, backend/weather-api-module/src/data-store.ts, backend/weather-api-module/src/http-client.ts, backend/weather-api-module/src/parse-data.ts, backend/weather-api-module/src/public-weather-error.ts, backend/weather-api-module/src/urlBuilder.ts, backend/weather-api-module/src/util.ts, backend/weather-api-module/src/weather-service.ts, backend/weather-api-module/src/weather-type.ts, backend/weather-api-module/src/xml-util.ts
한시간 단위로 제공되는 실제 관측 데이터를 가져와 저장하는 로직을 구현했습니다.
- 10분단위인줄 알았는데 한시간 단위로 제공되어 10분 단위로 쪼개서 저장하던 로직을 없애고 한시간 단위로 통일
- 코드 중복을 없애기 위해 parse라는 하나의 인터페이스로 두 가지 데이터에 대한 파싱을 할 수 있도록 구현
- 예시
- 예시
=> backend/DANG-1228: 한시간 단위 날씨 실황 데이터 저장 로직 구현

backend/server/src/common/database/database.module.ts, backend/server/src/const/cache-const.ts, backend/server/src/dogs/dogs.service.ts, backend/server/src/journals/journals.service.ts, backend/server/src/statistics/statistics.service.ts
1. 누락된 이벤트 추가
- 기존에는 산책일지 생성 시에만 캐시를 업데이트 하게 되어있어서 산책일지 삭제, 강아지 생성/수정/삭제시에 DB와 캐시사이 불일치 문제가 발생했습니다
- 누락된 이벤트를 추가했습니다
2. 이벤트 수신시 캐시를 업데이트하는 방식에서 캐시를 무효화 하는 방식으로 수정
- 배경 : 산책일지 삭제시, 강아지 두 마리 이상을 산책시킨 산책일지를 삭제했을 때 빈번하게 캐시가 업데이트 되지 않은 상태로 남아있는 버그 발생
- 원인 : 트랜잭션이 끝나기 전에 이벤트 수신
- 이벤트 수신 로그만 COMMIT 이전에 찍히고 실제 데이터를 가져오는 쿼리는 COMMIT 이후에 찍히고 있었지만, 미묘한 타이밍 문제로 트랜잭션의 변경사항이 반영되기 전 데이터를 가져오는 것으로 보임
- 강아지가 두마리 이상일 때 더 많은 데이터를 조작하기에 자주 데이터 불일치가 발생하는 것으로 추정됨
- 이를 해결하기 위해 이벤트 수신시 캐시를 삭제하고, 다시 홈 화면에 접속했을 때 데이터를 가져오도록 데이터의 fetch 타이밍을 뒤로 미루는 방식을 사용하도록 변경
- setImmediate를 사용하는 방법보다 이 방법이 좀 더 직관적이고 버그 가능성이 낮은 것 같아 선택했습니다
- 예시
- 예시
이에 따라 코드가 실행되는 순간에 실행이 결정되는 if …
=> backend/DANG-1260: 홈 화면 statistics api 캐시 불일치 문제 수정

.github/workflows/update-swagger.yml
- updateSwagger job이 실행될 때 403 error가 발생해서 실패하는 현상이 발생함.
- 이를 해결하기 위해 workflow 파일에 permission 관련 코드 추가
https://www.notion.so/do0ori/updateSwaggger-workflow-13f8ad358684802ba434d21096044a72
- 예시
- 예시
=> infra/DANG-1266: updateSwaggger workflow 권한 문제 해결

.github/workflows/change_ticket_status_done.yaml, .github/workflows/link_pr_to_ticket.yaml, .github/workflows/pr_labeler_validator.yaml
- PR event와 관련된 workflow 파일들에서 swagger-ui-updates에서의 event는 무시하도록 수정
https://www.notion.so/do0ori/workflow-swagger-ui-updates-branch-event-13f8ad358684807aa110c19a60760a98
- 예시
- 예시
=> infra/DANG-1267: workflow에서 swagger-ui-updates branch에서의 event는 무시하도록 수정

backend/server/src/app.module.ts, backend/server/src/auth/auth.service.ts, backend/server/src/auth/guards/auth.guard.ts, backend/server/src/auth/guards/oauth-data.guard.ts, backend/server/src/auth/guards/refresh-token.guard.ts, backend/server/src/auth/interceptors/cookie.interceptor.ts, backend/server/src/common/database/typeorm.repository.ts, backend/server/src/common/filters/all-exceptions.filter.ts, backend/server/src/common/interceptors/logging.interceptor.ts, backend/server/src/dogs/dogs.service.ts, backend/server/src/dogs/guards/auth-dog.guard.ts, backend/server/src/journals/guards/auth-journal.guard.ts, backend/server/src/today-walk-time/today-walk-time.service.ts, backend/server/src/walk/guards/auth-dogs.guard.ts
- 전역 예외 처리를 추가해 예외 로깅 중앙화
- 시스템 외적인 요인으로 발생하는 오류는 로그 레벨을 `warn`으로 설정하고, 복구 불가능한 시스템 오류는 `error`로 설정.
- 로그에는 cause 정보를 포함해 자세한 정보 제공, response는 statusCode와 message만 반환.
- `WinstonLoggerService`를 사용한 로깅 제거 -> throw를 던지면 exception filter가 알아서 logging을 찍어준다.
https://www.notion.so/do0ori/1-error-logging-2ee24d4afe1f4d23bb6b115d3eb15912
- 외부 API를 사용하는 로직에 대해서는 작업을 하지 못함.
- 예시
- 예시
=> backend/DANG-862: error logging 중앙화

backend/server/src/shared/logger/console-logger.ts, backend/server/src/shared/utils/ansi.util.ts, backend/server/test/test-utils.ts, backend/weather-api-module/src/logger/winston-logger.ts
코드 리팩토링 및 의존성 경로 수정, 타입 명시 추가
주요 변경사항:
1. `console-logger.ts` 파일에서 의존성 경로 수정 및 타입 명시 추가
2. `test-utils.ts` 파일에서 의존성 경로 수정 및 불필요한 import 제거
3. `typeorm` 관련 초기화 코드 추가
4. `MockOauthService` 및 `MockS3Service` 경로 수정
- 예시
- 예시
=> backend/DANG-1275: Logging 타입 명시 추가

.github/script/run_backend.sh, .github/script/test_run_backend.sh
Health check 실패 시 원인 파악을 위해 ec2에 접속해 docker container의 log를 확인하는 번거로움을 해결하기 위해 실패한 컨테이너의 최신 로그를 가져오는 기능을 추가했습니다.
---
```
Docker Operations
when health check fails
✓ should fail and display container logs (2739 ms)
Output:
[DEBUG] Target Container Image: test-repo/test-image:test-tag
[DEBUG] Environment File Path: /tmp/test/test.env.prod
[INFO] Deployment arguments validated.
[INFO] Authenticating with AWS ECR...
[MOCK] Docker login executed
[SUCCESS] Successfully authenticated with AWS ECR
[INFO] Checking deployment status...
[INFO] No active deployment found - Initiating Blue deployment...
[INFO] Starting deployment for dangdang-api-blue on port 3032...
[INFO] Cleaning up container: dangdang-api-blue
[MOCK] Docker stop executed
[MOCK] Docker rm executed
[MOCK] Docker pull executed
[INFO] …
```
=> infra/DANG-1280: run_backend.sh에 health check 실패 시 컨테이너 로그를 추출해 출력하는 기능 추가

.github/workflows/change_ticket_status_done.yaml
- 기존의 `branches-ignore` 옵션은 base 브랜치를 기준으로 동작하여 의도한대로 소스 브랜치(head)가 제외되지 않음
- 소스 브랜치 제외를 위해 `github.head_ref`를 이용한 명시적 조건 추가
- 불필요한 옵션 (`branches-ignore`) 제거
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore
- https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs?utm_source=chatgpt.com#github-context
- 예시
- 예시
=> infra/DANG-1282: 소스 브랜치가 'swagger-ui-updates'일 때 workflow 실행되지 않도록 수정
