dangdangwalk/dangdang-walk

README.md
backend/.husky/pre-commit
backend/package-lock.json
backend/package.json
backend/src/common/interceptor/prometheus.interceptor.ts
frontend/.husky/pre-commit
frontend/package-lock.json
frontend/package.json

- git hook 추가
- husky 및 lint-staged 설정
- pre-commit git hook script 작성
- branch 명이 프로젝트의 naming convention을 따르는지 검사
- commit message 작성 전에 lint-staged로 linter와 formatter 적용
- README.md에 git hook 관련 설명 추가
- 예시
- 예시

Backend/dang 3: Git hook 추가

---

frontend/Dockerfile
frontend/next.config.mjs
frontend/package-lock.json
frontend/package.json

주요 변경 사항
- 멀티스테이지 빌드를 사용하기 위한 빌드, 배포 이미지를 Dockerfile 스크립트를 작성했습니다
- next.config.mjs에 standalone 설정 추가 및 reactStricMode를 true 설정을 추가했습니다.
- Husky 의존성 라이브러리를 수정하였습니다.
- https://www.notion.so/do0ori/FrontEnd-Dockerfile-9f1cc4a41c68492996ab4604d7489dc8?pvs=4
- 예시
- 예시

Backend/dang 55 FrontEnd Dockerfile 작성하기

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/page.test.tsx
frontend/vitest.config.ts

- Vitest 설정
- 테스트용 테스트 추가
- https://www.notion.so/do0ori/Vitest-75f9c984d3194932b49ce53e3a6d967f?pvs=4
- 예시
- 예시

Frontend/dang 51: Vitest 설정

---

README.md
backend/.eslintrc.js

Backend/dang 59 NestJS DB 에러와 Lint 에러 해결하기

---

.github/labeler-config.yml
.github/workflows/labeler.yml

Backend/dang 59 NestJS DB 에러와 Lint 에러 해결하기
- 예시
- 예시

Backend/DANG-62 PR Label Action 작업하기

---

backend/package-lock.json
frontend/.husky/pre-commit
frontend/package-lock.json
frontend/package.json

- frontend 팀에서 frontend 환경 구성을 다시하는 과정에서 사라진 git hook 파일 다시 추가
- pre-commit script에서 branch 이름 규칙 검사 시 DANG- 뒤의 2자리 이상의 숫자에 대해 통과하지 못하던 에러 수정 (`\d` -> `[0-9]`)
- Windows에서 작업
https://www.notion.so/do0ori/frontend-git-hook-1-dc8ed38437094a028933589e21c9efe6
- Windows와 Mac 환경 차이에서 오는 오류는 추가적으로 수정 필요
- 이번 PR 이후 각자 환경에서 git hook을 적용해보고 오류 발생 시 보고 바람
- git hook 적용 방법 및 사용법은 `README.md` 참고
- 예시
- 예시

Backend/dang 60: frontend에 git hook 재추가 및 script 내부 regex 수정

---

backend/package-lock.json
backend/package.json

주요 변경 사항
swc 의존성 설치 문제로 에러가 발생했습니다. `npm i - @swc/core`를 실행으로 문제를 해결했습니다.
- 예시
- 예시

Backend/dang 78  NestJs swc 에러 문제를 해결하라

---

frontend/package-lock.json
frontend/package.json

주요 변경 사항
- husky 의존성이 devDependencies에 생성 되었지만 docker build 시 포함 되지 않아 build 실패 에러가 발생합니다.
- dev에서 dependencies로 의존성 설치 하여 문제를 해결했습니다.
- 예시
- 예시

Frontend/DANG-73 npm 의존성 문제 에러를 해결하라

---

.github/workflows/backend_deploy.yaml
.github/workflows/frontend_deploy.yaml

Backend/dang 37: GitAction ECR Build 배포 스크립트 작성하기

---

.github/workflows/backend_ci.yaml
.github/workflows/backend_deploy.yaml
.github/workflows/frontend_ci.yaml
.github/workflows/frontend_deploy.yaml

주요변경 사항
- paht 문제로 CI/CD가 정상적으로 작동하지 않아 에러를 해결했습니다.
- 예시
- 예시

Backend/dang 98: 백엔드 및 프론트엔드 CI/CD 워크플로우 트리거 수정

---

.github/workflows/backend_ci.yaml
.github/workflows/backend_deploy.yaml
.github/workflows/frontend_ci.yaml
.github/workflows/frontend_deploy.yaml

변경 내용:
- .github/workflows 디렉토리 내 CI/CD 워크플로우 파일 (backend_*.yaml, frontend_*.yaml) 에 defaults 섹션을 추가했습니다.
- defaults.run.working_directory 를 각 워크플로우에 맞게 ./backend 또는 ./frontend 로 설정하여 작업이 해당 디렉토리에서 실행되도록 합니다.
- 예시
- 예시

Backend/dang 98: Github Action 경로 문제 해결하기

---

backend/package.json
backend/src/users/users.controller.spec.ts
frontend/package.json

- git hook prettier를 적용 시 파일 수정까지 하도록 업데이트
- `users.controller` 테스트 코드에 WinstonLoggerService를 추가하여 테스트를 통과할 수 있도록 수정
https://www.notion.so/do0ori/git-hook-prettier-8b04b3484d3a46ccb36b8289f7470ef9
- 예시
- 예시

Backend/dang 97: git hook prettier 적용 시 파일 수정까지 하도록 업데이트

---

.github/workflows/backend_deploy.yaml
.github/workflows/frontend_deploy.yaml

변경 내용
- 워크플로우 명칭:
- AWS ECR Prod Deploy 에서 각 워크플로우의 기능을 명확하게 나타내도록
- AWS ECR Prod Backend Deploy (백엔드)
- AWS ECR Prod Frontend Deploy (프론트엔드) 로 변경
- 워크플로우 스크립트:
- 기존 컨테이너 이미지 빌드 스크립트에 다음과 같은 작업 추가
- 코드 체크아웃 (actions/checkout@v4 액션 사용)
- Node.js 환경 설정 (actions/setup-node@v4 액션 사용, 버전 21.2.0)
- 패키지 설치 (npm install)
- 테스트 실행 (npm run test)
- 빌드 스크립트 추가 (각 프로젝트의 스크립트 명 가정, 예: npm run build)
- 예시
- 예시

Backend/dang 101 GitHub Action 배포 에러를 해결하라

---

docs/openapi.yaml

openapi.yaml 파일의 오타 수정 (Work -> Walk)
- 예시
- 예시

docs: 오타 수정 (Work -> Walk) 일부러 제목 convention 안 지키기

---

.github/workflows/frontend_deploy.yaml

주요 변경 사항
- EC2 개인 키, 호스트 및 사용자에 대한 환경 변수 추가
- 워크플로우에 새 '배포' 작업 추가하기
- appleboy/ssh-action을 사용하여 EC2 인스턴스에 연결합니다.
- 빌드 성공 후 원격 EC2 인스턴스에서 run-frontend.sh 스크립트 실행
- https://www.notion.so/do0ori/Script-ec00b8ca5cea43b69e332e3563e8dab7?pvs=4
- 예시
- 예시

backend/DANG-103: GitHub Actions workflow 프런트엔드 배포 단계 추가하기

---

.github/workflows/frontend_deploy.yaml

변경 사항
- 워크플로우 시크릿(EC2_PUBLIC_HOST)에서 EC2 공용 호스트 참조
- SSH 개인 키 액세스를 위해 워크플로우 시크릿(EC2_SSH_PRIVTE_KEY)을 활용(환경에서 사전 노출 제거)
- Docker 이미지 빌드 최적화: 플랫폼(리눅스/암드64) 지정, 캐싱 비활성화, 이미지 이름 및 태그에 환경 변수 활용
- 리포지토리, 이미지 이름 및 태그에 대한 환경 변수를 사용하여 ECR 이미지 푸시 명확성 향상
- SSH 동작에 대한 명시적 버전(v1.0.3) 설정
- ./run-frontend.sh에 위치한 배포 스크립트 실행(로컬 실행 스크립트 가정)
- 예시
- 예시

frontend/DANG-109: 프론트엔드 GitAction 스크립트 에러 수정하라

---

.gitattributes
backend/.prettierrc
frontend/.prettierrc

- Prettier 설정 변경: 프런트엔드/백엔드 모두 `endOfLine` 설정을 `lf`에서 `auto`로 변경
- Git Attributes 설정 생성 (.gitattributes 파일 생성)
https://www.notion.so/do0ori/CRLF-ad9b68c9e9b240a1bd83a9ae7e831723?pvs=4
- 예시
- 예시

frontend/DANG-105: CRLF 문제 해결하기

---

.github/workflows/frontend_deploy.yaml

fix: frontend GitAction 조건문을 제거하라

---

backend/.prettierrc
backend/src/app.controller.spec.ts
backend/src/app.controller.ts
backend/src/app.module.ts
backend/src/app.service.ts
backend/src/common/health/health.controller.ts
backend/src/common/interceptor/prometheus.interceptor.ts
backend/src/common/logger/winstonLogger.module.ts
backend/src/common/logger/winstonLogger.service.spec.ts
backend/src/common/logger/winstonLogger.service.ts
backend/src/main.ts
backend/src/users/users.controller.spec.ts
backend/src/users/users.controller.ts
backend/src/users/users.entity.test.ts
backend/src/users/users.entity.ts
backend/src/users/users.module.ts
backend/test/app.e2e-spec.ts
backend/test/setup.ts

NestJS에서 default로 설정한대로 사용되던 prettier 설정 파일을 우리 프로젝트 환경에 맞게 업데이트
https://www.notion.so/do0ori/Backend-prettier-aa9d706b7c1b47438cdd2abcf25faaf6
- 예시
- 예시

backend/DANG-110: backend prettier 설정을 기존에 논의했던 공통 옵션으로 적용

---

.github/workflows/frontend_deploy.yaml

주요 변경 사항
빌드 태그: 커밋 SHA를 이용하여 빌드 태그 생성 (예: $GITHUB_SHA::7)
ECR 로그인: 별도의 login-ecr job 도입하여 ECR 로그인을 별도 단계로 분리 테스트 스크립트 제외: 워크플로우에서 테스트 스크립트 실행 제외 (개발자 로컬 테스트 권장) AWS 자격 증명: 워크플로우 환경변수 대신 시크릿 사용 (이전 커밋 삭제)
- 예시
- 예시

backend/DANG-112: GitAction Docker 이미지 경로 문제 수정하기

---

.github/workflows/frontend_deploy.yaml

frontend/DANG-113: GitAction Docker Image 경로 문제를 해결하라

---

.github/workflows/backend_deploy.yaml
.github/workflows/frontend_deploy.yaml

infra/Dang115: Backend ECR 빌드 에러를 해결하라

---

.github/workflows/frontend_deploy.yaml

변경 사항
- 빌드 해시: 빌드 태그 대신 커밋 SHA에서 생성된 해시값 사용 (hash)
- ECR 태그: 빌드 해시값 사용하여 이미지 태그 생성 ($REPO/$IMAGE:${{env.hash}})
- 배포 스크립트: 워크플로우 스크립트 내 직접 통합 (외부 스크립트 사용 제외)
- 예시
- 예시

infra/DANG-117: GitAction deploy 스크립트를 수정하라

---

.github/workflows/frontend_ci.yaml
.github/workflows/frontend_deploy.yaml

- https://www.notion.so/do0ori/Frontend-GitActions-c743e0c6dde24f8fa71c5fc4b368a744?pvs=4
- 예시
- 예시

frontend/DANG-119: Frontend GitActions 스크립트 리팩터링하기

---

frontend/.vscode/settings.json

VSCode에서 경로 별칭을 먼저 사용하도록 `.vscode/settings.json`에 설정 추가
https://www.notion.so/do0ori/VSCode-b0d9e22ad5ed490ebb7286e4b8d93e07?pvs=4
- 예시
- 예시

frontend/DANG-120: 경로 별칭 관련 설정

---

.github/workflows/backend_deploy.yaml
Makefile
backend/.eslintrc.js

주요 변경 사항
- ESLint와 prettierrc 충돌 문제로 플로그인을 제거하였습니다.
- 예시
- 예시

backend/DANG-113: ECR 배포 스크립트 작성 및 ESLint 에러를 해결하기

---

.github/workflows/backend_ci.yaml
.github/workflows/frontend_deploy.yaml
backend/Dockerfile

주요 변경 내용
- 사용자 엔티티 관련 테스트 코드를 작성했습니다.
- 예시
- 예시

backend/DANG-125: GitActions Docker Build 문제를 해결하라

---

frontend/src/app/api/auth/signin/components/Signin.tsx

frontend/DANG-136: 배포 테스트

---

.github/workflows/backend_ci.yaml
.github/workflows/backend_deploy.yaml
backend/src/users/users.controller.ts

infra/DANG-137: BackEnd GitActions 개선하기

---

.github/workflows/backend_deploy.yaml

infra/DANG-138: Deploy 시 기존 Docker를 삭제하는 로직을 추가하라

---

.gitignore
backend/package-lock.json
backend/package.json
backend/src/users/users.controller.ts
backend/src/users/users.entity.ts
backend/src/users/users.service.ts
backend/src/utils/hash.utils.ts

- 닉네임 uuid로 해시값 생성해서 중복 검사 후 추가하는 로직
- 소소한 오류 수정 
- 예시
- 예시

backend/DANG-128: 회원가입 로직 랜덤한 닉네임 추가

---

frontend/craco.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/tsconfig.json
frontend/tsconfig.paths.json

craco, craco-alias 설정 추가
- 예시
- 예시

frontend/DANG-148: craco, craco-alias 설정 추가

---

frontend/package-lock.json
frontend/package.json

@tanstack/react-query, @tanstack/eslint-plugin-query dependency 추가
- 예시
- 예시

frontend/DANG-150: @tanstack/react-query, @tanstack/eslint-plugin-query dependency 추가

---

frontend/package-lock.json
frontend/package.json
frontend/src/index.css
frontend/tailwind.config.js

tailwind postcss autoprefixer 추가
- 예시
- 예시

frontend/DANG-151: tailwind postcss autoprefixer 추가

---

backend/Dockerfile
frontend/Dockerfile
frontend/docker-entrypoint.sh
frontend/package-lock.json
frontend/package.json

Infra/DANG-139: 프론트엔드 새로운 환경에 Docker와 의존성 설치를 추가하라

---

.github/workflows/frontend_deploy.yaml

- Deploy 시 기존 Docker 컨테이너를 제거하고 새로운 컨테이너로 대체하도록 docker rm container를 시도했지만 정상적으로 작동하지 않은 문제로 코드를
수정했습니다.
- 예시
- 예시

infra/DANG-152: FrontEnd Deploy Docker 삭제에러를 에러를 해결하라

---

.github/workflows/backend_deploy.yaml
.github/workflows/frontend_ci.yaml
.github/workflows/frontend_deploy.yaml
backend/Dockerfile

주요 변경 사항
- 캐싱 성능 최적화를 위해 `actions/cache@v3`를 구현합니다.
- 정확한 종속성 관리를 위해 프로젝트별 `node_modules` 디렉터리를 캐시 경로로 지정합니다.
- 정확한 종속성 변경 감지를 위해 캐시 키 생성 시 `package-lock.json` 해시값을 활용합니다.
- Node.js 버전 제어를 개선하기 위해 `actions/setup-node@v3`로 업그레이드합니다.
- 컨테이너 중지 중 `docker container prune -f`를 활용하여 디스크 공간 확보.
- 이미지 정리 명령에 `-a` 플래그를 도입하여 최근 1시간 이내에 생성된 이미지를 제외한 모든 이미지를 정리합니다.
- 예시
- 예시

infra/DANG-164: 워크플로우 업데이트 (캐싱, Node.js 버전, 이미지 정리)

---

backend/src/users/users.service.ts

backend/DANG-163: hash.utils 경로 절대경로 -> 상대경로로 변경

---

frontend/src/api/http.ts

Frontend/dang 131: ㅊ

---

frontend/.eslintrc.json
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/api/http.ts
frontend/src/components/Navbar.tsx
frontend/src/pages/Home.tsx
frontend/src/pages/Profile.tsx
frontend/src/setupTests.ts

airbnb eslint config 설치
lint 명령어 설정
eslint import 관련 룰 설정
- 예시
- 예시

frontend/DANG-155: eslint-config-eslint 설치 및 lint 명령어 설정

---

frontend/.eslintrc.json
frontend/package-lock.json
frontend/package.json

airbnb package 삭제
eslint react-app 으로 설정
lint-staged husky 설치 및 설정
- 예시
- 예시

frontend/DANG-166: eslint react-app으로 설정

---

frontend/.eslintrc.json
frontend/package-lock.json
frontend/package.json

react-query eslint 설치
- 예시
- 예시

frontend/DANG-132: react-query eslint 설치

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/OAuthButton.tsx
frontend/src/constants/oauthList.ts
frontend/src/index.tsx
frontend/src/pages/Login.tsx

Oauth로그인: redirect url 연결 시켜주기
- 예시
- 예시

frontend/DANG-159: Oauth로그인: redirect url 연결 시켜주기

---

frontend/.husky/pre-commit

Next에서 React로 전환하면서 사라진 script 재추가
https://www.notion.so/do0ori/frontend-husky-setting-3a0a7040c31d42799a7bfee7c06319eb
- 예시
- 예시

frontend/DANG-175: husky pre-commit git hook script 추가

---

backend/src/auth/auth.controller.ts
backend/src/auth/auth.module.ts
backend/src/auth/auth.service.ts
backend/src/auth/google/google.controller.ts
backend/src/auth/google/google.service.ts
backend/src/auth/kakao/kakao.controller.ts
backend/src/auth/kakao/kakao.service.ts
backend/src/auth/naver/naver.controller.ts
backend/src/auth/naver/naver.service.ts
backend/src/auth/token/token.service.ts

- 주석 및 내부 logger 코드 제거
- auth.service.ts에 있던 token service를 auth 폴더 아래 token/token.service.ts로 분리
https://www.notion.so/do0ori/logger-token-service-auth-6a82f990102f4980bcaab40023137688
- 예시
- 예시

backend/DANG-182: 불필요한 코드 제거 및 token service 분리

---

backend/src/app.module.ts
backend/src/fake/fake.controller.ts
backend/src/fake/fake.module.ts

프론트엔드 개발을 위한 mock 컨트롤러 추가
- 예시
- 예시

backend/DANG-174: mock  컨트롤러 추가

---

.github/workflows/pr_labeler_validator.yaml

job level에서 조건문을 사용했더니 skip되는 현상이 발생해서 이를 보완하고자 step level로 조건문을 옮겼습니다.
- 예시
- 예시

infra/DANG-181: GitHub Actions validator skip 방지

---

backend/src/auth/auth.service.ts
backend/src/auth/google/google.controller.ts
backend/src/auth/google/google.service.ts
backend/src/auth/kakao/kakao.service.ts
backend/src/auth/naver/naver.service.ts
backend/src/auth/token/token.service.ts
backend/src/users/users.controller.ts
backend/src/users/users.entity.ts
backend/src/users/users.module.ts
backend/src/users/users.service.ts

#84 에서 DB 로직 추가
https://www.notion.so/do0ori/DB-logic-877fadad41344827bebc7fd7f31ec2b2
- 예시
- 예시

backend/DANG-177: 로그인 DB logic 추가해서 기능 완성

---

backend/package-lock.json
backend/package.json

이전 패키지.json 파일에서 @nestjs/jwt 의존성이 추가되었지만, Docker 모듈 빌드 시 모듈이 추가 되지 않아 에러가 발생 했습니다. 의존성 패키지를 dependencies로 재설치하여 에러를 해결했습니다.
- 예시
- 예시

backend/DANG-190: nestjs/jwt module 에러를 해결하라

---

backend/src/common/interceptor/serialize.interceptor.ts
backend/src/walk/interceptor/walk-command.interceptor.ts

Dto 클래스 정의에 맞춰 데이터를 변환해주는 인터셉터 정의
아래처럼 쓰면 됩니다
```
@Serialize(UserDto) //here
@Get('/:id')
async findUser(@Param('id') id: string) {
console.log('handler is running');
const user = await this.usersService.findOne(parseInt(id));
if (!user) {
throw new NotFoundException('user not found');
}
return user;
}
```
- 예시
- 예시

feat: dto 변환 인터셉터 구현

---

.github/workflows/backend_deploy.yaml

주요 변경 사항
- (사용자 정의) 포트 번호 8888에 충돌이 발생할 수 있음을 파악했습니다.
- 따라서 덜 충돌 가능성이 높은 포트 번호 3031로 변경하여 서비스 안정성을 향상 시킵니다.
- 예시
- 예시

infra/DANG-198: Backend 서비스 포트 변경하기

---

frontend/.prettierrc

Prettier 설정의 endOfLine 값을 auto로 변경
https://www.notion.so/do0ori/Prettier-27882f89aa724d148909a0f18c87d25d?pvs=4
- 예시
- 예시

frontend/DANG-194: Prettier 설정 변경

---

frontend/src/api/http.ts
frontend/src/api/weather.api.ts
frontend/src/models/weather.model.ts
frontend/src/pages/Home.tsx
frontend/src/utils/date.ts

날씨 api 설정
날씨 model 추가
- 예시
- 예시

frontend/DANG-172: 날씨 api 설정

---

backend/src/app.module.ts
backend/src/dog/dog.module.ts
backend/src/dog/dog.service.ts
backend/src/dog/dogs.entity.ts
backend/src/entity/excrements.entity.ts
backend/src/entity/userDogs.entity.ts
backend/src/entity/walkDogs.entity.ts
backend/src/fake/fake.controller.ts
backend/src/users/users.entity.ts
backend/src/walk/dtos/walk-command.dto.ts
backend/src/walk/walk.controller.ts
backend/src/walk/walk.module.ts
backend/src/walk/walk.service.ts

backend/DANG-191: 산책 시작/중지 api 구현

---

frontend/package.json

lint 스크립트 수정
https://www.notion.so/do0ori/lint-25262dbc6ec54a0cb1918f3e448dd98a?pvs=4
- 예시
- 예시

frontend/DANG-199: 윈도우에서의 lint 스크립트 경로 문제 해결

---

backend/src/dog/dto/dog-statistic.dto.ts

주요 변경 사항
- `statistics` Get 요청 시 강아지 산책 체크 사항 정보를 응답합니다.
- 예시
- 예시

backend/DANG-210: 강아지 주별로 산책 체크 사항 응답 객체 생성하기

---

frontend/src/vitest.test.ts

Vitest의 정상 작동을 확인하고 CI 테스트 통과를 위해 간단한 테스트를 작성
https://www.notion.so/do0ori/a1fb372adafd4d998983fad2ee9a7d41?pvs=4
- 예시
- 예시

frontend/DANG-211: 테스트용 테스트 작성

---

backend/src/main.ts

- origin은 *(wildcard) 대신 client origin으로 수정
- credientials option true
https://www.notion.so/do0ori/main-ts-cors-c32c37bfff6f41c8b4f61fec14a6abdd
- 예시
- 예시

backend/DANG-216: main.ts cors 설정 추가

---

frontend/src/components/OAuthButton.tsx

frontend/DANG-217: 구글 oauth url 수정

---

frontend/src/index.tsx
frontend/src/pages/Health.tsx

백엔드 연결 테스트 페이지와 버튼 구현
버튼을 누르면 백엔드의 `/health` API에 GET 요청을 보냄
https://www.notion.so/do0ori/268d16995940438cbe6a2557f4be6410?pvs=4
이전 Next.js에서 구현한 페이지가 유실되어서 다시 구현
- 예시
- 예시

frontend/DANG-212: 백엔드 연결 테스트 페이지 구현

---

frontend/src/api/auth.ts

frontend/DANG-219: auth.ts 불필요한 코드 정리

---

frontend/tsconfig.json

`tsconfig`에 `noUncheckedIndexedAccess` 설정 추가
https://www.notion.so/do0ori/4e5ba2c6b7ac4e5e821a341426fcd3ad?pvs=4
- 예시
- 예시

frontend/DANG-184: 타입스크립트 설정

---

frontend/.vscode/settings.json

Next.js → React로 마이그레이션 과정 중에 유실된 경로 별칭을 설정함
프로젝트 단위에서 VSCode 설정을 지정
https://www.notion.so/do0ori/VSCode-8162847c2dcd46bdbe556d46ed4ed7bd?pvs=4
- 예시
- 예시

frontend/DANG-221: 경로 별칭 관련 설정

---

frontend/src/api/auth.ts
frontend/src/hooks/useAuth.ts
frontend/src/pages/Profile.tsx

로그인 request body에 redirectURI 넣어주기
- 예시
- 예시

frontend/DANG-223: 로그인 request body에 redirectURI 넣어주기

---

frontend/src/pages/Health.tsx

주요 변경 사항
- 로컬 개발 환경과 배포 환경에서 서로 다른 백엔드 서비스 주소를 사용할 수 있도록 유연성을 높입니다.
- 환경 변수를 사용하면 코드 변경 없이 환경 설정만으로 다른 환경에 적용할 수 있습니다.
- 예시
- 예시

frontend/DANG-255: 백엔드 서비스 주소를 환경 변수 사용으로 변경

---

backend/src/auth/auth.module.ts

auth module에서 AuthGuard를 global로 추가해서 의존성 문제를 해결했다.
https://www.notion.so/do0ori/AuthGuard-e77b1dccaf5147b1a3328e67771bdf6a
auth가 필요 없거나 다른 guard를 사용해야 하는 endpoint에 대해서는 어떻게 처리할지 알아봐야 할 것 같다.
- 예시
- 예시

backend/DANG-235: AuthGuard를 global로 추가해서 의존성 해결

---

backend/src/dogs/dogs.controller.ts
backend/src/dogs/dogs.service.ts
backend/src/users/users.service.ts

- 실제 req 객체에 담긴 userId를 사용하도록 변경하였습니다
- 하드코딩 되어있던 getDogList 함수를 구현하였습니다
- 예시
- 예시

backend/DANG-229: req.user 사용하도록 변경, getDogList 구현

---

backend/src/main.ts

`string`을 `string[]`으로 바꾸고 Authorization header를 추가했습니다.
https://www.notion.so/do0ori/cors-header-authorization-0af77410d1ec45519ff859dffca800cd
- 예시
- 예시

backend/DANG-250: cors allowedHeaders에 Authorization 추가

---

frontend/src/api/auth.ts
frontend/src/hooks/useAuth.ts
frontend/src/pages/Login.tsx
frontend/src/pages/Profile.tsx
frontend/src/store/authStore.ts

frontend/DANG-253: 로그인, 로그아웃 기능 추가

---

frontend/src/App.tsx
frontend/src/api/queryClient.ts
frontend/src/types/common.ts

frontend/DANG-254: react-query 설정 추가

---

backend/src/app.module.ts
backend/src/excrements/excrements.module.ts
backend/src/excrements/excrements.service.ts
backend/src/journal/journal.module.ts
backend/src/journals/journals.controller.ts
backend/src/journals/journals.module.ts
backend/src/journals/journals.service.ts
backend/src/walk-log-photos/walk-log-photos.module.ts
backend/src/walk-log-photos/walk-log-photos.service.ts

산책일지 저장에 필요한 모듈들 생성하고 컨트롤러, 서비스 추가
journals, excrements, walkPhotos
- 예시
- 예시

Backend/dang 236: journals, excrements, walkPhotos 모듈 추가

---

frontend/.eslintrc.json
frontend/src/hooks/useWeather.ts
frontend/src/utils/weather.util.ts

frontend/DANG-255: 린트에러 수정

---

frontend/tailwind.config.js

Tailwind의 테마 colors에 primary 추가
https://www.notion.so/do0ori/Tailwind-b79dfe6168bb47a48e27c49b2ebc0065?pvs=4
- 예시
- 예시

frontend/DANG-44: Tailwind 테마 설정

---

backend/src/common/health/health.controller.ts

backend/DANG-265: Health Controller에 Logger를 추가하라

---

frontend/tailwind.config.js

Tailwind 테마에서 색상에 `primary-foreground`, `secondary`, `secondary-foreground` 추가
https://www.notion.so/do0ori/8f263069037d4bbb9dc541841ccb766d?pvs=4
- 예시
- 예시

frontend/DANG-264: Tailwind 테마에 색상 추가

---

frontend/.eslintrc.json
frontend/src/api/map.api.ts
frontend/src/components/home/WeatherInfo.tsx
frontend/src/hooks/useWeather.ts

카카오 api cors 에러수정
promise promiseAll로 수정
- 예시
- 예시

frontend/DANG-240: 카카오 api cors 에러수정

---

frontend/tailwind.config.js

Tailwind 테마에서 16진수 색상의 값을 소문자로 변경 (`#FF9900` → `#ff9900`)
가독성을 위해 소문자를 사용
https://www.notion.so/do0ori/Tailwind-16-59966d9738ce4116ab1a96e74b2c4c2d?pvs=4
- 예시
- 예시

frontend/DANG-266: Tailwind 테마에서 16진수 색상의 값을 소문자로 변경

---

frontend/components.json
frontend/package-lock.json
frontend/package.json
frontend/src/utils/tailwind-class.ts

shadcn/ui를 사용하기 위한 환경을 설정
- 패키지 추가 (`class-variance-authority clsx tailwind-merge @radix-ui/react-slot`)
- 유틸 함수 구현 (`utils/tailwind-class.ts`)
- 설정 파일 생성 (`components.json`)
https://www.notion.so/do0ori/shadcn-ui-c8b1f7b3444e4eb490b80e1f06d7fd5e?pvs=4
- 예시
- 예시

frontend/DANG-267: shadcn/ui 환경 설정

---

frontend/.vscode/settings.json

cva 내부에서 Tailwind 자동 완성을 활성화하기 위해 VSCode 설정 추가
https://www.notion.so/do0ori/VSCode-995ad8a20f4347d78793ffddca9ca524?pvs=4
- 예시
- 예시

frontend/DANG-273: VSCode 설정 추가

---

backend/src/dogs/dogs.controller.ts
backend/src/dogs/dogs.service.ts
backend/src/dogs/dto/dog-statistic.dto.ts

회의한대로 좀 더 알아보기 쉬운 이름으로 수정
권장 산책량 : amountOfWalk -> recommendedDailyWalkAmount
하루 산책량 : walkTime -> dailyWalkAmouont
주간 산책일자: weeklyWalkCheck -> weeklyWalks
- 예시
- 예시

backend/DANG-274: dogs/statistics api DTO 속성명 수정

---

backend/src/dogs/dogs.entity.ts

breed_id가 One to One으로 설정되어 있어 유니크 조건이 적용됨
Many to One으로 바꿈
- 예시
- 예시

backend/DANG-275:  Dogs 엔티티에서 breed_id 1대1 관계에서 다대1관계로 수정

---

frontend/src/components/home/WeatherInfo.tsx
frontend/src/index.css
frontend/src/pages/Home.tsx
frontend/tailwind.config.js

날씨 정보 스타일 추가
공통font 설정
tailwind color 추가
- 예시
- 예시

frontend/DANG-255: 날씨 정보 스타일 추가

---

frontend/tailwind.config.js

- Tailwind 테마에서 기존 색상을 재정의하던 것을 확장으로 변경
- Tailwind 테마에서 미사용 색상 제거 (`black`, `zinc`)
https://www.notion.so/do0ori/Tailwind-9c3a9477958e4951acbb73cb027c02bb?pvs=4
- 예시
- 예시

frontend/DANG-283: 잘못된 Tailwind 테마 해결

---

backend/src/auth/auth.controller.ts
backend/src/auth/auth.service.ts

우리 서비스를 이용하는 사용자를 user로 하기로 비즈니스 용어에서 정했기 때문에 이에 맞게 수정
https://www.notion.so/do0ori/auth-is-member-auth-is-user-f34efc0150f34212a0ee28311eab24b4
- 예시
- 예시

backend/DANG-288: member를 user로 수정

---

backend/Dockerfile
frontend/Dockerfile

헬스 체크 명령어 수정
- docker file에서는 헬스 체크가 5초마다 실행됩니다. 헬스 체크에 로그 기록에 5초마다 기록이 되어 보기 불편함으로 이번 커밋에서는 5초 실행하는 명령어를 수정했습니다.
타임존 설정
- 프로덕션 이미지를 위한 node:18-alpine 베이스 이미지에 서울 표준시 (Asia/Seoul)을 설정했습니다. 이는 컨테이너 실행 시 시스템 시간을 한국 시간대로 설정합니다.
- https://www.notion.so/do0ori/Docker-66bff30f4c32497cb15fb33c3981c7d1?pvs=4
- 예시
- 예시

infra/DANG-293: 헬스 체크 명령 간소화, 백엔드 이미지 최적화 및 타임존 설정

---

.github/workflows/backend_deploy.yaml
.github/workflows/frontend_deploy.yaml

infra/DANG-294: && 문법 에러를 해결하기

---

.github/workflows/backend_deploy.yaml
.github/workflows/frontend_deploy.yaml
docker-compose-dev.yml
frontend/Dockerfile

infra/DANG-295: Frontend Dockerfile을 스테이지별로 나누기

---

.github/workflows/backend_deploy.yaml
.github/workflows/frontend_deploy.yaml

infra/DANG-296: GitActions 컨테이너 삭제 명령어 수정 하기

---

frontend/src/components/Navbar.tsx
frontend/src/components/home/DogCard.tsx

네브바 백그라운드 추가
프로그레스바 위치 수정
- 예시
- 예시

frontend/DANG-297: 홈화면 스타일 수정

---

.github/workflows/backend_deploy.yaml
.github/workflows/frontend_deploy.yaml
frontend/Dockerfile

- https://www.notion.so/do0ori/bbaa16858be845c4b845cba4de510f73?pvs=4
- 예시
- 예시

infra/DANG-300: 프론트엔드 이미지 빌드 단계 추가 및 최적화 및 설정 파일 경로 단축

---

.github/workflows/backend_deploy.yaml
backend/src/common/health/health.controller.ts

infra/DANG-233: Docker 컨테이너 두 대 생성하도록 스크립트를 작성하라

---

frontend/src/App.tsx
frontend/src/api/http.ts
frontend/src/components/home/DogCard.tsx
frontend/src/components/home/Progressbar.tsx
frontend/src/hooks/useWeather.ts
frontend/src/index.css
frontend/src/utils/geo.ts

geouitl에 현재 위치 가져오는 함수 추가
usehook 내부에 위치가져오는 로직 수정
root css 수정, 프로그래스바 css 수정
배포시 console 삭제
- 예시
- 예시

frontend/DANG-299: 위도경도가져올떄 생기는 타이밍 문제 해결

---

.github/workflows/backend_deploy.yaml

infra/DANG-310: EC2 Docker 배포 시 컨테이너 삭제하도록 스크립트 작성하기

---

frontend/src/App.tsx
frontend/src/components/LoginAlertModal.tsx
frontend/src/components/LoginModal.tsx
frontend/src/components/Navbar.tsx
frontend/src/components/OAuthButton.tsx
frontend/src/index.tsx
frontend/src/pages/Home.tsx
frontend/src/pages/Profile.tsx
frontend/src/store/modalStateStore.ts
frontend/tailwind.config.js
frontend/tsconfig.json

Login 페이지를 LoginModal로 변경
- 예시
- 예시

frontend/DANG-312: Login 페이지를 LoginModal로 변경

---

docker-compose-dev.yml
nginx/Dockerfile
nginx/nginx.conf

infra/DANG-311: Nginx Docker file 생성하기

---

.github/workflows/backend_deploy.yaml

- 이전에는 컨테이너 이름을 정의하는 변수 (CONTAINER_NAME1, CONTAINER_NAME2)를 사용하지 않고 직접 이미지 이름을 사용했습니다.
- 이번 커밋을 통해 컨테이너 이름을 별도로 관리하는 변수를 도입했습니다.
- 이를 통해 컨테이너 이름을 더욱 명확하게 식별할 수 있습니다.
- 예시
- 예시

infra/DANG-320: 백엔드 배포 스크립트 개선 및 컨테이너 이름 설정

---

.github/workflows/frontend_deploy.yaml
frontend/src/vitest.test.ts

infra/DANG-325: Docker container 명령어를 수정하라

---

frontend/src/vitest.test.ts

frontend/DANG-327: Frontend 배포 위한 테스트 코드 작성하기

---

.github/workflows/frontend_deploy.yaml
frontend/src/vitest.test.ts

주요 변경 사항
- 배포 스크립트에서 docker run 명령을 수정하여 --env-file .env 옵션을 추가했습니다.
- frontend/src/vitest.test.ts 파일에 새로운 테스트 코드를 추가했습니다.
- 예시
- 예시

frontend/DANG-330: 프론트 엔드 배포 및 테스트 코드 추가

---

.dockerignore
.github/workflows/frontend_deploy.yaml
frontend/Dockerfile

infra/DANG-331: EC2 Docker 배포 시 env 파일을 생성 및 이미지 빌드 최적화

---

backend/src/app.module.ts
backend/src/common/interceptor/logging.interceptor.ts
backend/src/common/logger/winstonLogger.service.ts

- 형식 :
[REQUEST] [method | url | ip | userId] requestId 
[RESPONSE] [method | url | ip | statusCode | 요청 처리 시간(ms)] requestId
- debug 모드일 시 reponse의 payload도 기록
- 예시
- 예시

backend/DANG-306:  REQUEST/RESPONSE 기록하는 로그 인터셉터 구현

---

.github/workflows/frontend_deploy.yaml
frontend/Dockerfile

주요 변경 사항
- Dockerfile에 NODE_ENV=prod 참조하도록 build 단계에 참조 하였습니다.
- Secrets Manager 에서 가져온 시크릿 값을 .env.prod 파일에 저장하도록 변경되었습니다.
- https://www.notion.so/do0ori/Frontend-Dockerfile-prod-502a1ed3fab3427ab26413deba8fb558?pvs=4
- 예시
- 예시

infra/DANG-332: 프론트엔드 이미지 Build 단계에 NODE_ENV 추가 및 .env 파일 참조하도록 수정하기

---

frontend/src/App.tsx
frontend/src/pages/Home.tsx

Home , LoginAlertModal 관련 왼쪽 여백 처리
body width:100%
- 예시
- 예시

frontend/DANG-339: Home , LoginAlertModal 관련 왼쪽 여백 처리

---

frontend/src/App.tsx
frontend/src/components/LoginAlertModal.tsx
frontend/src/components/LoginBottomSheet.tsx
frontend/src/components/OAuthButton.tsx
frontend/src/store/loginBottomSheetStore.ts

frontend/DANG-343: isJoinning 상태 삭제

---

frontend/src/components/common/CheckBox.tsx
frontend/src/pages/Join.tsx

frontend/DANG-345: CheckBox 공통 컴포넌트 생성

---

.github/workflows/link_pr_to_ticket.yaml

기존에는 PR 시 PR url만 ticket에 추가했는데 Status도 Reviewing으로 업데이트하도록 코드를 추가했다.
https://www.notion.so/do0ori/PR-Notion-Reviewing-d2e67a5417fd4db18992833f98bb026d
- 예시
- 예시

infra/DANG-329: PR 시 Status를 Reviewing으로 업데이트하도록 자동화 코드 추가

---

backend/src/breed/breed.module.ts
backend/src/breed/breed.repository.ts
backend/src/breed/breed.service.ts
backend/src/common/database/abstract.repository.ts
backend/src/common/database/database.module.ts
backend/src/daily-walk-time/daily-walk-time.module.ts
backend/src/daily-walk-time/daily-walk-time.repository.ts
backend/src/daily-walk-time/daily-walk-time.service.ts
backend/src/dog-walk-day/dog-walk-day.module.ts
backend/src/dog-walk-day/dog-walk-day.repository.ts
backend/src/dog-walk-day/dog-walk-day.service.ts
backend/src/dogs/dogs.controller.ts
backend/src/dogs/dogs.module.ts
backend/src/dogs/dogs.repository.ts
backend/src/dogs/dogs.service.ts

기존 코드를 추상 DB 클래스 사용하게 변경하였습니다.
Dogs 모듈 관련 버그 고칠 게 있어서 Users 변경 전에 머지합니다.
- 예시
- 예시

backend/DANG-334: 기존 코드 추상 DB 클래스 사용하도록 변경 (User 제외)

---

.github/workflows/frontend_deploy.yaml
frontend/src/vitest.test.ts

infra/DANG-323: Github Action Build 시 env.file을 생성하도록 스크립트 작성하라

---

.github/workflows/backend_deploy.yaml
.github/workflows/frontend_deploy.yaml
backend/src/dogs/dogs.spec.ts
frontend/src/vitest.test.ts

.env.prod Build 시 내용일 겹쳐서 생성되어 폴더 별로 다르게 생성하도록
분리했습니다.
- 예시
- 예시

infra/DANG-234: env 파일 경로를 각 폴더별로 분리하라

---

.github/workflows/backend_deploy.yaml
.github/workflows/frontend_deploy.yaml
backend/src/dog-walk-day/dog-walk-day.spec.ts
frontend/src/vitest.test.ts

github action build 시 폴더가 이미 존재하면 build 실패로 조건문을
추가했습니다.
- 예시
- 예시

infra/DANG-350: 폴더가 존재하지 않으면 생성하도록 스크립트를 작성해라

---

.github/workflows/backend_deploy.yaml
.github/workflows/frontend_deploy.yaml
backend/src/dog-walk-day/dog-walk-day.spec.ts
frontend/src/vitest.test.ts

infra/DANG-352: 기존 파일에 append가 아닌 overwrite 하도록 shellscript를 작성하라

---

frontend/src/api/weather.ts

infra/DANG-359: weather 정보 토큰 정보 이식 확인하기

---

backend/src/entity/excrements.entity.ts
backend/src/entity/walk-log-photos.entity.ts
backend/src/journals/journals-dogs.entity.ts
backend/src/journals/journals.entity.ts
backend/src/journals/journals.module.ts
backend/src/journals/journals.repository.ts
backend/src/journals/journals.service.ts

테이블명을 더 명확하고 간결하게 변경했습니다
- 예시
- 예시

backend/DANG-367:  walk-journals -> journals, walk-dogs -> journals-dogs로 테이블명 변경

---

backend/src/users/users.service.ts

맞지 않는 느낌표 연산자가 들어가있어 수정하였습니다.
- 예시
- 예시

backend/DANG-369: checkDogOwnership 함수 로직 수정

---

backend/src/common/interceptor/serialize.interceptor.ts

- excludeExtraneousValues 속성을 추가해 @Exclude 된 항목은 제외하도록 함
- ClassConstructor 타입 사용이 안되고 있어서 사용하도록 변경함
- 예시
- 예시

backend/DANG-371: Serialize 데코레이터에 excludeExtraneousValues 속성 추가

---

frontend/package-lock.json
frontend/package.json

환경 변수 관리 도구 추가
- 새로운 의존 관계 env-cmd 패키지를 추가했습니다.
- 이 패키지는 .env 파일을 읽어 환경 변수를 설정하는 데 사용됩니다.
- 예시
- 예시

infra/DANG-370: 프론트엔드 환경 변수 관리 의존성 패키지 추가

---

.github/workflows/frontend_deploy.yaml

infra/DANG-375: Github Actions에 build 스크립트를 변경하라

---

frontend/src/vitest.test.ts

infra/DANG-376: 프론트 테스트 코드를 작성하라

---

backend/src/entity/journal-photos.entity.ts

walk-log-photos -> journal-photos로 테이블명을 변경하였습니다
- 예시
- 예시

backend/DANG-382: walk-log-photos -> journal-photos로 테이블명 변경

---

frontend/public/index.html

frontend/DANG-384: manifest.json Syntax error 오류를 해결하라

---

frontend/src/pages/Join.tsx

frontend/DANG-316: 약관동의화면 다음단계버튼 생성

---

backend/src/auth/auth.controller.ts
backend/src/auth/auth.service.ts
backend/src/common/database/abstract.repository.ts
backend/src/users/users.entity.ts
backend/src/users/users.service.spec.ts
backend/src/users/users.service.ts

- createIfNotExists method는 중복된 경우 ConflictException을 throw한다.
- updateAndFindOne method는 존재하는 entity를 update하며 entity가 없으면 NotFoundException을 throw한다.
- findOneRaw method는 entity 또는 null을 그대로 반환한다.
- users service에 대한 test를 추가했다.
- 변경된 logic 및 api 명세에 따라 api를 수정 & 추가했다.
https://www.notion.so/do0ori/api-54027be72b2547a99d6b7d50ee87b2ea
- 예시
- 예시

backend/DANG-372: login api 수정 및 signin api 추가

---

frontend/src/api/auth.ts
frontend/src/components/LoginBottomSheet.tsx
frontend/src/components/OAuthButton.tsx
frontend/src/hooks/useAuth.ts
frontend/src/pages/Join.tsx
frontend/src/pages/Profile.tsx
frontend/src/utils/oauth.ts

LoginBottomSheet에서 로그인 버튼 클릭시 회원인경우 Login api 호출
회원이 아닌경우 약관동의 화면 후 다음단계에서 가입시 Signin api 호출
- 예시
- 예시

frontend/DANG-388: 로그인, 회원가입 api 구현

---

frontend/package-lock.json
frontend/package.json
frontend/svgo.config.cjs

재사용 가능한 SVG 컴포넌트를 만들기 위한 [SVGR](https://react-svgr.com/) 환경 설정
https://www.notion.so/do0ori/SVGR-1afca2a605dc4d07b924ea63e7f6a290?pvs=4
- 예시
- 예시

frontend/DANG-248: SVGR 환경 설정

---

frontend/src/utils/oauth.ts

frontend/DANG-392: 구글로그인 문제 해결

---

backend/src/auth/auth.service.spec.ts
backend/src/common/database/abstract.repository.ts
backend/src/users/users.service.ts

auth service의 method들에 대해 간단한 테스트를 추가했다.
- 예시
- 예시

backend/DANG-393: login, signin, validateAccess/RefreshToken 간단한 테스트 추가

---

frontend/docker-entrypoint.sh
frontend/public/index.html

주요 변경 사항
- 새로운 스크립트가 docker-entrypoint.sh 파일에 추가되었습니다.
- 빈 파일 ./build/env.js 생성
- 예시
- 예시

infra/DANG-389: 프론트엔드 빌드 아웃풋에 환경 변수 주입

---

frontend/src/pages/Agreements.tsx

frontend/DANG-314: 약관동의화면 디자인

---

frontend/public/index.html
frontend/src/api/weather.ts
frontend/src/typed/env.d.ts
frontend/tsconfig.json

- frontend/src/api/weather.ts 파일에서 날씨 API 관련 서비스 키를 가져오는 로직을 수정했습니다.
- frontend/public/index.html 파일에서는 빌드 스크립트가 생성한 env.js 파일을 로딩하여 window._ENV 객체를 정의합니다.
- 예시
- 예시

infra/DANG-394: window 전역 객체 사용하여 env 파일 값 호출하기

---

frontend/src/components/icon/Check.tsx

아이콘 컴포넌트 Check 구현
https://www.notion.so/do0ori/Check-2d5d09113c3c45709373aec3e00e5253?pvs=4
- 예시
- 예시

frontend/DANG-379: 아이콘 컴포넌트 Check 구현

---

backend/src/main.ts

프론트엔드 URL http://dangdang-walk.prgms-fullcycle.com을 추가로 허용하도록 CORS 설정을 업데이트했습니다.
- 예시
- 예시

infra/DANG-400: 백엔드 CORS 설정 EC2 URL 허용하기

---

frontend/src/components/walk/WalkHeader.tsx
frontend/src/components/walk/WalkInfo.tsx
frontend/src/hooks/useGeolocation.ts
frontend/src/models/location.model.ts
frontend/src/pages/Walk.tsx
frontend/src/store/walkStore.ts
frontend/src/utils/format.test.ts
frontend/src/utils/format.ts
frontend/src/utils/geo.ts

walk store  칼로리, 거리, 위치 추가
타이머 기능 추가
칼로리 기능 추가
거리 계산 로직 추가
weather info 스타일 추가 
- 예시
- 예시

frontend/DANG-364: walkinfo 컴포넌트 추가

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/common/Checkbox2.tsx

공통 컴포넌트 CheckBox2 구현
https://www.notion.so/do0ori/CheckBox2-9bce54e1982a448db6d18f4d6ba20f57?pvs=4
- 예시
- 예시

frontend/DANG-358: 공통 컴포넌트 CheckBox2 구현

---

frontend/src/api/map.ts

process.env.REACT_APP_KAKAO_CLIENT_ID와 process.env.REACT_APP_KAKAO_MAP_URL 환경 변수를 직접 사용했습니다. 
이번 커밋을 통해 앞서 설정된 window._ENV 객체를 사용하도록 변경되었습니다.
- 예시
- 예시

infra/DANG-404: KakaoMap 환경 변수를 window.ENV으로 변경하라

---

frontend/components.json

shadcn/ui 설정에 aliases.ui 추가
https://www.notion.so/do0ori/shadcn-ui-1e0c6a5c777e4552bde4206a1c791f0a?pvs=4
- 예시
- 예시

frontend/DANG-397: shadcn/ui 설정 수정

---

backend/src/auth/auth.controller.ts
backend/src/auth/auth.service.spec.ts
backend/src/auth/auth.service.ts
frontend/src/api/auth.ts

signin은 로그인, signup은 회원가입을 뜻한다.
https://www.notion.so/do0ori/signin-signup-a86d4e2a8e1f49aa876c9cb26cdb8f1c
- 예시
- 예시

backend/DANG-406: 회원가입 api를 signin에서 signup으로 수정

---

frontend/tailwind.config.js

tailwind custom animate 추가
- 예시
- 예시

frontend/DANG-414: tailwind custom animate 추가

---

frontend/src/App.tsx

css: LoginBottomSheet duration-200 수정
- 예시
- 예시

frontend/DANG-413: LoginBottomSheet duration-200 수정

---

frontend/src/components/OAuthButton.tsx

refactor: Oauth 로그인 클릭후 딜레이 주기
버튼 클릭후 약관동의화면 슬라이드 보여주전에 로그인 바텀시트가 내려가는 것이 끊김 현상을 없애기 위해 딜레이를 주었다.
- 예시
- 예시

frontend/DANG-416: Oauth 로그인 클릭후 딜레이 주기

---

frontend/src/pages/JoinStep/PetOwner.tsx

style: 가입중 반려견 유무 페이지 디자인
- 예시
- 예시

frontend/DANG-409: 가입중 반려견 유무 페이지 디자인

---

frontend/src/pages/JoinStep/DogRegister1.tsx

style: 가입중 강아지정보입력 페이지1 디자인
- 예시
- 예시

frontend/DANG-410: 가입중 강아지정보입력 페이지1 디자인

---

frontend/src/pages/Home.tsx

feat: Home.tsx 로그인 기능 추가
- 예시
- 예시

frontend/DANG-418: Home.tsx 로그인 기능 추가

---

backend/src/common/interceptor/logging.interceptor.ts

https://www.notion.so/do0ori/oauthId-42c21052472648c5a659e8f3520b5e88
- 예시
- 예시

backend/DANG-368: Request log format에 oauthId 추가

---

frontend/docker-entrypoint.sh

기존 파일 삭제:
- 스크립트 실행 시 기존 build/env.js 파일이 있으면 삭제합니다. 파일 생성 및 변수 주입:
- build/env.js 파일을 새로 생성하고 프론트엔드 애플리케이션에서 사용할 수 있는 환경 변수 객체 (window._ENV)를 정의합니다.
- 환경 변수명이 REACT_APP_ 접두사로 시작하는 경우 (env 객체의 프로퍼티) 해당 키와 값을 window._ENV 객체에 추가합니다.
- 예시
- 예시

infra/DANG-439: 기존 프론트엔드 환경 변수 스크립트 개선

---

backend/src/dogs/dogs.entity.ts
backend/src/dogs/dto/dog.dto.ts

Reverts jihwooon/dangdang-walk#270

Revert "backend/DANG-436: Dogs birth field에 null option 추가"

---

backend/src/common/interceptor/logging.interceptor.ts

backend/DANG-445: logger 데이터에서 metrics url를 제외하라

---

backend/src/common/database/database.module.ts

backend/DANG-446: 데이터베이스 생성 변경 될 때 업데이트를 하라

---

backend/src/auth/auth.service.spec.ts
backend/src/auth/oauth/google.service.ts
backend/src/auth/oauth/kakao.service.ts
backend/src/auth/oauth/naver.service.ts
backend/src/auth/oauth/oauth.module.ts

backend/DANG-443: oauth service에 logger 추가

---

backend/src/dogs/guards/authDog.guard.ts
backend/src/users/users.service.ts
backend/src/utils/utilityFUnctions.utils.ts

해당 로직을 다른 곳에서도 자주 써서 유틸 함수로 분리하였습니다. 
- 예시
- 예시

backend/DANG-437: 배열에 특정 요소 또는 특정 배열이 모두 포함되어있는 검사하는 로직 함수로 분리

---

frontend/src/hooks/useAuth.ts

frontend/DANG-449: 로그인 버그 fix

---

frontend/src/components/common/Checkbox2.tsx

공통 컴포넌트 Checkbox2에 아이콘을 바꾸는 기능 추가
https://www.notion.so/do0ori/Checkbox2-544e9a516e444f5988c67740af6831f9?pvs=4
- 예시
- 예시

frontend/DANG-438: Checkbox2에 아이콘을 바꾸는 기능 추가

---

frontend/public/index.html
frontend/src/components/walk/Map.tsx
frontend/src/pages/Walk.tsx
frontend/src/utils/geo.ts

map 컴포넌트 위치 외부 주입으로 바꿈
map 컴포넌트 생성시 카카오맵 api 호출
- 예시
- 예시

frontend/DANG-448: 맵 sdk map 컴포넌트 랜더시 호출되게 바꿈

---

frontend/src/App.tsx
frontend/src/components/common/BottomSheet.tsx
frontend/src/components/common/Checkbox2.tsx
frontend/src/hooks/useGeolocation.ts
frontend/src/hooks/useWalkingDogs.ts
frontend/src/hooks/useWeather.ts
frontend/src/pages/Walk.tsx

frontend/DANG-431: chore: 서버에서 동작확인을 위한 console 배치

---

frontend/src/api/weather.ts

frontend/DANG-444: weather 정보를 직접 노출하여 정보 값을 확인하라

---

frontend/public/index.html

mixed cotent error head에 메타 태그 추가
- 예시
- 예시

frontend/DANG-455: mixed cotent error head에 메타 태그 추가

---

backend/src/main.ts

- https://www.notion.so/do0ori/CORS-Vercel-8d285c5b932b40faa043787710d9c318?pvs=4
- 예시
- 예시

backend/DANG-460: CORS 경로를 Vercel 경로로 수정하라

---

frontend/.gitignore
frontend/.storybook/main.ts
frontend/.storybook/preview.ts
frontend/package-lock.json
frontend/package.json

Storybook 추가 및 환경 설정
https://www.notion.so/do0ori/Storybook-f3c631b673054998b9eb1cf3b61dec6f?pvs=4
- 예시
- 예시

frontend/DANG-403: Storybook 추가 및 환경 설정

---

frontend/src/components/icon/Check.stories.tsx
frontend/src/components/icon/Feces.stories.tsx
frontend/src/components/icon/Urine.stories.tsx

`Check`, `Feces`, `Urine` 컴포넌트의 스토리 작성
https://www.notion.so/do0ori/e07625ad1a2a4b7e8d272341922137a7?pvs=4
- 예시
- 예시

frontend/DANG-474: 아이콘 컴포넌트의 스토리 작성

---

backend/src/dogs/dogs.controller.ts
backend/src/dogs/dogs.entity.ts
backend/src/dogs/dogs.service.ts
backend/src/dogs/dto/dog-statistic.dto.ts
backend/src/dogs/dto/dog.dto.ts
backend/src/journals/dto/journals-detail.dto.ts
backend/src/journals/journals.entity.ts
backend/src/journals/journals.service.ts

산책 경로 이미지 : logI_image_url → route_image_url
프로필 사진 : photo_url → profile_photo_url로 변경하였습니다
테스트 중 journals에 await이 안 붙어 있는 부분들도 수정하였습니다. 이전 PR의 예외 문제도 await가 없어 생기는 문제여서 고쳐졌습니다. 
- 예시
- 예시

backend/DANG-472: 엔티티 컬럼명 변경

---

frontend/src/App.tsx
frontend/src/components/walk/WalkNavbar.tsx
frontend/src/index.css
frontend/src/pages/Walk.tsx

geoLocation 기능 키고
롱클릭 디폴트 옵션 끔
- 예시
- 예시

frontend/DANG-483: 버튼길게눌렀을때 생기는 디폴트 옵션 끔

---

frontend/src/components/common/Button.stories.tsx

Button에 대한 스토리 작성
https://www.notion.so/do0ori/Button-77047562b6014a6a967a940401195d92?pvs=4
- 예시
- 예시

frontend/DANG-484: Button에 대한 스토리 작성

---

frontend/src/utils/oauth.ts

oauth 인가코드 요청 url 계정선택화면 나오도록 수정
- 예시
- 예시

frontend/DANG-487: oauth 인가코드 요청 url 계정선택화면 나오도록 수정

---

frontend/src/App.tsx
frontend/src/index.tsx

QueryClientProvider index.tsx 로 이동
- 예시
- 예시

frontend/DANG-498: QueryClientProvider index.tsx 로 이동

---

.github/workflows/backend_deploy.yaml
backend/src/dogs/dogs.spec.ts

- 현재 실행 중인 컨테이너 (Blue 또는 Green)를 파악합니다.
- 새로운 빌드 이미지를 사용하여 Green 컨테이너를 먼저 실행하고 Health Check를 수행합니다.
- Health Check 성공 시 Nginx를 재起動하여 트래픽을 Green 컨테이너로 라우팅합니다.
- 이후 이전에 실행 중이던 Blue 컨테이너를 정지 및 제거합니다.
- 예시
- 예시

infra/DANG-503: Blue/Green 배포 스크립트를 작성

---

.github/workflows/backend_deploy.yaml
backend/src/users/users.spec.ts

infra/DANG-504: 배포 실패 에러를 수정하라

---

.github/workflows/backend_deploy.yaml

infra/DANG-505: ShellScript을 읽도록 변경하라

---

backend/src/journals/journals.spec.ts

infra/DANG-506: 배포를 위한 테스트코드를 작성하라

---

backend/src/journals/journals.spec.ts

infra/DANG-507: 배포를 위한 테스트 코드를 작성하기

---

.github/workflows/backend_deploy.yaml
backend/src/journals/journals.spec.ts

infra/DANG-509: shellscript input 값을 다르게 설정하라

---

.github/workflows/backend_deploy.yaml
backend/src/journals/journals.spec.ts

infra/DANG-512: env 파일 경로를 수정하라

---

.github/workflows/backend_deploy.yaml
backend/src/journals/journals.spec.ts

infra/DANG-513: ENV 생성 파일 경로를 수정하라

---

.github/workflows/backend_deploy.yaml
backend/src/journals/journals.spec.ts

infra/DANG-514: shellscript 절대 경로를 수정하라

---

.github/workflows/backend_deploy.yaml
backend/src/journals/journals.spec.ts

infra/DANG-515: backend 폴더 경로 삭제하라

---

.github/workflows/backend_deploy.yaml
backend/src/journals/journals.spec.ts

infra/DANG-516: env 파일 생성하도록 수정하라

---

.github/workflows/backend_deploy.yaml
backend/src/journals/journals.spec.ts

infra/DANG-517: env 파일 생성하도록 경로를 수정하라

---

.github/workflows/backend_deploy.yaml
backend/src/journals/journals.spec.ts

infra/DANG-518: deploy 시 env 파일 생성하도록 수정하라

---

.github/workflows/backend_deploy.yaml
backend/src/journals/journals.spec.ts

infra/DANG-519: 파일을 불러 올 수 있도록 직접 파일을 추가하라

---

.github/workflows/backend_deploy.yaml
backend/src/journals/journals.spec.ts

infra/DANG-520: backend env.prod 파일 생성하도록 로직 추가하라

---

frontend/src/components/common/BottomSheet.tsx

bottom Sheet  bg-white
- 예시
- 예시

frontend/DANG-522: bottom Sheet  bg-white

---

frontend/src/components/walk/Map.tsx
frontend/src/pages/Walk.tsx

map에 경로그려주는 기능 추가
map height 수정 및 class 추가 할 수 있게 변경
- 예시
- 예시

frontend/DANG-467: map에 경로 그려주는 기능 추가

---

frontend/src/App.tsx

home, profile일때만  navbar, loginAlertModal 보여주기
- 예시
- 예시

frontend/DANG-526: home, profile일때만  navbar, loginAlertModal 보여주기

---

frontend/src/api/auth.ts
frontend/src/hooks/useAuth.ts
frontend/src/pages/Profile.tsx
frontend/src/store/authStore.ts

frontend/DANG-524: 로그인/회원가입로직 수정

---

frontend/src/pages/Join.tsx
frontend/src/pages/JoinStep/Agreements.tsx
frontend/src/pages/JoinStep/DogRegister1.tsx
frontend/src/pages/JoinStep/DogRegister2.tsx

join 페이지에 회원가입 로직 추가
- 예시
- 예시

frontend/DANG-533: join 페이지에 회원가입 로직 추가

---

frontend/src/pages/Health.tsx

frontend/DANG-430: 카메라 기능확인

---

frontend/src/App.tsx
frontend/src/components/common/Toast.mdx
frontend/src/components/common/Toast.stories.tsx
frontend/src/components/common/Toast.tsx
frontend/src/hooks/useToast.ts
frontend/src/store/toastStore.ts

공통 컴포넌트 Toast 구현
https://www.notion.so/do0ori/Toast-8fb16e2019b04d9a9143d350cb5194ef?pvs=4
- 예시
- 예시

frontend/DANG-490: 공통 컴포넌트 Toast 구현

---

frontend/.storybook/main.ts

Storybook 실행을 못하는 문제 해결
https://www.notion.so/do0ori/Storybook-2f87c634568f4b51b0868f621b74f483?pvs=4
- 예시
- 예시

frontend/DANG-535: Storybook 실행을 못하는 문제 해결

---

frontend/src/constants/keys.ts
frontend/src/pages/Join.tsx
frontend/src/store/authStore.ts

frontend/DANG-538: 로그아웃 후 로그인 상태 처리

---

frontend/.storybook/main.ts

path 모듈을 가져오는 방식 변경
https://www.notion.so/do0ori/path-b58651ceab9e4d7c922012b1f3221eb6?pvs=4
- 예시
- 예시

frontend/DANG-537: path 모듈을 가져오는 방식 변경

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/common/AlertDialog.tsx
frontend/src/components/common/Modal.tsx

공통 컴포넌트 Modal 구현
https://www.notion.so/Modal-d6ca5355c26644b3832f2da1d4136907?pvs=4
- 예시
- 예시

frontend/DANG-491: 공통 컴포넌트 Modal 구현

---

frontend/src/pages/JoinStep/DogRegister1.tsx
frontend/src/pages/JoinStep/DogRegister2.tsx

모바일환경에서 사진input, 숫자패드 input 확인 테스트
- 예시
- 예시

frontend/DANG-541: 모바일환경에서 사진input, 숫자패드 input 확인 테스트

---

frontend/src/models/dog.model.ts
frontend/src/pages/Join.tsx
frontend/src/pages/JoinStep/DogRegister1.tsx
frontend/src/pages/JoinStep/DogRegister2.tsx

feat: 강아지 등록정보 관련 state 관리하기
- 예시
- 예시

frontend/DANG-497: 강아지 등록정보 관련 state 관리하기

---

frontend/src/pages/Join.tsx

test: 모바일 환경에서 가입 테스트
- 예시
- 예시

frontend/DANG-543: 모바일 환경에서 가입 테스트

---

frontend/src/components/common/Button.stories.tsx

Button 스토리에서 불필요한 ESLint 무시 제거
https://www.notion.so/do0ori/Button-ESLint-6bcdc3fead6a4206aeda05527c65c27c?pvs=4
- 예시
- 예시

frontend/DANG-521: Button 스토리에서 불필요한 ESLint 무시 제거

---

backend/src/auth/auth.module.ts
backend/src/auth/auth.service.spec.ts
backend/src/auth/auth.service.ts
backend/src/auth/guards/auth.guard.ts

backend/DANG-544: 회원 로직 로그 찍기

---

frontend/src/api/dog.ts
frontend/src/api/dogs.ts
frontend/src/components/home/AvailableDogCheckList.tsx
frontend/src/components/home/DogCardList.tsx
frontend/src/components/walk/DogFeceAndUrineCheckList.tsx
frontend/src/components/walk/WalkNavbar.tsx
frontend/src/hooks/useDogStatistic.ts
frontend/src/hooks/useWalkingDogs.ts
frontend/src/index.tsx
frontend/src/models/dog.model.ts
frontend/src/pages/Camera.tsx
frontend/src/pages/Home.tsx
frontend/src/pages/Walk.tsx

홈화면 바탐시트 추가
홈화면에서 강아지 일주일 산책량 api 추가
- 예시
- 예시

frontend/DANG-429: 홈화면 강아지 일주일 산책량 api 추가

---

backend/src/auth/auth.controller.ts
backend/src/auth/guards/auth.guard.ts

backend/DANG-546: signup에 로그 추가

---

backend/src/auth/guards/oauthData.guard.ts

backend/DANG-549: oauthDataguard에 로그 추가

---

frontend/src/components/common/Modal.mdx
frontend/src/components/common/Modal.stories.tsx

Modal 컴포넌트에 대한 스토리와 문서 작성
https://www.notion.so/do0ori/Modal-4e2d3a4ffba4407bb9b09fc37ae9d678?pvs=4
- 예시
- 예시

frontend/DANG-539: Modal 컴포넌트에 대한 스토리와 문서 작성

---

backend/src/auth/interceptors/cookie.interceptor.ts

backend/DANG-550: secure 속성을 false로 변경

---

frontend/src/api/dogs.ts
frontend/src/components/common/Spiner.tsx
frontend/src/components/common/Topbar.tsx
frontend/src/components/home/DogCard.tsx
frontend/src/components/home/WeatherInfo.tsx
frontend/src/hooks/useAddressAndAirgrade.ts
frontend/src/hooks/useWalkAvailabeDog.ts
frontend/src/hooks/useWalkingDogs.ts
frontend/src/pages/Home.tsx
frontend/src/pages/Walk.tsx

홈화면 배경 수정
홈화면에서 산책화면으로 넘어갈떄 강아지 넘겨주는 기능 적용
산책 가능한 강아지 hook 추가
강아지 없을때 산책 버튼 없애기
dog api 오류 수정
- 예시
- 예시

frontend/DANG-548: 홈화면 데이터 바인딩

---

backend/src/auth/interceptors/cookie.interceptor.ts

https://www.notion.so/do0ori/Cross-site-Cookie-12a6e173f8f44aa684a96e7f05ac71a3
- 예시
- 예시

backend/DANG-552: clear cookie에 option 명시적으로 추가

---

frontend/src/hooks/useAuth.ts
frontend/src/hooks/useDogStatistic.ts
frontend/src/pages/Home.tsx

refactor: 홈화면 강아지 산책 목록 비동기처리
- 예시
- 예시

frontend/DANG-555: 홈화면 강아지 산책 목록 비동기처리

---

.github/script/backend.sh
conf/loki-config.yaml
conf/promtail-config.yaml

EC2 만료일이 지나면 접근이 불가능함으로 EC2에서 작업한 내용을 프로젝트로 옮깁니다.
- 예시
- 예시

infra/DANG-559: EC2내 작업한 내용을 프로젝트로 옮기기

---

frontend/src/index.tsx
frontend/src/pages/Journals/CreateForm.tsx

산책 기록 페이지(`/journals/create`)에서 태그 및 기본 로직 구현
https://www.notion.so/do0ori/5c11c26727494896b02be4abf834e3ad?pvs=4
- 예시
- 예시

frontend/DANG-318: 산책 기록 페이지에서 태그 및 기본 로직 구현

---

backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/s3/s3.controller.ts
backend/src/s3/s3.module.ts
backend/src/s3/s3.service.ts

AWS s3에 이미지를 업로드 할 수 있는 url인 presignedUrl을 가져오는 api를 구현했습니다. 
프론트엔드에서 이미지 업로드시 이 url로 요청을 보내, presignedUrl & key(파일명)를 받아
Url을 통해 이미지를 업로드하게 됩니다.
자세한건 문서로 공유하겠습니다.
env.local에 노션에 공유한 KEY들을 추가해야 합니다.
배포용 KEY도 추가 예정
- 예시
- 예시

backend/DANG-447: presignedUrl 생성 api 구현

---

backend/src/s3/s3.controller.ts
backend/src/s3/s3.service.ts
backend/src/s3/type/s3.type.ts

backend/DANG-561: upload api에 리스폰스 타입 추가, ContentType 추가

---

backend/src/s3/s3.service.ts

backend/DANG-562: 배포용

---

frontend/src/components/home/AvailableDogCheck.tsx
frontend/src/components/home/AvailableDogCheckList.tsx
frontend/src/components/home/DogCard.tsx
frontend/src/components/home/WeatherInfo.tsx
frontend/src/hooks/useAddressAndAirgrade.ts
frontend/src/hooks/useSunsetSunrise.ts
frontend/src/hooks/useWeather.ts
frontend/src/pages/Home.tsx

강아지 카드 눌렀을때 이동
산책가능한 강아지 없을때, 전체선택 기능 추가
- 예시
- 예시

frontend/DANG-302: 홈화면에서 기능추가, 페이지이동

---

frontend/src/hooks/useAuth.ts
frontend/src/store/authStore.ts

frontend/DANG-566: 배포환경에서 로그인 상태 테스트1

---

backend/src/auth/interceptors/cookie.interceptor.ts

배포 환경인 cross-site에서 domain을 설정해주지 않으면 server의 domain이 default여서 client서 읽지 못한다.
- 예시
- 예시

backend/DANG-571: cookie domain 추가

---

frontend/src/hooks/useAuth.ts

frontend/DANG-572: auth console.log 삭제

---

backend/src/auth/interceptors/cookie.interceptor.ts

backend/DANG-573: cookie domain 앞에 .을 붙여 하위 domain까지 허용

---

frontend/src/hooks/useAuth.ts
frontend/src/hooks/useCookie.ts
frontend/src/store/authStore.ts

frontend/DANG-579: 배포환경 로그인 상태 관리 테스트2

---

frontend/src/hooks/useAuth.ts

frontend/DANG-580: 배포환경 로그인 상태 관리 테스트3

---

backend/src/auth/interceptors/cookie.interceptor.ts

backend/DANG-581: isLoggedIn 및 expiresIn cookie에서 sameSite: lax 사용

---

frontend/src/App.tsx
frontend/src/hooks/useAuth.ts
frontend/src/store/authStore.ts

frontend/DANG-583: 배포환경 로그인 상태 관리 테스트4

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/CropperModal.tsx
frontend/src/components/ImageCropper.tsx
frontend/src/constants/cropper.ts
frontend/src/constants/index.ts
frontend/src/pages/Join.tsx
frontend/src/pages/JoinStep/DogRegister1.tsx
frontend/src/utils/canvas-preview.ts

frontend/DANG-568: image cropper 기능 추가

---

backend/src/auth/interceptors/cookie.interceptor.ts
backend/src/auth/oauth/google.service.ts
backend/src/auth/oauth/kakao.service.ts
backend/src/auth/oauth/naver.service.ts
backend/src/auth/oauth/oauth.module.ts

oauth API 요청에 error logging 추가
- 예시
- 예시

backend/DANG-586: oauth API 요청에 error logging 추가

---

frontend/src/components/ImageCropper.tsx

frontend/DANG-587: 배포환경에서 crop 화면 테스트1

---

frontend/src/components/ImageCropper.tsx

fix: 배포환경에서 crop 화면 테스트2
- 예시
- 예시

frontend/DANG-588: 배포환경에서 crop 화면 테스트2

---

frontend/src/components/ImageCropper.tsx

fix: 배포환경에서 crop 화면 테스트3
- 예시
- 예시

frontend/DANG-590: 배포환경에서 crop 화면 테스트3

---

frontend/src/components/ImageCropper.tsx

fix: 배포환경에서 crop 화면 테스트4
- 예시
- 예시

frontend/DANG-592: 배포환경에서 crop 화면 테스트4

---

frontend/src/api/walk.ts
frontend/src/components/home/WeatherInfo.tsx
frontend/src/components/walk/Map.tsx
frontend/src/components/walk/WalkNavbar.tsx
frontend/src/constants/keys.ts
frontend/src/hooks/useGeolocation.ts
frontend/src/hooks/useStopAlert.ts
frontend/src/hooks/useStopWatch.ts
frontend/src/hooks/useWalkingDogs.ts
frontend/src/pages/Home.tsx
frontend/src/pages/Walk.tsx

토스트 적용
state 오는 데이터 적용
스토리지 적용
산책 종료후 스토리지 지우고 페이지 이동
- 예시
- 예시

frontend/DANG-575: 산책 페이지 데이터 바인딩

---

backend/package-lock.json
backend/package.json

backend/DANG-610: sqlite3 제거

---

backend/src/s3/s3.service.ts
backend/src/s3/type/s3.type.ts

backend/DANG-612: presignedURL api 속성명 key -> filename으로 변경

---

.github/labeler.yml
.github/workflows/pr_labeler_validator.yaml

- rever branch 이름 검사 예외 처리 추가
- label에 emoji를 추가하면서 labeler에도 emoji 추가
- 예시
- 예시

infra/DANG-613: revert branch 예외 처리 추가

---

backend/src/journals/journals.controller.ts

산책일지 상세조회 API journalId를 param으로 받도록 변경했습니다.
- 예시
- 예시

backend/DANG-614: 산책일지 상세조회 API journalId를 param으로 받도록 변경

---

frontend/src/api/upload.ts
frontend/src/constants/keys.ts
frontend/src/hooks/useImageUpload.ts
frontend/src/hooks/useWalkAvailabeDog.ts
frontend/src/pages/Camera.tsx

frontend/DANG-597: 이미지 업로드 훅 추가

---

backend/src/s3/s3.service.ts

backend/DANG-621: 배포용 TODO 로그 삭제

---

frontend/src/api/upload.ts
frontend/src/hooks/useImageUpload.ts

upload api header 수정
- 예시
- 예시

frontend/DANG-619: upload api header 수정

---

backend/src/breed/breed.controller.ts

견종 목록 API는 AuthGuard를 skip하도록 변경하였습니다 
- 예시
- 예시

backend/DANG-625:  breeds API Authguard 사용하지 않도록 변경

---

frontend/src/api/breed.ts
frontend/src/components/BreedSearch.tsx
frontend/src/hooks/useBreed.ts
frontend/src/pages/JoinStep/DogRegister1.tsx

frontend/DANG-593: 견종 검색 기능 구현

---

frontend/src/pages/Join.tsx
frontend/src/pages/JoinStep/DogRegister2.tsx

refactor: 강아지 상세정보입력 페이지 체크박스 리펙토링
- 예시
- 예시

frontend/DANG-632: 강아지 상세정보입력 페이지 체크박스 리펙토링

---

backend/src/breed/breed.service.ts
backend/src/dogs/dogs.service.ts
backend/src/dogs/dto/dog-statistic.dto.ts
docs/dogs/statistics.yaml

backend/DANG-627: recommendedDailyWalkAmount → recommendedWalkAmount

---

backend/src/auth/auth.service.ts

- log level을 `LOG`에서 `DEBUG`로 변경
- message에서 `|`를 `-`로 변경
- 예시
- 예시

backend/DANG-633: auth service log level과 message 일부 수정

---

frontend/src/components/ImageCropper.tsx
frontend/src/pages/Join.tsx
frontend/src/pages/JoinStep/DogRegister1.tsx
frontend/src/pages/JoinStep/DogRegister2.tsx

feat: 강아지 등록 정보 state 연결
- 예시
- 예시

frontend/DANG-636: 강아지 등록 정보 state 연결

---

frontend/src/components/BreedSearch.tsx
frontend/src/pages/Join.tsx
frontend/src/pages/JoinStep/DogRegister1.tsx
frontend/src/pages/JoinStep/DogRegister2.tsx

refactor: DogRegInfo 타입 수정
- 예시
- 예시

frontend/DANG-637: DogRegInfo 타입 수정

---

backend/src/dogs/dogs.controller.ts
backend/src/dogs/dogs.entity.ts
backend/src/dogs/dto/dog-statistic.dto.ts
backend/src/dogs/dto/dog.dto.ts
backend/src/journals/dto/journals-detail.dto.ts
backend/src/journals/journals.service.ts

backend/DANG-638: Dogs.profilePhotoUrl null 허용

---

backend/package-lock.json
backend/package.json
backend/src/s3/s3.controller.ts
backend/src/s3/s3.service.ts

aws-sdk v3로 변경했습니다
presignedURL을 리턴하는 upload API를 이미지 갯수만큼 URL 리턴하도록 변경했습니다
- 예시
- 예시

backend/DANG-609: aws-sdk v3로 변경, upload API 이미지 갯수만큼 URL 리턴하도록 변경

---

backend/src/auth/guards/auth.guard.ts
backend/src/auth/guards/refreshToken.guard.ts

error 객체를 따로 만들어 주지 않으면 error log는 뜨지만 response status가 500 error가 뜬다.
그래서 jwt token error 발생 시 401 에러 객체를 만들어 던지고 error log도 찍도록 했다.
- 예시
- 예시

backend/DANG-643: token error 객체 생성 & error log 추가

---

frontend/src/api/upload.ts
frontend/src/hooks/useImageUpload.ts

refactor: getUploadUrl api 수정
frontend/DANG-644
- 예시
- 예시

frontend/DANG-644: getUploadUrl api 수정

---

backend/src/daily-walk-time/daily-walk-time.entity.ts
backend/src/daily-walk-time/daily-walk-time.module.ts
backend/src/daily-walk-time/daily-walk-time.repository.ts
backend/src/daily-walk-time/daily-walk-time.service.ts
backend/src/dogs/dogs.entity.ts
backend/src/dogs/dogs.module.ts
backend/src/dogs/dogs.service.ts
backend/src/statistics/statistics.service.ts

API에 맞춰 daily_walk_time 테이블명을 today_walk_time으로 변경
- 예시
- 예시

backend/DANG-647: daily_walk_time 테이블을 today_walk_time으로 변경 

---

backend/src/dogs/dogs.controller.ts
backend/src/dogs/dogs.service.ts

updateDog breed optional하게 처리
- 예시
- 예시

backend/DANG-650: breed field가 생략되었을 때 처리 코드 추가

---

frontend/src/api/dogs.ts
frontend/src/components/ImageCropper.tsx
frontend/src/hooks/useAuth.ts
frontend/src/hooks/useDog.ts
frontend/src/pages/Join.tsx
frontend/src/utils/dataUrlToFile.ts

frontend/DANG-653: 강아지 등록 기능 구현
- 예시
- 예시

frontend/DANG-653: 강아지 등록 기능 구현

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/api/dogs.ts
frontend/src/api/upload.ts
frontend/src/components/home/AvailableDogCheck.tsx
frontend/src/components/home/AvailableDogCheckList.tsx
frontend/src/components/home/DogCard.tsx
frontend/src/components/home/DogCardList.tsx
frontend/src/components/home/RegisterCard.tsx
frontend/src/components/walk/Map.tsx
frontend/src/hooks/useDogStatistic.ts
frontend/src/hooks/useImageUpload.ts
frontend/src/hooks/useWalkAvailabeDog.ts
frontend/src/models/dog.model.ts
frontend/src/pages/Camera.tsx
frontend/src/pages/Health.tsx
frontend/src/pages/Home.tsx
frontend/src/pages/Walk.tsx
frontend/src/store/spinnerStore.ts

useAvailableDog refacoring
useImageUpload 파일 여러개 적용
임시적역 스피너 추가
- 예시
- 예시

frontend/DANG-527: image upload 수정 및 photourl 베이스 url 추가

---

frontend/src/components/CancelRegModal.tsx
frontend/src/pages/Join.tsx

feat: 강아지 등록 flow 중 취소 modal 추가
- 예시
- 예시

frontend/DANG-655: 강아지 등록 flow 중 취소 modal 추가

---

frontend/src/components/home/RegisterCard.tsx
frontend/src/pages/Join.tsx

frontend/DANG-656: 강아지 등록화면으로 가는 페이지 이동 추가

---

frontend/src/pages/Join.tsx

refactor: 강아지 등록 photoUrl 수정
- 예시
- 예시

frontend/DANG-661: 강아지 등록 photoUrl 수정

---

backend/src/journals/journals.service.ts
backend/src/statistics/statistics.service.ts
backend/src/utils/date.utils.ts

- 주어진 날짜의 주차를 구하는 util 함수 추가
- userId, dogsId, 한 달 기간에 해당하는 journals data를 가져와 주별로 가공해 월별 강아지 산책 현황 data를 반환한다.
https://www.notion.so/do0ori/API-3-6ffa620803d74d8bb64162c3616e555b
- 예시
- 예시

backend/DANG-646: 월별 강아지 산책 현황 조회 API

---

frontend/src/pages/Join.tsx

refactor: 홈화면에서 강아지 등록 페이지 이동 후 로직 수정
- 예시
- 예시

frontend/DANG-662: 홈화면에서 강아지 등록 페이지 이동 후 로직 수정

---

backend/src/utils/date.utils.spec.ts

backend/DANG-663: getWeek util 함수 test code 작성

---

frontend/src/pages/Join.tsx

refactor: 강아지 사진 url 수정
- 예시
- 예시

frontend/DANG-664: 강아지 사진 url 수정

---

backend/src/dogs/dogs.controller.ts
backend/src/dogs/dogs.module.ts
backend/src/dogs/dogs.service.ts
backend/src/journals-dogs/journals-dogs.service.ts
backend/src/walk/walk.controller.ts
backend/src/walk/walk.module.ts
backend/src/walk/walk.service.ts

- 산책 관련된 기능의 URI 변경
dogs/walks/start, dogs/walks/stop, dogs/walks/available
- dobs/walks/available을 순환 참조 문제로 walk 모듈로 옮김
- 예시
- 예시

backend/DANG-641: 산책 가능한 강아지 조회시 강제중단된 강아지의 is_walking 상태를 false로 바꿔주는 로직 추가

---

frontend/src/App.tsx
frontend/src/api/journals.ts
frontend/src/components/common/Avatar.tsx
frontend/src/components/common/NoProfileImage.tsx
frontend/src/components/common/Spinner.tsx
frontend/src/components/home/DogCard.tsx
frontend/src/components/journals/JournalCard.tsx
frontend/src/components/journals/JournalCardList.tsx
frontend/src/components/walk/WalkInfo.tsx
frontend/src/constants/keys.ts
frontend/src/index.tsx
frontend/src/models/journals.ts
frontend/src/pages/Journals/Journals.tsx
frontend/src/utils/date.ts

journal page추가
jounalcard 컴포넌트 추가
spinner 문제 해결
noprofileImage 컴포넌트 추가
- 예시
- 예시

frontend/DANG-660: jounals페이지 및 리스트 보여주는 카드 컴포넌트 추가

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/common/Avatar.tsx
frontend/src/components/common/DefaultProfileImage.tsx
frontend/src/components/journals/JournalCard.tsx
frontend/src/pages/Camera.tsx
frontend/src/pages/Walk.tsx

WalkDogData export 
NoProfileImage => DefaultProfileImage로 이름 변경
html2canvas package 삭제
- 예시
- 예시

frontend/DANG-672: WalkDogData export 및 파일 정리

---

frontend/src/components/CropperModal.tsx
frontend/src/components/ImageCropper.tsx
frontend/src/components/home/RegisterCard.tsx
frontend/src/pages/Join.tsx
frontend/src/pages/JoinStep/DogBasicInfo.tsx
frontend/src/pages/JoinStep/DogDetailInfo.tsx
frontend/src/store/cropStore.ts

refactor: crop 관련 state zustand로 상태 관리
- 예시
- 예시

frontend/DANG-671: crop 관련 state zustand로 상태 관리

---

backend/src/journals/dto/journal-update.dto.ts
backend/src/journals/dto/journals-create.dto.ts
backend/src/journals/dto/journals-detail.dto.ts
backend/src/journals/journals.entity.ts
backend/src/journals/journals.service.ts

사용자가 제목 입력하는 기능이 아예 없다고 해서 모두 삭제함
테이블에서 삭제 (엔티티에서 삭제)는 profilePhotoUrl의 속성을 text -> varchar로 바꾸는 작업과 함께 할 예정
- 예시
- 예시

backend/DANG-648: 산책 관련 메소드/DTO에서 title 필드 삭제

---

frontend/src/components/ImageCropper.tsx
frontend/src/pages/Join.tsx
frontend/src/pages/JoinStep/DogBasicInfo.tsx
frontend/src/store/cropStore.ts

ImageCropper component Join → DogBasicInfo 에서 호출
- 예시
- 예시

frontend/DANG-679: ImageCropper component Join → DogBasicInfo 에서 호출

---

frontend/src/pages/Journals/CreateForm.tsx

산책 페이지에서 넘어오는 데이터 받기
https://www.notion.so/do0ori/4df574872c1f4d5d9824eea660fcec49?pvs=4
- 예시
- 예시

frontend/DANG-665: 산책 페이지에서 넘어오는 데이터 받기

---

backend/src/dogs/dogs.module.ts
backend/src/dogs/dogs.service.ts
backend/src/journals/journals.spec.ts
backend/src/s3/s3.module.ts
backend/src/s3/s3.service.ts

강아지 프로필 수정/삭제시 S3에도 반영되도록 수정했습니다.
- 예시
- 예시

backend/DANG-678: 강아지 프로필 수정/삭제시 S3에도 반영

---

frontend/src/pages/Join.tsx
frontend/src/pages/OauthCallback.tsx

feat: 강아지 가입시 spinner 추가
- 예시
- 예시

frontend/DANG-683: 강아지 가입시 spinner 추가

---

backend/src/app.module.ts
backend/src/dogs/dogs.module.ts

backend/DANG-686: S3Module 종속성 계층 처리

---

backend/breedData.json
backend/package-lock.json
backend/package.json
backend/src/common/database/database.module.ts
backend/src/common/database/seeds/breed.seeder.ts

- [typeorm-extension](https://github.com/tada5hi/typeorm-extension?tab=readme-ov-file#seeding)을 사용해 breed data를 `DatabaseModule`이 초기화될 때 insert한다.
- 이를 위해 breed data는 json 형태로 가공했다.
https://www.notion.so/do0ori/breed-data-seeding-170b150a62414ddbb1607846b40a6843
일단 server를 매번 실행할 때마다 breed table을 truncate하고 data를 insert하도록 했는데 논의가 필요해 보인다.
- 예시
- 예시

backend/DANG-687: breed data seeding

---

backend/src/auth/auth.controller.ts
backend/src/auth/token/token.service.ts
backend/src/breed/breed.controller.ts
backend/src/breed/breed.service.ts
backend/src/common/interceptors/serialize.interceptor.ts
backend/src/walk/interceptors/walk-command.interceptor.ts

- seeding 작업으로 insert된 breed data에서 견종 목록(koreanName)을 가져오도록 업데이트했다.
https://www.notion.so/do0ori/API-187044c2d2554c75a04d296bce86ff2b
- 예시
- 예시

backend/DANG-692: 견종 목록 가져오기 API (Mock data → DB data)

---

backend/src/dogs/dogs-gender.enum.ts
backend/src/dogs/dogs.controller.ts
backend/src/dogs/dogs.service.ts

강아지 프로필 조회 API가 수정되어 필드를 추가했습니다.
- 예시
- 예시

backend/DANG-694: 강아지 프로필 조회 API 수정-필드 추가

---

backend/src/dogs/dogs.controller.ts
backend/src/dogs/dogs.service.ts
backend/src/journals/journals.service.ts
backend/src/statistics/statistics.service.ts
backend/src/walk/walk.controller.ts
backend/src/walk/walk.service.ts

profile API가 달라지면서 수정한 함수를 getAvailableDogs에서 같이 쓰고 있어서
DogSummary라는 타입을 새로 만들고, 이 타입에 맞춰서 정보를 가공하는 메소드를 새로 구현해
getAvailableDogs를 수정하였습니다.
- 예시
- 예시

backend/DANG-696: getAvailableDogs API 수정

---

frontend/src/api/dogs.ts
frontend/src/api/walk.ts

frontend/DANG-700: 강아지 산책 api 수정

---

backend/src/journals/dto/journals-detail.dto.ts

산책일지 상세페이지에 startedAt 필드를 추가했습니다.
- 예시
- 예시

backend/DANG-705: 산책일지 상세에 startedAt 추가

---

frontend/src/pages/Journals/CreateForm.tsx

산책일지 저장 페이지에서 사진 추가할 때 S3에 업로드하기
https://www.notion.so/do0ori/S3-48f607f1d55d4d95b752086c29a627f7?pvs=4
- 예시
- 예시

frontend/DANG-697: 산책일지 저장 페이지에서 사진 추가할 때 S3에 업로드하기

---

frontend/src/components/journals/DogImages.tsx
frontend/src/components/journals/Heading.tsx
frontend/src/pages/Journals/CreateForm.tsx

산책일지 저장 페이지 스타일링
https://www.notion.so/do0ori/33cbb15115414048b44abcda32bd1682?pvs=4
- 예시
- 예시

frontend/DANG-707: 산책일지 저장 페이지 스타일링

---

backend/src/dogs/guards/authDog.guard.ts
backend/src/journals/guards/authJournal.guard.ts
backend/src/journals/journals.controller.ts

backend/DANG-708: 사용자의 journal인지 확인하고 인가하는 AuthJournalGuard 추가

---

backend/src/s3/s3.controller.ts
backend/src/s3/s3.service.ts

delete용 presignedURL을 반환하는 api/delete 를 추가했습니다.
- 예시
- 예시

backend/DANG-701: api/delete 추가

---

backend/package-lock.json
backend/package.json
backend/src/auth/auth.service.ts
backend/src/common/database/database.module.ts
backend/src/dogs/dogs.service.ts
backend/src/journals/journals.service.ts
backend/src/main.ts

- 직접 구현해볼까 생각했으나 abstract repository를 사용하면서 일반적인 구조와는 좀 다르기도 하고 이미 손쉽게 transaction decorator를 사용할 수 있게 만들어둔 라이브러리가 존재해서 [typeorm-transactional](https://www.npmjs.com/package/typeorm-transactional)을 사용하기로 결정
- DB resource를 변형시키는 create, delete, update와 같은 query가 한 비즈니스 로직에서 2개 이상 사용되는 method들에 적용
https://www.notion.so/do0ori/Transaction-4e1d934d066a4d5390c57fdb695bd69f
- 예시
- 예시

backend/DANG-606: Transaction 처리

---

backend/src/auth/token/token.service.ts

backend/DANG-714: token payload에 있는 userId 및 oauthId를 number로 type casting

---

backend/src/auth/auth.service.ts
backend/src/dogs/dogs.controller.ts
backend/src/dogs/dogs.service.ts
backend/src/s3/s3.controller.ts
backend/src/s3/s3.service.ts

파일 삭제하는 api/delete API를 구현하였습니다.
- deleteSingleObject에 userId가 삭제하려는 파일의 userId와 일치하는지 체크하는 함수를 추가했습니다. 이에 따라 deleteSingleObject와 이를 사용하는 메소드들에 userId를 인자로 추가했습니다.
- 예시
- 예시

backend/DANG-710: 파일 삭제 API 구현

---

backend/src/s3/s3.controller.ts

이미지 삭제 api의 메소드를 post->delete로 변경했습니다
- 예시
- 예시

backend/DANG-721: 이미지 삭제 api post->delete로 변경

---

backend/src/journals/journals.service.ts
backend/src/statistics/statistics.controller.ts
backend/src/statistics/statistics.service.ts

- 월 data를 주별로 aggregate했었는데 일별로 하도록 수정
- field 또한 단순히 journalsCntAMonth만 사용
https://www.notion.so/do0ori/API-c24ad02e0cee4e39bd756f232284db5a
- 예시
- 예시

backend/DANG-718: 월별 강아지 산책 조회 API 수정

---

backend/src/journals/journals.service.ts
backend/src/statistics/pipes/periodValidation.pipe.ts
backend/src/statistics/statistics.controller.ts
backend/src/statistics/statistics.service.ts
backend/src/utils/date.utils.ts

- `period` query string으로 단위 선택 가능
- date가 속한 달의 통계를 보고 싶으면 `period = month` 사용
- date가 속한 주의 통계를 보고 싶으면 `period = week` 사용
추가한 util 함수들의 test 코드 작성 필요
- 예시
- 예시

backend/DANG-724: 강아지 한달 및 일주일 산책 현황 조회 API 업데이트

---

backend/src/dogs/dogs.controller.ts
backend/src/dogs/dogs.entity.ts
backend/src/dogs/dogs.service.ts
backend/src/dogs/dto/dog.dto.ts

https://www.notion.so/do0ori/API-weight-column-c47e4b2d656b48169ee3267daba0e1f9
- 예시
- 예시

backend/DANG-732: Dogs.weight column 추가

---

frontend/src/api/dogs.ts

feat: FetchDogs, deleteDog api 추가
- 예시
- 예시

frontend/DANG-737: FetchDogs, deleteDog api 추가

---

frontend/src/components/journals/CustomCalendar.css
frontend/src/components/journals/CustomCalendar.tsx

frontend/DANG-735: 캘린더 css 수정 및 달력 달이동시 변경안되는 문제 해결

---

backend/src/walk/walk.controller.ts

backend/DANG-748: 산책 시작 버그 수정

---

backend/src/auth/auth.service.spec.ts
backend/src/auth/auth.service.ts
backend/src/auth/oauth/google.service.ts
backend/src/auth/oauth/kakao.service.ts
backend/src/auth/oauth/naver.service.ts
backend/src/auth/oauth/oauth.service.interface.ts
backend/src/users/dto/createUser.dto.ts
backend/src/users/dto/updateUser.dto.ts
backend/src/users/users.entity.ts
backend/src/users/users.service.spec.ts
backend/src/users/users.service.ts

backend/DANG-757: Users table의 column명을 profileImage → profileImageUrl로 수정

---

frontend/src/api/walk.ts

잘못된 산책 중지 API Url
https://www.notion.so/do0ori/API-Url-ba4a1891880b4f4dafd0ce0072fa5162?pvs=4
- 예시
- 예시

frontend/DANG-758: 잘못된 산책 중지 API Url

---

frontend/src/components/journals/AddPhotoButton.tsx
frontend/src/components/journals/CompanionDogs.tsx
frontend/src/components/journals/Memo.tsx
frontend/src/components/journals/Photos.tsx
frontend/src/pages/Journals/CreateForm.tsx

산책일지 저장 페이지에서 컴포넌트 추출
- CompanionDogs
- Photos
- Memo
https://www.notion.so/do0ori/2776666075b943d1b1ce788793804177?pvs=4
- 예시
- 예시

frontend/DANG-752: 산책일지 저장 페이지에서 컴포넌트 추출

---

backend/src/dogs/dogs.service.ts

backend/DANG-760: 강아지 정보가 업데이트되지 않던 오류 해결

---

backend/src/auth/auth.controller.ts
backend/src/breed/breed.controller.ts
backend/src/common/health/health.controller.ts
backend/src/dogs/dogs.controller.ts
backend/src/journals/journals.controller.ts
backend/src/statistics/statistics.controller.ts
backend/src/users/users.controller.ts

- '/'로 시작
- 하위 path가 없는 경우 비워두기
https://www.notion.so/do0ori/path-b39781fd50a2422da8790beb367bdc85
- 예시
- 예시

backend/DANG-761: path 형식 통일

---

backend/src/dog-walk-day/dog-walk-day.service.ts

statstics 일주일 산책 cnt에 updated_at 컬럼이 추가되어 제외했습니다.
- 예시
- 예시

backend/DANG-762: statstics 일주일 산책 cnt에 updated_at 컬럼 추가되어 제외

---

frontend/src/api/journals.ts
frontend/src/pages/Journals/CreateForm.tsx

산책일지 저장 페이지에서 저장 API 연결
https://www.notion.so/do0ori/API-9945c114bfc844908a1f7a1613323bf5?pvs=4
- 예시
- 예시

frontend/DANG-712: 산책일지 저장 페이지에서 저장 API 연결

---

frontend/src/components/walk/Map.tsx
frontend/src/pages/Journals/CreateForm.tsx

frontend/DANG-739: Map 컴포넌트에서 중복 sdk fetch 제거 및 createform페이지 맵 적용

---

backend/src/common/database/database.module.ts
backend/src/dogs/dogs.entity.ts

생일 정보는 날짜만 필요하므로 date로 변경한다.
- 예시
- 예시

backend/DANG-766: 강아지 생일 data type을 timestamp에서 date로 변경

---

backend/src/utils/date.utils.ts

주어진 날짜의 하루 시작과 끝 Date 객체를 반환
https://www.notion.so/do0ori/getStartAndEndOfDay-util-b48e07d864d745d4b702df1daef6c215
- 예시
- 예시

backend/DANG-777: 하루 범위를 구하는 getStartAndEndOfDay util 추가

---

backend/src/journals/journals.service.ts

산책일지 목록 조회 날짜 UTC로 변환해 조회하도록 변경, console.log 제거
- 예시
- 예시

backend/DANG-775: 산책일지 목록 조회 날짜 UTC로 변환해 조회하도록 변경, console.log 제거

---

backend/src/journals/journals.controller.ts
backend/src/journals/journals.service.ts

산책 상세 API url에서 dogId가 삭제되어 수정했습니다.
- 예시
- 예시

backend/DANG-780: 산책 상세 API에서 dogId 파람 제거

---

docs/auth/login.yaml
docs/auth/signup.yaml
docs/auth/token.yaml
docs/auth/users.yaml
docs/openapi.yaml

infra/DANG-785: swagger 회원 API 업데이트

---

frontend/src/api/dogs.ts
frontend/src/api/journals.ts
frontend/src/assets/icons/ic-drop-down.svg
frontend/src/components/common/SelectBox.tsx
frontend/src/components/home/DogCard.tsx
frontend/src/components/home/DogCardList.tsx
frontend/src/components/journals/CustomCalendar.tsx
frontend/src/components/journals/JournalCard.tsx
frontend/src/components/journals/JournalCardList.tsx
frontend/src/components/walk/WalkHeader.tsx
frontend/src/hooks/useCalendar.ts
frontend/src/hooks/useDogsStatistic.ts
frontend/src/hooks/useJournals.ts
frontend/src/models/dog.model.ts
frontend/src/pages/Home.tsx
frontend/src/pages/Journals/Journals.tsx

home 화면에서 jounal페이지로 넘겨 줄때 데이터 상태 보내주는 기능 추가
캘린더 shadow 적용
journal api에서 date에 null들어가는 문제 해결
useCalendar로 캘린더 로직 빼냄
selectbox 컴포넌트 추가
강아지 선택시 생기는 이벤트 적용ㅂ
- 예시
- 예시

frontend/DANG-749: 산책기록 페이지 select box

---

backend/src/statistics/pipes/date-validation.pipe.ts

불필요한 것 같아서 삭제
https://www.notion.so/do0ori/DateValidatePipe-74b28198c18142eb8ecdb45d425070a7
- 예시
- 예시

backend/DANG-782: 미래인지 확인하는 logic 삭제

---

frontend/src/components/common/SelectBox.tsx
frontend/src/pages/Journals/Journals.tsx

frontend/DANG-787: select box 데이터 바인딩 문제 해결

---

backend/src/journals/dtos/journals-create.dto.ts
backend/src/journals/journals.service.ts
backend/src/today-walk-time/today-walk-time.service.ts

산책일지 생성시 today_walk_time 업데이트하도록 변경하였습니다.
- 예시
- 예시

backend/DANG-789: 산책일지 생성시 today_walk_time 업데이트하도록 변경

---

frontend/src/components/journals/JournalCard.tsx
frontend/src/components/walk/Map.tsx
frontend/src/models/window.d.ts
frontend/src/pages/Camera.tsx
frontend/src/typed/window.d.ts

산책일지 디테일 페이지 이동시 state 포함
refactor wiondow interface
- 예시
- 예시

frontend/DANG-797: 산책일지 디테일 페이지 이동시 state 포함

---

backend/src/journals/journals.service.ts

산책일지 수정에서 journals-photos 테이블에 해당하는 레코드가 없어 404 entity not found 에러를 던지는 현상 발생해
산책일지 생성시 photoUrl이 없어도 journals-photos 테이블에 새 레코드 생성하도록 변경했습니다.
- 예시
- 예시

backend/DANG-794: 산책일지 생성시 photoUrl이 없어도 journals-photos 테이블에 새 레코드 생성

---

frontend/src/App.tsx
frontend/src/components/NavbarProvider.tsx
frontend/src/index.tsx

feat: NavbarProvider 적용
- 예시
- 예시

frontend/DANG-800: NavbarProvider 적용

---

frontend/src/App.tsx
frontend/src/components/NavbarProvider.tsx

NavbarProvider에 LoginAlertBottomSheet, OauthLoginBottomSheet 이사
- 예시
- 예시

frontend/DANG-801: NavbarProvider에 LoginAlertBottomSheet, OauthLoginBottomSheet 이사

---

frontend/src/pages/Join.tsx

refactor: 강아지 등록완료 버튼 연타시 여러번 등록되는 버그 픽스
- 예시
- 예시

frontend/DANG-802: 강아지 등록완료 버튼 연타시 여러번 등록되는 버그 픽스

---

frontend/src/hooks/useAuth.ts

refactor: 회원탈퇴시 무한루프 오류 버그 픽스
- 예시
- 예시

frontend/DANG-807: 회원탈퇴시 무한루프 오류 버그 픽스

---

backend/src/common/database/database.module.ts

산책일지 상세 조회 배포 환경 버그 수정을 위해 legacySpatialSupport: false 옵션 추가했습니다.
- 예시
- 예시

backend/DANG-806: 산책일지 상세 조회 배포 환경 버그 수정을 위해 legacySpatialSupport: false 옵션 추가

---

.github/workflows/backend_ci.yaml
backend/package.json

변경 내용:
- package.json에 새로운 스크립트 test:only-changed 추가
- backend_ci.yaml 에서 기존 test 스크립트를 test:only-changed 스크립트로 변경
- 예시
- 예시

backend/DANG-808: 테스트 실행 최적화-변경된 파일만 테스트하기

---

frontend/src/pages/Join.tsx

refactor: 강아지 등록버튼 연타시 여러개 등록 버그 픽스2
- 예시
- 예시

frontend/DANG-809: 강아지 등록버튼 연타시 여러개 등록 버그 픽스2

---

Makefile
README.md

maraidb와 mysql 차이점으로 종종 에러가 발생해 RDS에 사용하는 mysql로
변경하였습니다.
- 예시
- 예시

infra/DANG-810: Local환경에 Docker Image를 Mariadb를 Mysql로 변경하라

---

frontend/src/index.tsx
frontend/src/pages/Walk.tsx

frontend/DANG-510: home 화면 산책화면 스크롤 문제 해결

---

frontend/src/App.tsx
frontend/src/components/NavbarProvider.tsx
frontend/src/components/journals/CustomCalendar.tsx
frontend/src/hooks/useAuth.ts
frontend/src/hooks/useJournals.ts
frontend/src/pages/Journals/Journals.tsx

frontend/DANG-816: token 비동기 문제 해결

---

frontend/src/pages/Health.tsx

frontend/DANG-824: vercel 배포 하기

---

frontend/src/api/dogs.ts
frontend/src/hooks/useDog.ts
frontend/src/pages/DogProfile.tsx
frontend/src/pages/Profile.tsx

refactor: Avatar 수정에 관한 관련코드 수정
- 예시
- 예시

frontend/DANG-829: Avatar 수정에 관한 관련코드 수정

---

frontend/src/pages/DogProfile.tsx
frontend/src/utils/time.ts

feat: 초 단위 data를 hh:mm:ss 형식으로 변환
- 예시
- 예시

frontend/DANG-833: 초 단위 data를 hh:mm:ss 형식으로 변환

---

frontend/src/classes/Distance.test.ts
frontend/src/classes/Distance.ts
frontend/src/components/walk/WalkInfo.tsx
frontend/src/pages/DogProfile.tsx
frontend/src/utils/geo.ts

frontend/DANG-828: 거리 km로 바꾸고 Distance클래스로 관련 부분 수정

---

frontend/src/classes/Distance.ts
frontend/src/components/journals/JournalCard.tsx
frontend/src/hooks/useGeolocation.ts

frontend/DANG-834: 거리 증가하지 않는 문제 해결

---

frontend/src/hooks/useGeolocation.ts
frontend/src/utils/geo.test.ts

frontend/DANG-837: 거리 Offset추가

---

frontend/src/hooks/useGeolocation.ts

frontend/DANG-837: startPostiion 수정

---

frontend/src/hooks/useGeolocation.ts

frontend/DANG-839: change offset distance to 1

---

frontend/src/hooks/useDog.ts
frontend/src/pages/DogProfile.tsx
frontend/src/pages/Join.tsx
frontend/src/pages/Profile.tsx

refactor: 강아지 수정시 사진변경없이 수정시 버그 픽스
- 예시
- 예시

frontend/DANG-840: 강아지 수정시 사진변경없이 수정시 버그 픽스

---

frontend/src/hooks/useGeolocation.ts

frontend/DANG-839: watchPostion부분 로직 수정

---

frontend/src/hooks/useGeolocation.ts

frontend/DANG-841: 경로 추가 안되는 문제 해결

---

frontend/src/hooks/useGeolocation.ts

frontend/DANG-842: offset 값 10으로 변경

---

README.md

infra/DANG-844: README 작성하기

---

README.md

- dangdangwalk logo 업데이트 
- 오탈자 및 형식 수정
https://www.notion.so/do0ori/Readme-da4363e3e90d4e60b2fe75a38362fb9d
- 예시
- 예시

infra/DANG-846: Readme 로고 변경 및 오탈자 수정

---

backend/src/journal-photos/journal-photos.service.ts
backend/src/journals/journals.controller.ts
backend/src/journals/journals.service.ts

산책일지 삭제시 S3에서도 사진 삭제되도록 변경하였습니다.
- 예시
- 예시

backend/DANG-847:  산책일지 삭제시 S3에서 사진 삭제

---

frontend/src/pages/DogProfile.tsx
frontend/src/pages/Profile.tsx

refactor: 마이페이지가 강아지 프로필페이지 높이에 맞춰 높이가 늘어나는 문제 해결
- 예시
- 예시

frontend/DANG-851: 마이페이지가 강아지 프로필페이지 높이에 맞춰 높이가 늘어나는 문제 해결

---

backend/src/dog-walk-day/dog-walk-day.service.ts
backend/src/journals/journals.service.ts
backend/src/today-walk-time/today-walk-time.service.ts

산책일지 삭제시 하루 산책량, 산책 횟수도 되돌리도록 변경했습니다
+, - 연산만 달라지는 부분은 함수로 전달하도록 해 중복을 방지했습니다
- 예시
- 예시

backend/DANG-850: 산책일지 삭제시 하루 산책량, 산책 횟수도 되돌리기

---

backend/src/s3/s3.controller.ts
frontend/src/App.tsx
frontend/src/components/NavbarProvider.tsx
frontend/src/components/journals/CustomCalendar.tsx
frontend/src/hooks/useAuth.ts
frontend/src/hooks/useJournals.ts
frontend/src/pages/Journals/Journals.tsx

- DTO로 만들정도는 아니라 그냥 `ParseArrayPipe` 사용
- `s3.service.ts`에 있는 `BUCKET_NAME`은 환경변수로 관리하는 것이 좋아보임 → 추후 논의
https://www.notion.so/do0ori/S3-Validation-4b61d70dc69741f4a5771c854ba77e62
- 예시
- 예시

backend/DANG-854: S3에 Validation 추가

---

README.md

- 기술 스택 이미지 교체
- Readme 구조 정리
- Trouble Shooting 및 ERD는 Wiki로 옮김
https://www.notion.so/do0ori/Readme-1-132d9c3b0b0e4e20a7298d7f76161090
- 예시
- 예시

backend/DANG-856: 키워드 부분 삭제, 개요 및 시작 가이드 추가

---

frontend/vercel.json

Storybook 배포
https://www.notion.so/do0ori/Storybook-4a72b13c3c57495eb1b0bd58c057f4a1?pvs=4
- 예시
- 예시

frontend/DANG-475: Storybook 배포

---

backend/README.md

- NestJS 기반 백엔드 애플리케이션 소개 및 실행 방법 안내
- 로컬 개발 환경에서 MySQL 데이터베이스 설정 방법 설명
- 관련 참고 자료 링크 추가
- https://www.notion.so/do0ori/Getting-Started-4003e4f715f44a0080eac25b03d4859d?pvs=4
- 예시
- 예시

backend/DANG-870: 백엔드 시작 가이드 추가하라

---

frontend/README.md

frontend/DANG-858: readme 초안 작성

---

README.md

env 파일에 관련 key-value 값을 추가해주어야 하기 때문에 필수 작업이다.
https://www.notion.so/do0ori/Readme-Requirements-OAuth-2919dded9300444483be9c0e0ec32f7c
- 예시
- 예시

backend/DANG-871: Requirements에 wiki home에 작성한 OAuth 사전 작업 링크 추가

---

README.md

https://www.notion.so/do0ori/Readme-Sequence-Diagram-5fb241fb49a148ec9ae18f5ad4db5dfe
- 예시
- 예시

backend/DANG-872: Sequence Diagram (로그인, 산책) 추가

---

frontend/vercel.json

잘못된 스토리북 배포
https://www.notion.so/do0ori/86a8d68860aa4cdcb7a271c2ecb3e949?pvs=4
- 예시
- 예시

frontend/DANG-876: 잘못된 스토리북 배포

---

frontend/src/api/http.ts
frontend/src/hooks/useAuth.ts
frontend/src/hooks/useDog.ts
frontend/src/pages/Join.tsx

refactor: header token 비동기 이슈 해결
- 예시
- 예시

frontend/DANG-884: header token 비동기 이슈 해결

---

README.md

infra/DANG-885: Readme 이모지 제목 한칸 띄우기

---

frontend/src/App.tsx
frontend/src/components/NavbarProvider.tsx
frontend/src/hooks/useAuth.ts
frontend/src/pages/Home.tsx
frontend/src/store/authStore.ts

refactor: zustand로 로그인 상태 관리
- 예시
- 예시

frontend/DANG-890: zustand로 로그인 상태 관리

---

docs/api/delete.yaml
docs/api/upload.yaml
docs/auth/deactivate.yaml
docs/auth/login.yaml
docs/auth/logout.yaml
docs/auth/token.yaml
docs/auth/users.yaml
docs/dogs/default.yaml
docs/dogs/id-statistics.yaml
docs/dogs/id.yaml
docs/dogs/statistics.yaml
docs/dogs/walk-available.yaml
docs/dogs/walks-start.yaml
docs/dogs/walks-stop.yaml
docs/journals/default.yaml
docs/journals/id.yaml
docs/openapi.yaml

추가/수정된 API에 대한 swagger yaml 파일을 작성했습니다. 
- 예시
- 예시

backend/DANG-874: swagger API 문서 작성

---

README.md

infra/DANG-893: 세팅 → 설정으로 변경, 산책 이모지 wiki와 통일

---

backend/src/main.ts

- swagger 배포 origin을 설정에 추가해서 CORS 오류 해결하기
https://www.notion.so/do0ori/swagger-origin-CORS-48280965f56b45908ea0a5aa9ba97f4f
- 예시
- 예시

backend/DANG-894: Swagger 문서 배포 origin을 CORS 설정에 추가

---

frontend/src/pages/DogProfile.tsx

refactor: 강아지 정보 총 거리 단위 수정
- 예시
- 예시

frontend/DANG-895: 강아지 정보 총 거리 단위 수정

---

README.md

infra/DANG-896: Wiki section 추가

---

README.md
backend/README.md
frontend/README.md

- Readme 형식 통일
- 메인 Readme 주요 기능 소개 업데이트
https://www.notion.so/do0ori/Backend-Frontend-Readme-8a403a717fd942659fdb6d7021d0af35
- 예시
- 예시

infra/DANG-900: Backend/Frontend Readme 수정

---

frontend/README.md

- Frontend logo를 추가했는데 href랑 alt를 변경하지 않고 올려버려서 수정했다.
https://www.notion.so/do0ori/Frontend-Readme-logo-link-670e4c9bfbaa4f19ba3915664c73cbc4
- 예시
- 예시

infra/DANG-901: Frontend Readme logo link 수정

---

frontend/src/api/auth.ts
frontend/src/api/dogs.ts
frontend/src/hooks/useDog.ts
frontend/src/pages/Profile.tsx

비로그인 상태에서 호출되는 profile, 강아지 목록 api 호출하지 않기
- 예시
- 예시

frontend/DANG-906: 비로그인 상태에서 호출되는 profile, 강아지 목록 api 호출하지 않기

---

backend/src/app.controller.ts
backend/src/app.module.ts
backend/src/app.service.ts
backend/src/breed/breed.service.ts
backend/src/dog-walk-day/dog-walk-day.service.ts
backend/src/dogs/dogs.service.ts
backend/src/excrements/excrements.service.ts
backend/src/journal-photos/journal-photos.service.ts
backend/src/journals-dogs/journals-dogs.service.ts
backend/src/journals/journals.service.ts
backend/src/s3/s3.service.ts
backend/src/today-walk-time/today-walk-time.service.ts
backend/src/users-dogs/users-dogs.service.ts
backend/src/users/users.service.ts
backend/src/walk/walk.service.ts

- Repository 내부에서만 사용되는 method의 경우 private으로 설정
- Repository 내부에서만 사용되는 DB query method는 직접 repository 사용
- 각 service 파일에서 사용되지 않는 코드 제거
https://www.notion.so/do0ori/f618a26f42514c5d961ca79f2f65b7fc
- 예시
- 예시

backend/DANG-907: 사용되지 않는 코드 제거

---

frontend/src/pages/Join.tsx

refactor: 강아지 추가 등록시 마지막 버튼에 “등록 완료”
- 예시
- 예시

frontend/DANG-919: 강아지 추가 등록시 마지막 버튼에 “등록 완료”

---

backend/package.json

기존 lint 설정이 되어 있어 추가 된 lint를 제거했습니다.
- 예시
- 예시

backend/DANG-922: lint script를 제거하라

---

frontend/src/api/http.ts

refactor: http.ts 콘솔로그 제거
- 예시
- 예시

frontend/DANG-928: http.ts 콘솔로그 제거

---

backend/src/common/database/database.module.ts

- Breed entity만 문제가 있는 줄 알았으나 e2e test 시 다른 entity도 같은 오류가 발생했다. (#621)
- 경로가 잘못된 것 같아 test 환경에서는 entities 경로를 dist가 아니라 src로 바꾸어주니 잘 동작한다.
https://www.notion.so/do0ori/e2e-test-EntityMetadataNotFoundError-5b0a43ac4356489d90ccd2dce4114621
- 예시
- 예시

backend/DANG-929: e2e test 실행 시 EntityMetadataNotFoundError 해결하기

---

frontend/src/constants/keys.ts
frontend/src/hooks/useBreed.ts

refactor: 견종목록 비동기 문제 해결
- 예시
- 예시

frontend/DANG-930: 견종목록 비동기 문제 해결

---

frontend/src/api/auth.ts
frontend/src/hooks/useAuth.ts

refactor: 비로그인상태에서 호출하는 api들 queryOption: enabled 로 리팩토링
- 예시
- 예시

frontend/DANG-931: 비로그인상태에서 호출하는 api들 queryOption: enabled 로 리팩토링

---

backend/src/utils/date.util.spec.ts
backend/src/utils/date.util.ts
backend/src/utils/hash.util.spec.ts

backend/DANG-916: 테스트 코드 수정

---

frontend/src/components/home/AvailableDogCheckList.tsx
frontend/src/components/walk/DogFeceAndUrineCheckList.tsx
frontend/src/hooks/useWalkAvailabeDog.ts
frontend/src/hooks/useWalkingDogs.ts
frontend/src/pages/Home.tsx
frontend/src/pages/Walk.tsx
frontend/src/utils/check.test.ts
frontend/src/utils/check.ts

frontend/DANG-914: check util 추가

---

backend/src/breed/breed.spec.ts
backend/src/dog-walk-day/dog-walk-day.spec.ts
backend/src/dogs/dogs.spec.ts
backend/src/journals/journals.spec.ts
backend/src/utils/hash.util.spec.ts
backend/test/breed.e2e-spec.ts

```bash
$ npm run test:e2e -- --testPathPattern=test/breed.e2e-spec.ts
> cross-env NODE_ENV=test jest --config ./test/jest-e2e.json --maxWorkers=1 --testPathPattern=test/breed.e2e-spec.ts
PASS  test/breed.e2e-spec.ts (6.932 s)
BreedController (e2e)
/breeds (GET)
견종 목록 가져오기 요청을 보내면
√ 200 상태 코드와 견종 목록을 반환해야 한다. (38 ms)
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        7.038 s, estimated 8 s
Ran all test suites matching /test\\breed.e2e-spec.ts/i.
```
https://www.notion.so/do0ori/breed-e2e-test-6124c408447c4348a88c1a2e92c9ae97
- 예시
- 예시
이에 따라 코드가 실행되는 순간에 실행이 …

backend/DANG-937: breed e2e test 코드 작성

---

frontend/src/components/home/AvailableDogCheck.tsx
frontend/src/components/home/AvailableDogCheckList.tsx
frontend/src/components/home/WeatherInfo.tsx
frontend/src/components/walk/DogFeceAndUrineCheckList.tsx
frontend/src/components/walk/WalkHeader.tsx
frontend/src/components/walk/WalkInfo.tsx
frontend/src/hooks/useWalkAvailabeDog.ts
frontend/src/index.css
frontend/src/pages/Home.tsx
frontend/src/pages/Walk.tsx

frontend/DANG-935: 홈화면 산책화면 스타일 오류수정 및 오타 수정

---

backend/src/s3/__mocks__/s3.service.ts
backend/test/test-utils.ts

s3 service의 경우 외부 api에 의존하기 때문에 mock을 작성했다.
https://www.notion.so/do0ori/s3-mock-1b8d6ac6fcab40d78ae22e989ff2088f
- 예시
- 예시

backend/DANG-941: s3 service mock 작성

---

frontend/src/api/auth.ts
frontend/src/api/breed.ts
frontend/src/api/dog.ts
frontend/src/api/http.ts
frontend/src/components/DeactivateModal.tsx
frontend/src/components/NavbarProvider.tsx
frontend/src/constants/keys.ts
frontend/src/hooks/useAuth.ts
frontend/src/hooks/useBreed.ts
frontend/src/hooks/useDogsStatistic.ts
frontend/src/pages/Join/index.tsx
frontend/src/pages/MyPage/index.tsx
frontend/src/pages/OauthCallback.tsx
frontend/src/store/authStore.ts

refactor: auth 관련 컨벤션 정리
- 예시
- 예시

frontend/DANG-940: auth 관련 컨벤션 정리

---

Makefile

Make file에 e2e 테스트 데이터베이스를 추가했습니다.
- 예시
- 예시

backend/DANG-923: Make file e2e 테스트 실행 데이터베이스를 추가하라

---

frontend/src/api/dog.ts
frontend/src/api/journal.ts
frontend/src/components/BreedSearch.tsx
frontend/src/components/journals/CompanionDogSection.tsx
frontend/src/hooks/useDog.ts
frontend/src/hooks/useWalkAvailabeDog.ts
frontend/src/models/dog.ts
frontend/src/pages/Join/DogBasicInfo.tsx
frontend/src/pages/Join/DogDetailInfo.tsx
frontend/src/pages/Join/index.tsx
frontend/src/pages/Journals/index.tsx
frontend/src/pages/MyPage/DogDetail.tsx
frontend/src/pages/MyPage/index.tsx

frontend/DANG-947: dog 컨벤션 정리

---

frontend/src/api/dog.ts
frontend/src/components/BreedSearch.tsx
frontend/src/components/DeleteDogModal.tsx
frontend/src/hooks/useDog.ts
frontend/src/pages/Join/Agreements.tsx
frontend/src/pages/Join/DogBasicInfo.tsx
frontend/src/pages/Join/DogDetailInfo.tsx
frontend/src/pages/Join/index.tsx
frontend/src/pages/MyPage/DogDetail.tsx
frontend/src/pages/MyPage/index.tsx

강아지 정보 setData함수를 기존엔 자식 컴포넌트에서 set -> 최상위 부모 컴포넌트에서 핸들링
- 예시
- 예시

frontend/DANG-950: 강아지 setData 함수 → 최상단에서 handleChange함수로 변경

---

frontend/src/constants/index.ts
frontend/src/constants/keys.ts
frontend/src/constants/time.ts
frontend/src/hooks/useAddressAndAirgrade.ts
frontend/src/hooks/useAuth.ts
frontend/src/hooks/useBreed.ts
frontend/src/pages/Join/index.tsx

리액트 쿼리에서 사용되는 시간을 상수화 시킴
- 예시
- 예시

frontend/DANG-951: 리액트쿼리 시간 관련 상수화

---

frontend/src/api/http.ts
frontend/src/hooks/useAuth.ts

refactor: queryKey : auth 통합
- 예시
- 예시

frontend/DANG-952: queryKey : auth 통합

---

backend/src/users/users.service.spec.ts

`createIfNotExists` method에서 `generateUniqueNickname`을 통해 중복되지 않는 nickname을 생성할 때 탈출 조건이 만들어지지 않아 발생한 문제였다. `mockResolvedValueOnce` method를 사용해 nickname 생성 시에는 findOne method가 `null`을 반환해 탈출 조건을 만들어주고 그 후에는 `mockUser`를 반환하도록 했다.
```bash
$ npm run test -- --testPathPattern=users.service.spec.ts
> nest-js-example@0.0.1 test
> cross-env NODE_ENV=test jest --testPathPattern=users.service.spec.ts
PASS  src/users/users.service.spec.ts
UsersService
findOne                                                                                                                                                                                                       
사용자가 존재 할 때
√ 사용자 정보를 반환해야 한다. (11 ms)
사용자가 존재하지 않을 때
√ NotFoundException 예외를 던져야 한다. (6 ms)
updateAndFindOne
사용자 토큰 정보가 주어지고 사용자가 존재하면
√ 사용자 정보를 …
```

backend/DANG-954: createIfNotExists test case에서 발생하는 heap out of memory error 해결하기

---

.github/workflows/change_ticket_status_done.yaml

Related to: #418
https://www.notion.so/do0ori/change_ticket_status_done-check_error-380b003d2f5e46b2ba90e991696500f6
- 예시
- 예시

infra/DANG-955: change_ticket_status_done script에서 check_error 함수 삭제

---

frontend/src/pages/MyPage/DogDetail.tsx
frontend/src/pages/MyPage/index.tsx

as-is: 강아지 정보 수정시 DogDetial->MyPage로 이동
to-be: 정보 수정시 DogDetail에 머물며 수정된 data 반영되여 DogDetail에 렌더링 후 toast 띄어주기
- 예시
- 예시

frontend/DANG-957: 강아지 정보 수정시 mypage로 넘어가지않고 dogDetail 페이지에 머물며 update값 보여주기

---

frontend/src/components/commons/Toast.tsx
frontend/tailwind.config.js

feat: toast: face-out animation 추가
- 예시
- 예시

frontend/DANG-956: toast: face-out animation 추가

---

frontend/.eslintrc.json
frontend/.prettierrc
frontend/package-lock.json
frontend/package.json
frontend/src/components/commons/Toast.tsx
frontend/tailwind.config.js

코드 수정 후 저장하고 commit했을때 custom tailwind theme 관련 코드만 prettier가 풀리는 문제 해결
- 예시
- 예시

frontend/DANG-958: custom tailwind theme eslint error 해결

---

frontend/.eslintrc.json
frontend/package-lock.json
frontend/package.json
frontend/src/components/BreedSearch.tsx
frontend/src/components/ImageCropper.tsx
frontend/src/components/LoginAlertModal.tsx
frontend/src/components/commons/BottomSheet.tsx
frontend/src/components/commons/Button.tsx
frontend/src/components/commons/Checkbox.tsx
frontend/src/components/commons/DefaultProfileImage.tsx
frontend/src/components/commons/Spinner.tsx
frontend/src/components/home/DayIcon.tsx
frontend/src/components/home/Progressbar.tsx
frontend/src/components/home/RegisterCard.tsx
frontend/src/components/journals/AddImageButton.tsx
frontend/src/components/journals/CustomCalendar.tsx
frontend/src/components/journals/JournalCard.tsx
frontend/src/components/walk/StopToast.tsx
frontend/src/pages/Join/DogBasicInfo.tsx
frontend/src/pages/Join/DogDetailInfo.tsx
frontend/src/pages/Join/PetOwner.tsx
frontend/src/pages/Join/index.tsx
frontend/src/pages/Journals/CreateForm.tsx
frontend/src/pages/Journals/Detail.tsx
frontend/src/pages/MyPage/index.tsx

refactor: tailwind eslint fix
- 예시
- 예시

frontend/DANG-959: tailwind eslint fix

---

frontend/src/utils/time.ts

time.ts regular -> arrow function
- 예시
- 예시

frontend/DANG-963: time.ts regular -> arrow function

---

frontend/src/components/commons/Modal.tsx

Modal 컴포넌트의 스타일 수정
https://www.notion.so/do0ori/Modal-3f5be1ffcd8c4d3a95693f65b71692a9?pvs=4
- 예시
- 예시

frontend/DANG-964: Modal 컴포넌트의 스타일 수정

---

frontend/src/pages/Journals/CreateForm.tsx

산책기록 저장 페이지의 스타일 수정
https://www.notion.so/do0ori/53a4b7a90ac94e8dbd2aebc0755c0d9a?pvs=4
- 예시
- 예시

frontend/DANG-965: 산책기록 저장 페이지의 스타일 수정

---

frontend/src/pages/Journals/Detail.tsx

산책기록 상세 페이지의 스타일 수정
https://www.notion.so/do0ori/cd8784d9e0ee45338bbf92c8b7cb6611?pvs=4
- 예시
- 예시

frontend/DANG-966: 산책기록 상세 페이지의 스타일 수정

---

frontend/src/components/Navbar.tsx
frontend/src/components/home/RegisterCard.tsx
frontend/src/components/journals/Navbar.tsx
frontend/src/hooks/useAuth.ts
frontend/src/index.tsx
frontend/src/pages/Join/Agreements.tsx
frontend/src/pages/Join/index.tsx
frontend/src/pages/MyPage/DogDetail.tsx
frontend/src/pages/MyPage/index.tsx
frontend/src/utils/oauth.ts

refactor: 네이밍 수정 : Join →SignUp, Profile → MyPage
- 예시
- 예시

frontend/DANG-972: 네이밍 수정 : Join →SignUp, Profile → MyPage

---

backend/src/main.ts

- https://dangdang-walk-phi.vercel.app를 CORS 허용 origin에 추가
- 해당 origin에서의 API 요청 허용
- 예시
- 예시

backend/DANG-976: CORS 허용 origin 추가

---

backend/src/main.ts

- 더 이상 필요하지 않은 origin을 CORS 허용 목록에서 제거하여 보안 강화
- 예시
- 예시

backend/DANG-977: CORS 허용 origin 목록에서 https://dangdang-walk.vercel.app 제거

---

backend/src/main.ts

backend/DANG-978: 배포용 테스트 추가

---

frontend/src/utils/oauth.ts

frontend/DANG-980: goole 인가코드 url 수정

---

frontend/src/api/http.ts
frontend/src/components/ImageCropper.tsx
frontend/src/constants/keys.ts

refactor: tokenKeys, storageKeys 정리
- 예시
- 예시

frontend/DANG-984: tokenKeys, storageKeys 정리

---

frontend/src/pages/MyPage/DogDetail.tsx

기존 강아지 사진이 있는상태에서 사진이외의 정보 수정했을때 사진이 없어지는 문제 해결
- 예시
- 예시

frontend/DANG-985: 기존 강아지 사진이 있는상태에서 사진이외의 정보 수정했을때 사진이 없어지는 문제 해결

---

frontend/src/api/dog.ts
frontend/src/pages/MyPage/DogDetail.tsx

refactor: 강아지 사진 저장안되는 문제 해결
- 예시
- 예시

frontend/DANG-986: 강아지 사진 저장안되는 문제 해결

---

backend/src/main.ts

https://dangdang-walk-phi.vercel.app를 https://dangdang-walk.xyz로 변경하여 CORS 허용 origin 업데이트 변경된 origin에서의 API 요청 허용
- 예시
- 예시

backend/DANG-987: CORS 허용 origin 변경

---

.github/workflows/backend_deploy.yaml
backend/src/statistics/statistics.service.ts

- getDogWalkCnt 함수에서 데이터 불일치 예외 발생 시 로그에 자세한 정보 추가
- 오늘 산책량, 주간 산책량 배열 길이 불일치 시 해당 정보를 로그에 명시하여 디버깅 용이성 향상
- Docker 이미지 이름을 dangdang-api에서 dangdangwalk으로 변경
- 예시
- 예시

infra/DANG-995: 산책 통계 조회 시 데이터 불일치 예외 처리 개선 및 docker image 변경

---

backend/src/statistics/statistics.service.ts

infra/DANG-997: 배포용 lint 정리하기

---

backend/src/statistics/statistics.service.ts

infra/DANG-998: 배포용 테스트

---

backend/src/main.ts
docs/dogs/default.yaml
docs/dogs/id-statistics.yaml
docs/images/delete.yaml

공용 계정인 dangdangwalk로 repository 소유권을 이전하면서 swagger 배포도 해당 계정으로 하기 위해 CORS 허용 origin 업데이트
https://www.notion.so/do0ori/Swagger-CORS-584ab4be3d334d2989779a4d19c7e7de
- 예시
- 예시

backend/DANG-1003: Swagger CORS 에러 해결하기

---

.github/workflows/backend_deploy.yaml
backend/src/statistics/statistics.service.ts

- 빌드/배포 전 기존 ECR 이미지 삭제 단계 추가
- run-backend.sh 스크립트에 ECR 레포지토리 정보 전달
- getDogStatistics 함수에서 startDate, endDate 변수 선언 스타일 통일 (가독성 향상)
- 예시
- 예시

infra/DANG-1004: 빌드/배포 프로세스 개선 및 변수 선언 스타일 통일

---

.github/workflows/backend_deploy.yaml

-ECR 레포지토리에 이미지가 없을 때 발생하는 오류 수정
- 이미지가 없으면 삭제를 건너뛰고 진행하도록 조건문 추가
- 스크립트 오류 수정
- if 조건문의 조건식 수정 ([[ -z $IMAGE_TAG ]] -> [[ -z "$IMAGE_TAG" ]])
- else 문 추가하여 이미지가 존재하는 경우에만 삭제 실행
- break 대신 echo 명령어를 사용하여 이미지 미존재 시 메시지 출력
- 조건문에 fi 추가하여 if-else 문 종료
- 예시
- 예시

infra/DANG-1005: ECR 이미지 삭제 단계 오류 수정

---

backend/src/dogs/dogs.service.ts

backend/DANG-1007: docker env 속성 변경 후 재배포

---

backend/src/journals-dogs/journals-dogs.service.ts

backend/DANG-1008: ECR 재배포

---

backend/src/dog-walk-day/dog-walk-day.spec.ts

backend/DANG-1009: Blue-Green 배포 전략 확인하기

---

backend/src/s3/s3.service.ts
backend/test/s3.e2e-spec.ts

버킷 이름을 dangdangwalk->dangdangbucket으로 변경했습니다
- 예시
- 예시

backend/DANG-1011:  버킷 이름 변경

---

.github/workflows/backend_deploy.yaml
backend/src/breed/breed.spec.ts

infra/DANG-1014: Github ShellScript 인자값 변경하기

---

frontend/src/components/journals/JournalCard.tsx

frontend/DANG-1015: journal page 강아지 사진 경로 오류 수정

---

docs/openapi.yaml

https://www.notion.so/do0ori/swagger-server-url-7f06285660624a9c98f874fc1ea8f8c9
- 예시
- 예시

backend/DANG-1019: server 이전 후 바뀐 url로 업데이트

---

backend/src/dog-walk-day/dog-walk-day.service.spec.ts
backend/src/dog-walk-day/dog-walk-day.service.ts
backend/src/fixtures/dogWalkDays.fixture.ts
backend/src/journals/journals.service.ts

backend/DANG-1020: DogWalkDayService 테스트 코드 및 리팩터링 하기

---

backend/src/common/database/database.module.ts

https://www.notion.so/do0ori/query-log-c68106eb46ee4b3c853abb1706dc740e
- 예시
- 예시

backend/DANG-1022: query logging을 배포 환경이 아닐 때만 사용하도록 수정

---

frontend/src/components/ImageCropper.tsx
frontend/src/pages/MyPage/DogDetail.tsx

refactor: 강아지 사진 포맷 jpeg로 수정 및 압축화
- 예시
- 예시

frontend/DANG-1024: 강아지 사진 포맷 jpeg로 수정 및 압축화

---

frontend/src/constants/time.ts
frontend/src/hooks/useAuth.ts
frontend/src/hooks/useBreed.ts
frontend/src/hooks/useDog.ts

breed 목록, 강아지 목록 조회에 캐싱 옵션 적용
- 예시
- 예시

frontend/DANG-1026: Get 함수 캐싱 적용

---

frontend/src/store/authStore.ts
frontend/src/store/cropStore.ts

authStore, cropStore에 devtools 적용
- 예시
- 예시

frontend/DANG-1027: authStore, cropStore에 devtools 적용

---

frontend/src/components/BreedSearch.tsx
frontend/src/components/OAuthButton.tsx
frontend/src/components/home/DogCard.tsx
frontend/src/components/journals/JournalCard.tsx
frontend/src/pages/Join/DogDetailInfo.tsx
frontend/src/pages/MyPage/DogDetail.tsx
frontend/src/pages/MyPage/index.tsx

1차적으로 클릭이벤트가 발생하는 곳에 scale 옵션 추가
- 예시
- 예시

frontend/DANG-1031:  클릭이벤트가 발생하는 곳에 scale 옵션 추가

---

frontend/src/hooks/useAuth.ts

useGetRefreshToken enabled 옵션 삭제
- 예시
- 예시

frontend/DANG-1034: useGetRefreshToken enabled 옵션 삭제

---

frontend/src/components/home/WeatherInfo.tsx
frontend/src/hooks/useWeather.ts
frontend/src/pages/Home.tsx
frontend/src/pages/Walk.tsx

frontend/DANG-989: 산책시 뒤로가기 눌렀을때 생기는 에러 수정 및 날씨 블링크 이슈 수정

---

frontend/src/hooks/useAuth.ts

refactor: 로그아웃 Onsettled에서 로그아웃 뒷처리
- 예시
- 예시

frontend/DANG-1037: 로그아웃 Onsettled에서 로그아웃 뒷처리

---

backend/src/common/logger/winstonLogger.service.ts

- test 환경에서는 최소한의 transport인 Console을 silent option과 함께 사용한다.
- prod 환경에서는 file에 log를 저장하고 그 외의 환경에서는 file에 log도 저장하고 console에도 출력한다.
https://www.notion.so/do0ori/test-logging-1379056646c24c4d8ad3588187437274
`EPERM: operation not permitted, open 'home\dangdang-walk\backend\log\XXXX-XX-XX.log'` 에러 해결
- 예시
- 예시

backend/DANG-1032: test 환경에서는 logging을 출력하거나 파일에 저장하지 않도록 수정

---

frontend/src/api/http.ts

refactor: interceptor에서 token api 401일때 로그아웃 처리
- 예시
- 예시

frontend/DANG-1039: interceptor에서 token api 401일때 로그아웃 처리

---

backend/src/fixtures/journals.fixture.ts
backend/src/fixtures/statistics.fixture.ts

- `Logitude is out of range in function st_geomfromtext. It must be within (-180.000000, 180.000000].` 오류 해결하기
- MySQL에서는 좌표 값이 위도는 (-90, 90], 경도는 (-180, 180]의 범위 내에 있어야 한다고 한다.
- 범위 내의 값을 가지도록 수정해주었다.
https://www.notion.so/do0ori/journal-fixture-58b88a945f74489e9e777194bef1b48a
- 예시
- 예시

backend/DANG-1042: journal 관련 fixture에서 위도, 경도 값 수정

---

frontend/src/hooks/useDog.ts

refactor: 강아지 생성시 강아지목록 갱신
- 예시
- 예시

frontend/DANG-1043: 강아지 생성시 강아지목록 갱신

---

backend/src/common/database/database.module.ts
backend/src/common/logger/winstonLogger.service.ts

- 배포 환경에서 info level 이상만 기록하도록 수정했다.
- query log는 test 및 local에서만 기록하도록 수정했고 각 환경별로 적합한 log 파일명을 사용하도록 했다.
- log 파일이 log 폴더 안에 생성되도록 했다.
https://www.notion.so/do0ori/info-level-query-log-test-local-82fbfb32f2a34e3ea77724a1f3f84f78
- 예시
- 예시

backend/DANG-1030: Logging 설정 업데이트

---

frontend/src/pages/MyPage/index.tsx
frontend/src/pages/WebView.tsx

test: WebView 통신 테스트
- 예시
- 예시

frontend/DANG-1044: WebView 통신 테스트

---

frontend/src/pages/WebView.tsx

test: WebView 통신 테스트 2차
- 예시
- 예시

frontend/DANG-1045: WebView 통신 테스트 2차

---

frontend/src/components/CancelRegModal.tsx
frontend/src/pages/Join/DogBasicInfo.tsx
frontend/src/pages/Join/DogDetailInfo.tsx
frontend/src/pages/Join/PetOwner.tsx
frontend/src/pages/Join/index.tsx
frontend/src/pages/MyPage/DogDetail.tsx
frontend/src/pages/MyPage/index.tsx

refactor: 클릭이벤트 있는 버튼에 scale 옵션 추가 2차
- 예시
- 예시

frontend/DANG-1047: 클릭이벤트 있는 버튼에 scale 옵션 추가 2차

---

frontend/src/components/home/WeatherInfo.tsx
frontend/src/hooks/useGeolocation.ts
frontend/src/pages/Home.tsx

위치 정보 없는 상태 추가 및 위치 정보 없을때 경고문 표시
- 예시
- 예시

frontend/DANG-1048: 위치 정보 없는 상태 추가 및 위치 정보 없을때 경고문 표시

---

frontend/src/components/commons/BottomSheet.tsx
frontend/src/components/home/AvailableDogCheckList.tsx
frontend/src/components/home/DogCardList.tsx
frontend/src/components/home/DogStatisticsView.tsx
frontend/src/components/home/RegisterCard.tsx
frontend/src/components/journals/JournalCard.tsx
frontend/src/components/journals/JournalCardList.tsx
frontend/src/hooks/useJournals.ts
frontend/src/pages/Home.tsx
frontend/src/pages/Journals/index.tsx
frontend/src/pages/Walk.tsx
frontend/src/utils/validate.ts

available dog check all 상태 제거
dogStatisticsView로 분리하여 loading 로직 단순화
paveMove로직으로 화면에서 통일
homebottomsheet에 로딩스피너 추가
빈배열 확이하는 validate 유틸 추가
journal 페이지 로딩 추가
- 예시
- 예시

frontend/DANG-992: home refactoring

---

backend/package-lock.json
backend/src/breed/breed.service.ts
backend/src/dog-walk-day/dog-walk-day.service.ts
backend/src/dogs/dogs.service.ts
backend/src/excrements/excrements.service.ts
backend/src/journal-photos/journal-photos.service.ts
backend/src/journals-dogs/journals-dogs.service.ts
backend/src/journals/journals.entity.ts
backend/src/journals/journals.service.ts
backend/src/journals/types/journal-detail.type.ts
backend/src/s3/s3.service.ts
backend/src/statistics/statistics.service.ts
backend/src/today-walk-time/today-walk-time.service.ts
backend/src/users/users.entity.ts
backend/src/users/users.service.ts
backend/src/walk/walk.service.ts

백엔드 팀원이 같이 코드 보며 바꿀 부분 논의한 부분 TODO 주석으로 기록
- 예시
- 예시

backend/DANG-1053: 바꿔야 할 부분 TODO 주석처리

---

backend/src/dogs/dogs.controller.ts
backend/src/journals/journals.controller.ts
backend/src/s3/s3.controller.ts

https://www.notion.so/do0ori/body-true-204-7f93751f10b443ae8b9b042a7c9429d6
API 문서 페이지도 수정 완료
- 예시
- 예시

backend/DANG-1051: 응답으로 true를 반환하는 코드 삭제 및 Http Code 204로 설정

---

frontend/src/components/ImageCropper.tsx
frontend/src/pages/MyPage/DogDetail.tsx

refactor: image crop, 강아지 정보 수정시 spinner 추가
- 예시
- 예시

frontend/DANG-1060: image crop, 강아지 정보 수정시 spinner 추가

---

README.md

https://www.notion.so/do0ori/README-07522fcf92e24263b575673a159f8e36
- 예시
- 예시

backend/DANG-1055: 프로그래머스 최종 발표회 발표 영상 바로가기 README 및 wiki에 추가

---

frontend/src/global.d.ts
frontend/src/pages/MyPage/index.tsx

test: webview 통신 test
- 예시
- 예시

frontend/DANG-1061: webview 통신 test

---

frontend/src/pages/MyPage/index.tsx

frontend/DANG-1062: webview 통신 test 2

---

frontend/src/pages/MyPage/index.tsx

test: webview postMessage에 setTimeout 추가
- 예시
- 예시

frontend/DANG-1064: webview postMessage에 setTimeout 추가

---

frontend/src/pages/MyPage/index.tsx

test: webview 메세지에 고유값 넣어주기
- 예시
- 예시

frontend/DANG-1065: webview 메세지에 고유값 넣어주기

---

frontend/src/pages/MyPage/index.tsx

refactor: Webview postmessage 수정
- 예시
- 예시

frontend/DANG-1067: Webview postmessage 수정

---

frontend/package-lock.json
frontend/package.json
frontend/src/index.css

frontend/DANG-1075: 글자 드래그 막기

---

frontend/.eslintrc.json
frontend/src/api/http.ts
frontend/src/api/weather.ts
frontend/src/components/journals/CustomCalendar.tsx
frontend/src/hooks/useGeolocation.ts
frontend/src/pages/Health.tsx
frontend/src/pages/Home.tsx
frontend/src/pages/Journals/index.tsx

frontend/DANG-1052: eslint no-console 추가 및 home handle bottom sheet refactoring

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx

@babel/plugin-proposal-private-property-in-object 대신 @babel/plugin-transform-private-property-in-object사용하기
- 예시
- 예시

frontend/DANG-1076: @babel/plugin-transform-private-property-in-object 추가

---

backend/src/walk/test.walk.service.ts
backend/src/walk/walk.service.spec.ts
backend/src/walk/walk.service.ts

- WalkService의 getAvailableDogs 메서드에 대한 테스트 코드 작성
- 사용자 ID를 입력받아 사용 가능한 강아지 목록을 반환하는 기능 테스트
- UsersService, DogsService의 관련 메서드를 모킹하여 테스트 환경 구성
- checkAvailableDogs 메서드를 private에서 public으로 변경
- 예시
- 예시

backend/DANG-1078: getAvailableDogs 테스트 케이스 추가

---

frontend/src/components/walk/Map.tsx
frontend/src/hooks/useImageUpload.ts

frontend/DANG-1084: 사진 등록했을때 토스트 보여주는 기능 추가 및 이동시 자동으로 지도 움직이는 기능 제거

---

backend/src/auth/auth.service.spec.ts

backend/DANG-1086: AuthService 테스트코드 의존성 제거 및 비동기 함수 처리

---

backend/test/s3.e2e-spec.ts

api가 200->204로 바뀜에 따라 테스트 코드의 expect도 204로 변경하였습니다.
- 예시
- 예시

backend/DANG-1082: s3 e2e 이미지 삭제 테스트에 대한 expect status 변경

---

frontend/src/App.tsx
frontend/src/components/walk/WalkNavbar.tsx

frontend/DANG-1088: 롱클릭 안드로이드에서 오류 수정 및 디자인 적용

---

frontend/src/components/walk/WalkNavbar.tsx

frontend/DANG-1089: long click time 0.5s에서 1s onContextMenu prevent

---

frontend/src/components/walk/WalkNavbar.tsx

frontend/DANG-1090: long click time 0.5s 1s

---

frontend/src/store/authStore.ts
frontend/src/store/cropStore.ts
frontend/src/store/index.ts
frontend/src/store/loginBottomSheetStore.ts
frontend/src/store/spinnerStore.ts
frontend/src/store/toastStore.ts

스토어에 devtools 적용
https://www.notion.so/do0ori/devtools-22cebe06f22744b38ace45d858d53f66?pvs=4
- 예시
- 예시

frontend/DANG-1094: 스토어에 devtools 적용

---

frontend/src/components/walk/WalkNavbar.tsx

frontend/DANG-1097: 우클릭 막고 모바일에서는컨텍스트에서 실행

---

frontend/src/components/walk/WalkNavbar.tsx

frontend/DANG-1098: contextMenu preventDefault 및 navbar style 수정

---

backend/src/walk/walk.service.spec.ts
backend/test/journals.e2e-spec.ts
backend/test/walk.e2e-spec.ts

테스트 간 독립성을 확보하기 위해 
중복되는 fixture 또한 개별 테스트에서 각각 정의하도록 변경하였습니다. 
- 예시
- 예시

backend/DANG-1099: journals, walk e2e 테스트에서 fixture를 각 테스트에서 정의하도록 변경

---

backend/test/performance/utils/token.util.ts

명령줄에 userId, oauthId, provider, expiresIn 값을 넘겨 원하는 payload를 지정해 token을 발급할 수 있다.
backend 폴더에서 다음과 같이 명령어를 입력해 사용할 수 있다.
```bash
$ ts-node './test/performance/utils/token.util.ts' userId=1 oauthId=1 provider=kakao expiresIn=100y
args={"userId":"1","oauthId":"1","provider":"kakao","expiresIn":"100y"}
userId=1, provider=kakao, expiresIn=100y
> test access token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInByb3ZpZGVyIjoia2FrYW8iLCJpYXQiOjE3MTg5Njc3MzAsImV4cCI6NDg3NDcyNzczMH0.9J6Q5CIW1lJO2lSyupXQDgEei1H5lf-AvkXt8woy9nc
oauthId=1, provider=kakao, expiresIn=100y
> test refresh token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYXV0aElkIjoiMSIsInByb3ZpZGVyIjoia2FrYW8iLCJpYXQiOjE3MTg5Njc3MzAsImV4cCI6NDg3NDcyNzczMH0.pqKLDnEY3n7Kzu9-RZ64o4ZVR250vurm0j0iCUjbJxA
``` …

backend/DANG-1110: 원하는 payload를 가지는 test token을 발급하는 script 작성

---

backend/src/excrements/excrements.service.spec.ts
backend/src/excrements/excrements.service.ts
backend/src/excrements/excrements.spec.ts
backend/src/excrements/fake-excrements.service.ts
backend/src/journals/journals.service.ts

- ExcrementsService의 getExcrementsCount 메서드가 배변 정보를 정확하게 조회하는지 테스트
- 견종, 강아지, 배변 종류별 배변 정보 조회 기능 테스트
- 테스트 데이터(mockExcrements) 추가
- getExcrementsCount로 변경
- 예시
- 예시

backend/DANG-1111: ExcrementsService 테스트 케이스 추가

---

frontend/.prettierignore
frontend/craco.config.cjs
frontend/package-lock.json
frontend/package.json

frontend/DANG-1116: data-testid build시 제거

---

backend/src/app.module.ts
backend/src/common/interceptors/profilingInterceptor.ts

- API method와 url, 응답 속도를 기록한다.
- query별 상세 profile을 기록한다.
- query 횟수는 `log/ormlogs.{env}.log`에서 확인할 수 있지만 이 interceptor는 query별 상세 profile을 확인하기 위해 사용한다.
- `log/query-profiling.log`에 기록된다.
- 환경변수 `ENABLE_PROFILING=true`일 때에만 ProfilingInterceptor가 동적으로 적용되도록 설정했다.
<details><summary>log 예시 (강아지 등록 API)</summary>
```log
>> POST /dogs
API Call Duration: 42ms
Profiles: [
{
"Query_ID": 1,
"Duration": 0.000114,
"Query": "START TRANSACTION",
"Details": [
{
"Status": "starting",
"Duration": "0.000057"
},
{
"Status": "Executing hook on transaction ",
"Duration": "0.000002"
},
{
"Status": "starting",
"Duration": "0.000007"
},
{
"Status": "query end",
"Duration": "0.000005"
},
{
"Status": "closing tables",
"Duration": "0.000002"
},
{
"Status": "freeing items",
"Duration": "0.000035"
},
{
"Status": …
```

backend/DANG-1114: query 분석을 위한 ProfilingInterceptor 작성

---

frontend/src/pages/MyPage/DogDetail.tsx

모바일 환경에서 강아지 상세페이지에 강아지 이름 색상 다르게 나오는 문제 수정
- 예시
- 예시

frontend/DANG-1119: 모바일 환경에서 강아지 상세페이지에 강아지 이름 색상 다르게 나오는 문제 수정

---

frontend/public/index.html

모바일 환경에서 인풋 클릭시 화면 확대되는 현상 막기
-  user-scalable=no // 확대 기능을 사용하지 않습니다.
- maximum-scale=1 // 최대 배율, 크기를 설정합니다.
- 예시
- 예시

frontend/DANG-1120: 모바일 환경에서 인풋 클릭시 화면 확대되는 현상 막기

---

frontend/src/pages/SignUp/DogDetailInfo.tsx

'~의 체중이 궁금해요' 모바일 환경에서 짤리는 문제 해결
- 예시
- 예시

frontend/DANG-1121: '~의 체중이 궁금해요' 모바일 환경에서 짤리는 문제 해결

---

backend/src/statistics/statistics.service.ts
backend/src/today-walk-time/today-walk-time.service.spec.ts
backend/src/today-walk-time/today-walk-time.service.ts

- TodayWalkTimeService의 getWalkTimeList 메서드에 대한 테스트 코드 작성
- 입력된 walkTimeIds 배열에 해당하는 산책 시간 목록 조회 기능 테스트
- 존재하지 않는 walkTimeId에 대한 예외 처리 테스트
- mock 데이터를 활용하여 테스트 환경 구성
- 예시
- 예시

backend/DANG-1115: TodayWalkTimeService 테스트 케이스 추가

---

backend/src/common/interceptors/profilingInterceptor.ts

- profile history가 남아있어 이전 호출시 실행되었던 쿼리에 대한 profile 까지 중복으로 기록되는 문제가 있었습니다. 
- 인터셉터 리턴 전에 히스토리를 초기화하도록 변경하였습니다.
- 예시
- 예시

backend/DANG-1118: profiligInterceptor 리턴 전 profile 히스토리를 삭제하도록 변경

---

backend/src/common/interceptors/profilingInterceptor.ts

- finalize callback에서는 switchMap과 같이 Observable을 기다리는 함수를 사용할 수가 없어서 그냥 initProfiling으로 초기화한다.
- 어차피 DB를 새롭게 시작할 때마다 profiling = 0으로 초기화되므로 괜찮을 것 같다.
https://www.notion.so/do0ori/ProfilingInterceptor-1d73d5ed63054932a4e67ab0279d1b5f
- 예시
- 예시

backend/DANG-1128: finalize를 제거하고 initProfiling을 다시 복원해 비동기 문제 해결

---

backend/src/main.ts

프론트엔드 테스트용 로컬 서버의 주소를 CORS_ORIGIN에 추가했습니다.
- 예시
- 예시

backend/DANG-1132: 프론트엔드 로컬 서버 주소 CORS_ORIGIN에 추가

---

frontend/package.json
frontend/src/components/walk/WalkNavbar.tsx

frontend/DANG-1130: contextmenu event 제거 및 pause icon image 에서 icon으로 변경

---

backend/rest-api/breeds/korean-name.http
backend/rest-api/dogs/dogs.http
backend/rest-api/journals/journals.http
backend/rest-api/statistics/statistics.http
backend/rest-api/walks/available.http
backend/rest-api/walks/start.http
backend/rest-api/walks/stop.http

- 산책 가능한 강아지 목록 조회 (/dogs/walks/available) 요청 예시 추가
- 산책 시작 (/dogs/walks/start) 요청 예시 추가
- 산책 중지 (/dogs/walks/stop) 요청 예시 추가
- 각 요청에 필요한 헤더 정보 (Authorization, Content-Type) 및 바디 데이터 명시
- 예시
- 예시

backend/DANG-1133: REST API 테스트 요청 파일 추가

---

backend/src/utils/ms.util.ts
backend/test/performance/utils/createMockEntity.util.ts
backend/test/performance/utils/random.util.ts

- faker 라이브러리의 코드를 적절히 변형해서 random util 함수들의 가독성을 향상시켰다.
- api의 성능에 영향을 주지 않는 field들은 고정값을 사용하도록 수정했다. 너무 배포 환경을 모방하려고 했던 것 같다.
https://www.notion.so/do0ori/response-time-script-random-faker-5c09533c5a2e4b07838176308ecfa382
- 예시
- 예시

backend/DANG-1142: random util 함수 개선

---

frontend/src/components/dogRegistration/DogRegHeader.tsx
frontend/src/pages/SignUp/DogBasicInfo.tsx
frontend/src/pages/SignUp/DogDetailInfo.tsx
frontend/src/pages/SignUp/PetOwner.tsx

DogRegHeader 컴파운드 컴포넌트 생성 및 적용
- 예시
- 예시

frontend/DANG-1149: DogRegHeader 컴파운드 컴포넌트 생성 및 적용

---

frontend/src/App.tsx
frontend/src/api/http.ts
frontend/src/constants/keys.ts
frontend/src/hooks/useAuth.ts
frontend/src/hooks/useDogStatistic.ts
frontend/src/pages/Journals/CreateForm.tsx
frontend/src/pages/Walk.tsx
frontend/src/store/authStore.ts

as-is : 새로고침했을때 api http header에 토큰이 사라져서 http interceptor에 특정 api 호출시 토큰이 없으면 다시 토큰 발급해오는 로직
to-be:  토큰이 필요한 api에 enabled 속성 또는 토큰을 받아왔을때 호출하려는 api를 실행하도록 리팩토링
- 예시
- 예시

frontend/DANG-1151: token 비동기 처리 리팩토링

---

frontend/src/App.tsx
frontend/src/components/hoc/withAuthenticated.tsx
frontend/src/components/hoc/withMainAuthenticated.tsx
frontend/src/hooks/useDogStatistic.ts
frontend/src/hooks/useJournal.ts
frontend/src/hooks/useJournals.ts
frontend/src/pages/Home.tsx
frontend/src/pages/Journals/CreateForm.tsx
frontend/src/pages/Journals/Detail.tsx
frontend/src/pages/Journals/index.tsx
frontend/src/pages/MyPage/index.tsx
frontend/src/pages/SignUp/index.tsx
frontend/src/pages/Walk.tsx

`withMainAuthenticated.tsx` : Home, MyPage
`withAuthenticated.tsx` : 그 외 나머지 페이지에 적용
- 예시
- 예시

frontend/DANG-1153: Authenticated HOC 2가지 생성 및 적용

---

frontend/src/hooks/useAuth.ts

refactor: 로그인 성공시 provider, redirect Path 삭제
- 예시
- 예시

frontend/DANG-1160: 로그인 성공시 provider, redirect Path 삭제

---

backend/test/performance/utils/createMockEntity.util.ts

실수로 n개 만큼 생성하도록 해서 제대로 test data가 삽입되지 않았다.
https://www.notion.so/do0ori/createMockEntity-2c852b238c9744cb8ebbdb0c97051607
- 예시
- 예시

backend/DANG-1162: createMockEntity 오타 수정

---

backend/src/walk/test.walk.service.ts
backend/src/walk/walk.service.spec.ts
backend/src/walk/walk.service.ts

- select option 사용 및 bulk update로 성능 개선
- `isWalking`이 true이고 `MAX_WALK_TIME`이 지났으면 산책 중 상태를 초기화하도록 로직 구성 (기존에는 `isWalking`을 확인하지 않았음)
https://www.notion.so/do0ori/WalkService-TODO-da257f3336cb4f16b96570d0886b2140
- 예시
- 예시

backend/DANG-1163: WalkService TODO

---

frontend/src/pages/SignUp/index.tsx

refactor: 강아지 사진 추가시 홈으로 리다이렉트되는 문제
- 예시
- 예시

frontend/DANG-1169: 강아지 사진 추가시 홈으로 리다이렉트되는 문제

---

frontend/craco.config.cjs
frontend/package-lock.json
frontend/package.json

chore: front build 시간 측정 라이브러리 추가
- 예시
- 예시

frontend/DANG-1170: build 시간 측정 라이브러리 추가

---

frontend/public/index.html

refactor: %PUBLIC_URL% 관련 콘솔에러 해결
- 예시
- 예시

frontend/DANG-1171: %PUBLIC_URL% 관련 콘솔에러 해결

---

frontend/src/components/walk/WalkInfo.tsx
frontend/src/hooks/test/useGeolocation.test.ts
frontend/src/hooks/useGeolocation.ts
frontend/src/utils/distance.test.ts
frontend/src/utils/distance.ts

frontend/DANG-1138: 산책 단위 m 에서 10m로 수정

---

frontend/src/constants/walk.ts
frontend/src/hooks/useGeolocation.ts
frontend/src/pages/Walk.tsx
frontend/src/store/spinnerStore.ts
frontend/src/utils/time.ts

spinner add remove 문제 수정
산책 종료시 delay 추가
칼로리 계산 시간 기준에서 거리로 바꿈
거리(km) *몸무게 * activity factor
- 예시
- 예시

frontend/DANG-1178: 칼로리계산 시간기준에서 거리 기준으로 바꿈

---

backend/src/auth/interceptors/cookie.interceptor.ts

SameSite 속성을 생략해도 브라우저의 기본 값인 Lax가 사용되지만 명확하게 설정하는 것이 좋을 것 같아 추가했다.
https://www.notion.so/do0ori/Cookie-SameSite-8ab033aba2eb452a8dcc1f7c5a69f192
- 예시
- 예시

backend/DANG-1190: cookie SameSite 속성 명시

---

backend/src/journals/dtos/create-journal.dto.ts
backend/src/journals/journals.controller.ts
backend/src/journals/journals.service.ts
backend/src/journals/types/journal.types.ts

- request로 받은 데이터 타입은 ~Request
- response로 보낼 데이터 타입은  ~Response
- request, response 타입의 서브 타입은 ~Input, ~Output
- 쿼리 인자로 사용될 데이터 타입은 ~DatabaseInput
- 이름이 겹칠 때는 ForCreate, ForDetail 등 사용되는 API명으로 분류
- 예시
- 예시

backend/DANG-1202:  journals 타입 리팩토링

---

frontend/src/hooks/test/useGeolocation.test.ts
frontend/src/hooks/useGeolocation.ts
frontend/src/utils/geo.ts

https://namekdev.net/2014/06/iterative-version-of-ramer-douglas-peucker-line-simplification-algorithm/ 
이 글을 참고하여 포인트가 20개 될 때 마다 실시간으로 적용하도록 추가
(테스트 전)
- 예시
- 예시

frontend/DANG-1205: 지도 데이터 경량화를 위해 RDP 알고리즘 추가(테스트 전)

---

frontend/src/constants/walk.ts
frontend/src/hooks/useGeolocation.ts

frontend/DANG-1210: RDP 알고리즘에 쓰이는 엡실론 상수화

---

backend/src/journals/journals.entity.ts

RDP 알고리즘 적용에 따라 text(최대 65535바이트)로도 충분히 저장 가능한 사이즈가 되었으므로 타입을 변경했습니다.
링크 참고
https://velog.io/@anna951/%EB%8C%95%EB%8C%95%EC%9B%8C%ED%81%AC-%EA%B2%BD%EB%A1%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B2%BD%EB%9F%89%ED%99%94%ED%95%98%EA%B8%B0
- 예시
- 예시

backend/DANG-1212:  routes 컬럼 타입 medium text -> text로 변경

---

backend/src/journals/journals.service.ts

- routes의 타입을 text로 바꾸니 데이터가 날아가서 기존에 저장해둔 데이터로 update 함, 이후 unexpected end of JSON 에러가 나며 산책일지 상세 조회에서 경로가 조회되지 않는 상황
- 포맷에는 문제가 없어보임. rds에서 JSON_VALID 함수로 확인했을때도 모두 valid 하다고 나옴. 이유를 알 수 없어 JSON.parse 전 raw 데이터를 출력하는 디버그 로그로 확인하고자 함
- 예시
- 예시

backend/DANG-1213: chore: unexpected end of JSON 에러 디버그

---

backend/src/common/logger/winstonLogger.service.ts
backend/src/journals/journals.service.ts

- routes의 타입을 text로 바꾸니 데이터가 날아가서 기존에 저장해둔 데이터로 update 함, 이후 unexpected end of JSON 에러가 나며 산책일지 상세 조회에서 경로가 조회되지 않는 상황
- 포맷에는 문제가 없어보임. rds에서 JSON_VALID 함수로 확인했을때도 모두 valid 하다고 나옴. 이유를 알 수 없어 JSON.parse 전 raw 데이터를 출력하는 디버그 로그로 확인하고자 함
- prod 에서도 debug 로그를 찍도록 변경하였음. 작은 서비스에서는 이렇게 하기도 한다고 함 (from 마르코 멘토님) 유저가 없는 상태이니 출시 전까지라도 이렇게 해도 괜찮을 것 같음
- 예시
- 예시

backend/DANG-1213: unexpected end of JSON 에러 디버그

---

.github/workflows/backend_deploy.yaml
.gitignore
backend/server/tsconfig.build.json
backend/server/tsconfig.json
backend/weather-api-module/tsconfig.build.json

- tsconfig.build의 extend는 현재 모듈의 tsconfig를 가리키는 것이라 이전으로 되돌림
- gitignore에 backend/server/log 추가
- 도커 파일에 디버깅용 stage 추가
- 예시
- 예시

backend/DANG-1221: 빌드 오류 디버깅

---

.github/workflows/backend_deploy.yaml
backend/server/Dockerfile

-  Dockerfile에 디버깅 로그 추가, backend_deply.yaml 파일에서는 제거
- 예시
- 예시

backend/DANG-1222: 빌드 오류 디버깅 

---

backend/server/Dockerfile

- 빌드시 backend/tsconfig를 복사하도록 변경
- 이에 맞춰 backend_deploy.yaml 파일의 경로도 수정
- 예시
- 예시

backend/DANG-1223: backend/tsconfig를 복사하도록 Dockerfile, backend_deploy.yaml 변경

---

.github/workflows/backend_deploy.yaml
backend/server/Dockerfile

backend/DANG-1224: 디버그 로그 추가, 경로 추가 수정

---

backend/server/Dockerfile

- 다른 echo는 유용한 듯 해서 남겨둠
- 예시
- 예시

backend/DANG-1226: Dockerfile에서 디버깅용 echo 중 tsconfig 내용물 출력하는 부분 삭제

---

backend/server/Dockerfile

backend/DANG-1227: Dockerfile echo 문법 오류 수정

---

backend/weather-api-module/package-lock.json
backend/weather-api-module/package.json
backend/weather-api-module/src/data-store.ts
backend/weather-api-module/src/init.ts
backend/weather-api-module/src/scheduler.ts
backend/weather-api-module/src/weather-service.ts

요청이 왔던 지역에 대해
- 매일 새벽 두시 한번 하루 예보 데이터를 저장하는 스케줄러와
- 매일 한시간에 한번 실황 데이터를 저장하는 스케줄러를 등록했습니다
- node-cron 패키지를 사용
- init.ts 파일을 추가, 프로그램 구동시 cronJob을 등록
- 예시
- 예시

backend/DANG-1229: 날씨 API 모듈 스케줄러 구현

---

backend/weather-api-module/src/data/data-factory.ts
backend/weather-api-module/src/data/data-store.ts
backend/weather-api-module/src/env.ts
backend/weather-api-module/src/http/http-client.ts
backend/weather-api-module/src/http/http-server.ts
backend/weather-api-module/src/init.ts
backend/weather-api-module/src/logger/winston-logger.ts
backend/weather-api-module/src/public-weather-api-url/public-weather-api-url-builder.ts
backend/weather-api-module/src/public-weather-api-url/public-weather-api-url.ts
backend/weather-api-module/src/scheduler/scheduler.ts
backend/weather-api-module/src/url/url.ts
backend/weather-api-module/src/weather/weather-controller.ts
backend/weather-api-module/src/weather/weather-service.ts

- 노드의 https 모듈로 server 구현
- weather/ 엔드포인트에 대한 컨트롤러 구현
- init() 함수에서 loadConfig가 먼저 실행되도록 async/await를 사용해 초기화 함수 동기화
- Redis에 연결시 재연결 정책 설정 : 3초에 한번 다시 재연결 하고 5회 이상 실패시 리턴
- Request, Response 로그 추가
- 예시
- 예시

backend/DANG-1231: 날씨 API 모듈 서버 파트 구현

---

backend/weather-api-module/src/parser/parse-data.ts
backend/weather-api-module/src/public-weather-api-url/public-weather-api-url-builder.ts
backend/weather-api-module/src/public-weather-api-url/public-weather-api-url.ts
backend/weather-api-module/src/util.ts
backend/weather-api-module/src/weather/weather-controller.ts
backend/weather-api-module/src/weather/weather-service.ts

1. 관측 시간대 변경
- 당일 새벽 2시 관측 기준으로 데이터를 요청하면 당일 0시 ~ 2시까지는 날씨 정보가 비어있게 된다.
전날 11시를 기준으로 데이터를 요청해 하루 전체 시간대에 대한 정보를 저장하도록 변경했다.
2. 최저/최고 기온 가져오지 못하는 문제 수정
- 최소 기온 / 최대 기온은 하루 전체 데이터 중 특정 시간대에만 있는 정보인데 모든 시간대에서 해당 정보를 찾으려고 해서 없는 시간대에는 0으로 저장되는 문제가 있었다
- 전체 데이터를 돌아서 최소, 최대기온을 먼저 찾고 모든 시간대의 데이터에 해당 값으로 저장하도록 변경
- 예시
- 예시

backend/DANG-1233: 날씨 정보 오류 수정

---

.github/workflows/backend_deploy.yaml
.github/workflows/backend_weather_deploy.yaml
backend/weather-api-module/src/weather/weather-controller.ts

- --ignore-scripts 추가, husky 디렉토리 설정을 prepare가 아닌 다른 이름의 커맨드로 실행시키는 게 좋을 것 같음
- 백엔드 배포 워크플로우 파일의 트리거를 backend/server에 커밋이 일어났을 때로 변경
- 예시
- 예시

backend/DANG-1235: 날씨 API 배포 오류 수정

---

backend/weather-api-module/src/weather/weather-controller.ts

backend/DANG-1237: 배포 테스트

---

.github/workflows/backend_weather_deploy.yaml
backend/weather-api-module/src/weather/weather-controller.ts

backend/DANG-1238: 워크플로우 파일에서 run-weather.sh 경로 수정

---

.github/workflows/backend_weather_deploy.yaml
backend/weather-api-module/src/data/data-factory.ts

- 기준 경로가/home/opc/actions-runner/_work/dangdang-walk/dangdang-walk 였음
- 뎁스가 깊어서 절대경로로 변경
- 예시
- 예시

backend/DANG-1239: run-weather 경로 변경

---

.github/workflows/backend_weather_deploy.yaml
backend/weather-api-module/src/data/data-factory.ts

- 앞에 슬래쉬가 하나 안들어갔음
- run-weather 실행시 변수들도 출력
- 예시
- 예시

backend/DANG-1240: run-weather 경로 수정

---

.github/workflows/backend_weather_deploy.yaml
backend/weather-api-module/src/data/data-factory.ts

backend/DANG-1241: TAG 변수 스테이지간 공유하도록 변경

---

.github/workflows/backend_weather_deploy.yaml
backend/weather-api-module/src/data/data-factory.ts

각 스테이지에서 github-sha 잘라서 쓰도록 변경
- 예시
- 예시

backend/DANG-1242: tag 변수 할당 안되는 문제 수정 

---

backend/weather-api-module/Dockerfile

backend/DANG-1243: 도커파일 마지막 실행 파일명 수정 main.js -> init.js

---

.github/workflows/backend_weather_deploy.yaml
backend/weather-api-module/src/data/data-factory.ts

backend/DANG-1244: 디버깅용 출력 삭제

---

.github/workflows/backend_weather_deploy.yaml
backend/weather-api-module/src/init.ts

backend/DANG-1245: init.ts 에러 로깅에 에러 메세지 추가

---

.github/workflows/backend_weather_deploy.yaml
backend/weather-api-module/src/init.ts

backend/DANG-1247: 레디스 도커 실행 안되는 문제 수정

---

backend/weather-api-module/src/data/data-store.ts

- 배포환경에서는 redis-container를 써야 해서 redis 호스트를 환경변수로 설정
- 예시
- 예시

backend/DANG-1248: redis 연결시 host를 loacl과 prod에서 다르게 설정하도록 환경변수 설정

---

frontend/src/api/weather.ts
frontend/src/hooks/useWeather.ts
frontend/src/models/weather.ts

frontend/DANG-1232: 공공 날씨 API가 아닌 백엔드 날씨 API 모듈을 사용하도록 프론트엔드 코드 변경

---

backend/weather-api-module/src/data/data-store.ts
backend/weather-api-module/src/http/http-client.ts
backend/weather-api-module/src/http/public-weather-error.ts
backend/weather-api-module/src/logger/winston-logger.ts
backend/weather-api-module/src/parser/parse-data.ts
backend/weather-api-module/src/scheduler/scheduler.ts
backend/weather-api-module/src/weather/weather-service.ts
backend/weather-api-module/src/weather/weather-type.ts

- 관측 불가 지역에 대한 예외처리 추가
- 관측 정보가 없을 시에는 파싱 로직을 타지 않도록 변경
- 한시간 실황 데이터 파싱 로직에 SKY가 빠져있어서 추가
- cron job, redis에 대한 로그 보강
- 예시
- 예시

backend/DANG-1250: 에러 로직 수정, 로그 보강

---

backend/weather-api-module/src/logger/winston-logger.ts
backend/weather-api-module/src/weather/weather-controller.ts
backend/weather-api-module/src/weather/weather-service.ts

backend/DANG-1251: 기상청 API 요청에 대한 로그 추가

---

backend/server/package-lock.json
backend/server/package.json
backend/server/src/app.module.ts
backend/server/src/journals/journals.service.ts
backend/server/src/statistics/statistics.controller.ts
backend/server/src/statistics/statistics.module.ts
backend/server/src/statistics/statistics.service.ts

홈 화면에서 일주일 강아지 산책 통계 조회하는 API를 로컬 캐싱했습니다.
이벤트 방식으로 산책일지 생성시마다 캐시를 업데이트 하도록 최적화 했습니다.
- 예시
- 예시

backend/DANG-1252: 홈 화면 statistics 로컬 캐싱

---

backend/server/README.md

서버 리드미 번호가 안바뀐 부분 수정
- 예시
- 예시

backend/DANG-1259: 서버 리드미 번호가 안바뀐 부분 수정

---

frontend/src/api/dog.ts
frontend/src/components/home/AvailableDogCheck.tsx
frontend/src/components/home/AvailableDogCheckList.tsx
frontend/src/components/walk/DogFecesAndUrineCheckList.tsx
frontend/src/hooks/test/useWalkingDogs.test.ts
frontend/src/hooks/useWalkAvailableDog.ts
frontend/src/hooks/useWalkingDogs.ts
frontend/src/models/dog.ts
frontend/src/pages/Home.tsx
frontend/src/pages/Walk.tsx
frontend/src/utils/check.ts

- 강아지 객체에 포함된 체크 프로퍼티 제거하고 체크리스트 상태로 체크 관리
-
- 예시
- 예시

frontend/DANG-1257: 체크로직 수정

---

backend/server/tsconfig.json

server/tsconfig가 test/ 디렉토리 포함하도록 수정
- 예시
- 예시

backend/DANG-1262: server/tsconfig가 test/ 디렉토리 포함하도록 수정

---

backend/server/Dockerfile
backend/server/src/walk/walk.service.spec.ts

- 디렉토리 매핑이 잘못되어 빌드 에러 발생, 수정
- 불필요한 dev stage 삭제
- 반복되는 권한 설정, apk 설정 삭제
- 예시
- 예시

backend/DANG-1264: Dockerfile  빌드 에러 수정, 불필요한 코드 삭제

---

backend/server/src/breed/breed.repository.ts
backend/server/src/common/database/base.interface.ts
backend/server/src/common/database/typeorm.repository.ts
backend/server/src/dog-walk-day/dog-walk-day.repository.ts
backend/server/src/dogs/dogs.repository.ts
backend/server/src/excrements/excrements.repository.ts
backend/server/src/journals-dogs/journals-dogs.repository.ts
backend/server/src/journals/journals.repository.ts
backend/server/src/today-walk-time/today-walk-time.repository.ts
backend/server/src/users-dogs/users-dogs.repository.ts
backend/server/src/users/users.repository.ts

- 제네릭한 인터페이스를 추가
- 서비스레이어에서 구현체가 아닌 인터페이스를 사용함으로써 여러 데이터 소스에 대해 일관되게 접근할 수 있도록 함
- AbstractRepository의 이름을 TypeORMRepository로 변경해 TypeORM의 구현체임을 명시
- 예시
- 예시

backend/DANG-1265: repository 레이어에 인터페이스 추가

---

backend/server/src/auth/auth.service.spec.ts
backend/server/src/auth/auth.service.ts
backend/server/src/auth/oauth/oauth.module.ts
backend/server/src/auth/types/oauth-provider.type.ts

- 기존 문자열 기반 동적 서비스 호출 방식을 Map으로 통합 관리하도록 구조를 개선하여 OCP 준수
- OauthModule에서 OAUTH_REGISTRY를 통한 중앙 집중식 OAuth 서비스 관리 구현
- 관련 테스트 코드 리팩토링
https://www.notion.so/do0ori/OAuth-15b8ad358684802c9a8ce590263c8354
- 예시
- 예시

backend/DANG-1268: OAuth 리팩토링

---

backend/server/src/auth/auth.service.spec.ts
backend/server/src/auth/auth.service.ts
backend/server/src/auth/oauth/oauth.module.ts
backend/server/src/auth/types/oauth-provider.type.ts

Reverts dangdangwalk/dangdang-walk#901
(Deploy 에러)

Revert "backend/DANG-1268: OAuth 리팩토링"

---

.github/script/run_backend.sh
.github/script/test_run_backend.sh

- **백엔드 배포 스크립트 개선**
- 코드 구조화: 함수 모듈화 및 `main` 함수 도입으로 가독성과 유지보수성 향상.
- Blue-Green 배포 로직 분리 및 로깅 시스템 강화 (컬러 로깅, 상세 로그 메시지).
- 에러 처리 개선: AWS, Docker, Nginx 작업 실패 시 명확한 에러 메시지 출력 및 스크립트 종료.
- 헬스 체크 로직 개선: 재시도 횟수와 간격을 상수로 분리, 실패 시 적절한 종료 처리.
- **테스트 스크립트 추가**
- 모의(mock) 바이너리를 활용해 AWS, Docker, Nginx 등 주요 작업을 테스트.
- Blue-Green 배포 검증, 인자 누락, 작업 실패 등 다양한 시나리오 지원.
- 타임아웃 감지 및 상세 출력(Verbose 모드) 기능 추가.
- **상수 및 변수 관리 강화**
- 매직 넘버 제거 및 상수화(`readonly` 키워드 사용).
- 환경 변수 파일 검증 로직 추가 (존재 여부 및 읽기 권한 확인).
---
<details>
<summary>클릭하여 코드 보기</summary>
fuzzy@BOOK360-HWANGJK-PC MINGW64 /d/personal-project/dangdang-walk/.github/script (backend/DANG-1271)
$ ./test_run_backend.sh -v
Backend Deployment Tests
[DEBUG] Test environment setup completed at /tmp/test
Basic Deployment
when all configurations are valid
✓ …

backend/DANG-1271: 백엔드 배포 스크립트 run_backend.sh 리팩토링

---

Makefile
docker-compose-dev.yml

docker-compose-dev.yml 파일에서 불필요한 공백을 제거하고, front 서비스 관련 설정을 삭제했습니다.
주요 변경사항:
1. db, server, weather 서비스의 환경 변수 설정에서 불필요한 공백 제거
2. front 서비스 설정 삭제 (container_name, image, platform, restart, environment, env_file, volumes, working_dir, ports, networks, command)
- 예시
- 예시

infra/DANG-1272: docker-compose-dev.yml 파일 수정

---

backend/server/Dockerfile
docker-compose-dev.yml

기존 Dockerfile에는 log 폴더가 없을 시 log 폴더를 생성하도록 로직이 작성 되어 있습니다.
DockerCompose 마운트를 추가하여 Dockerfile 로직에 log 폴더 생성하는 로직을 제거 합니다.
Dockerfile과 docker-compose-dev.yml 파일을 수정하여 빌드 및 배포 프로세스를 개선했습니다.
Dockerfile 내 중복 로직과 가독성 및 레이어 계층을 줄이기 위해 코드를 리팩터링했습니다.
- 예시
- 예시

backend/DANG-1276: Dockerfile 및 docker-compose-dev.yml 수정

---

.github/workflows/backend_weather_deploy.yaml

backend weather-api-module 디렉토리를 backend weather 디렉토리로 변경하였습니다.
주요 변경사항:
1. GitHub Actions 워크플로우에서 경로를 backend/weather로 변경
2. Docker 이미지 이름을 dangdangwalk/weather로 변경
3. npm 작업 디렉토리를 backend/weather로 변경
4. Dockerfile 경로를 backend/weather로 변경
5. 환경 변수 파일 경로를 backend/weather로 변경
- 예시
- 예시

backend/DANG-1278: backend weather 디렉토리로 경로 변경

---

backend/docker-compose.yml
backend/server/Dockerfile

backend의 Docker 설정 파일을 수정하고 리소스 디렉토리를 추가했습니다.
주요 변경사항:
1. docker-compose.yml에서 server/resources 볼륨 마운트를 제거했습니다.
2. Dockerfile에 server/resources 디렉토리를 추가로 복사하도록 수정했습니다.
- 예시
- 예시

backend/DANG-1279: Docker 설정 파일 수정 및 리소스 디렉토리 추가
